load("//crates:defs.bzl", "rue_crate")

rue_crate(
    name = "rue-error",
    deps = [
        "//crates/rue-span:rue-span",
        "//third-party:lasso",
        "//third-party:thiserror",
    ],
)
