//! Stack alignment verification for AArch64.
//!
//! This module provides compile-time verification that the stack remains properly
//! aligned throughout function execution. The AAPCS64 ABI requires SP to be 16-byte
//! aligned at all times.
//!
//! # Background
//!
//! Unlike x86-64 where alignment is only required at call sites, AArch64 requires
//! the stack pointer to be 16-byte aligned at all times. Many AArch64 instructions
//! that access [SP] will fault if SP is not 16-byte aligned.
//!
//! # Verification Strategy
//!
//! We track a "stack depth" representing how many bytes have been pushed relative
//! to the aligned state after the prologue. Instructions that modify the stack
//! update this depth:
//!
//! - `stp x1, x2, [sp, #-16]!`: depth += 16 (store pair, pre-decrement)
//! - `ldp x1, x2, [sp], #16`: depth -= 16 (load pair, post-increment)
//! - `bl symbol`: verify depth % 16 == 0 (SP must be aligned at call)
//!
//! Note: The prologue is generated by the emitter, not present in the MIR. The
//! prologue ends with SP 16-byte aligned, so we start verification with depth = 0.
//!
//! # Limitations
//!
//! This verification pass operates on the instruction stream before emission,
//! when the prologue hasn't been added yet. We verify that the body of the function
//! maintains alignment assuming the prologue left SP aligned.
//!
//! The prologue's alignment is correct by construction (see `emit_prologue` in emit.rs).

use super::mir::{Aarch64Inst, Aarch64Mir, LabelId, Operand, Reg};
use crate::stack_verify::{self, StackVerifyAdapter};
use rue_error::{CompileError, CompileResult, ErrorKind};

/// Verifies that the stack is properly aligned throughout function execution.
///
/// This checks that:
/// 1. All call instructions occur when SP is 16-byte aligned
/// 2. STP/LDP sequences are balanced within basic blocks
/// 3. Control flow joins have consistent stack depths
///
/// # Arguments
///
/// * `mir` - The MIR instructions to verify (post-regalloc, pre-emit)
///
/// # Returns
///
/// `Ok(())` if verification passes, or `Err(CompileError)` with details about
/// the first alignment violation found.
pub fn verify_stack_alignment(mir: &Aarch64Mir) -> CompileResult<()> {
    stack_verify::verify(&Aarch64StackVerifyAdapter { mir })
}

struct Aarch64StackVerifyAdapter<'a> {
    mir: &'a Aarch64Mir,
}

impl StackVerifyAdapter for Aarch64StackVerifyAdapter<'_> {
    type Inst = Aarch64Inst;

    fn instructions(&self) -> &[Self::Inst] {
        self.mir.instructions()
    }

    fn stack_delta(&self, inst: &Self::Inst) -> i64 {
        match inst {
            // Store pair with pre-decrement: stp x1, x2, [sp, #offset]!
            // This pushes two registers onto the stack
            Aarch64Inst::StpPre { offset, .. } => {
                // offset is typically negative (e.g., -16 to allocate 16 bytes)
                // depth increases by |offset|
                (-*offset) as i64
            }

            // Load pair with post-increment: ldp x1, x2, [sp], #offset
            // This pops two registers from the stack
            Aarch64Inst::LdpPost { offset, .. } => {
                // offset is typically positive (e.g., 16 to deallocate 16 bytes)
                // depth decreases by offset
                -(*offset as i64)
            }

            // SubImm on SP: allocates stack space
            Aarch64Inst::SubImm { dst, src, imm } => {
                if is_sp(dst) && is_sp(src) {
                    // sub sp, sp, #imm → increases depth (allocates)
                    *imm as i64
                } else {
                    0
                }
            }

            // AddImm on SP: deallocates stack space
            Aarch64Inst::AddImm { dst, src, imm } => {
                if is_sp(dst) && is_sp(src) {
                    // add sp, sp, #imm → decreases depth (deallocates)
                    -(*imm as i64)
                } else {
                    0
                }
            }

            _ => 0,
        }
    }

    fn label(&self, inst: &Self::Inst) -> Option<LabelId> {
        match inst {
            Aarch64Inst::Label { id } => Some(*id),
            _ => None,
        }
    }

    fn jump_targets<'a>(&self, inst: &'a Self::Inst) -> &'a [LabelId] {
        match inst {
            Aarch64Inst::B { label }
            | Aarch64Inst::BCond { label, .. }
            | Aarch64Inst::Bvs { label }
            | Aarch64Inst::Bvc { label }
            | Aarch64Inst::Cbz { label, .. }
            | Aarch64Inst::Cbnz { label, .. } => std::slice::from_ref(label),
            _ => &[],
        }
    }

    fn is_return(&self, inst: &Self::Inst) -> bool {
        matches!(inst, Aarch64Inst::Ret)
    }

    fn alignment_violation(&self, inst: &Self::Inst, current_depth: i64) -> Option<String> {
        match inst {
            Aarch64Inst::Bl { .. } => {
                // At a call site, SP must be 16-byte aligned.
                // Unlike x86-64, the return address goes into LR, not pushed to stack,
                // so the callee sees SP at the same alignment as the caller.
                if current_depth % 16 != 0 {
                    Some(format!(
                        "call requires 16-byte aligned SP, but stack is {} bytes off",
                        current_depth % 16
                    ))
                } else {
                    None
                }
            }
            _ => None,
        }
    }

    fn error(
        &self,
        idx: usize,
        inst: &Self::Inst,
        current_depth: i64,
        message: String,
    ) -> CompileError {
        CompileError::without_span(ErrorKind::InternalCodegenError(format!(
            "stack alignment verification failed at instruction {}: {} (depth: {} bytes) - {}",
            idx, inst, current_depth, message
        )))
    }
}

/// Check if an operand is the stack pointer.
fn is_sp(op: &Operand) -> bool {
    matches!(op, Operand::Physical(Reg::Sp))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::aarch64::{Cond, Operand, Reg};

    fn make_mir(instructions: Vec<Aarch64Inst>) -> Aarch64Mir {
        let mut mir = Aarch64Mir::new();
        for inst in instructions {
            mir.push(inst);
        }
        mir
    }

    #[test]
    fn test_empty_function() {
        let mir = make_mir(vec![Aarch64Inst::Ret]);
        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_balanced_stp_ldp() {
        let mir = make_mir(vec![
            // Push two registers (16 bytes)
            Aarch64Inst::StpPre {
                src1: Operand::Physical(Reg::X19),
                src2: Operand::Physical(Reg::X20),
                offset: -16,
            },
            // Pop them back
            Aarch64Inst::LdpPost {
                dst1: Operand::Physical(Reg::X19),
                dst2: Operand::Physical(Reg::X20),
                offset: 16,
            },
            Aarch64Inst::Ret,
        ]);
        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_call_after_aligned_push() {
        // Two STP operations = 32 bytes, still aligned
        let mut mir = Aarch64Mir::new();
        let sym_id = mir.intern_symbol("foo");
        mir.push(Aarch64Inst::StpPre {
            src1: Operand::Physical(Reg::X19),
            src2: Operand::Physical(Reg::X20),
            offset: -16,
        });
        mir.push(Aarch64Inst::StpPre {
            src1: Operand::Physical(Reg::X21),
            src2: Operand::Physical(Reg::X22),
            offset: -16,
        });
        mir.push(Aarch64Inst::call(sym_id));
        mir.push(Aarch64Inst::LdpPost {
            dst1: Operand::Physical(Reg::X21),
            dst2: Operand::Physical(Reg::X22),
            offset: 16,
        });
        mir.push(Aarch64Inst::LdpPost {
            dst1: Operand::Physical(Reg::X19),
            dst2: Operand::Physical(Reg::X20),
            offset: 16,
        });
        mir.push(Aarch64Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_aligned_call() {
        let mut mir = Aarch64Mir::new();
        let sym_id = mir.intern_symbol("test_func");
        mir.push(Aarch64Inst::call(sym_id));
        mir.push(Aarch64Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_sub_add_sp_balanced() {
        // Sub SP, then call, then add SP back
        let mut mir = Aarch64Mir::new();
        let sym_id = mir.intern_symbol("foo");

        // Allocate 32 bytes (aligned)
        mir.push(Aarch64Inst::SubImm {
            dst: Operand::Physical(Reg::Sp),
            src: Operand::Physical(Reg::Sp),
            imm: 32,
        });
        // Call (should be aligned)
        mir.push(Aarch64Inst::call(sym_id));
        // Deallocate
        mir.push(Aarch64Inst::AddImm {
            dst: Operand::Physical(Reg::Sp),
            src: Operand::Physical(Reg::Sp),
            imm: 32,
        });
        mir.push(Aarch64Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_unaligned_sub_sp_fails() {
        // Sub SP by 8 (not 16-aligned), then call - should fail
        let mut mir = Aarch64Mir::new();
        let sym_id = mir.intern_symbol("foo");

        // Allocate 8 bytes (misaligned!)
        mir.push(Aarch64Inst::SubImm {
            dst: Operand::Physical(Reg::Sp),
            src: Operand::Physical(Reg::Sp),
            imm: 8,
        });
        // Call without proper alignment - should fail
        mir.push(Aarch64Inst::call(sym_id));
        mir.push(Aarch64Inst::Ret);

        let result = verify_stack_alignment(&mir);
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(err.to_string().contains("alignment"));
    }

    #[test]
    fn test_jump_with_consistent_depth() {
        let mut mir = Aarch64Mir::new();
        let label = mir.alloc_label();

        mir.push(Aarch64Inst::CmpImm {
            src: Operand::Physical(Reg::X0),
            imm: 0,
        });
        mir.push(Aarch64Inst::BCond {
            cond: Cond::Eq,
            label,
        });
        // Fall through path: no stack changes
        mir.push(Aarch64Inst::Label { id: label });
        mir.push(Aarch64Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_backward_jump_with_inconsistent_depth_fails_at_jump() {
        let mut mir = Aarch64Mir::new();
        let label = mir.alloc_label();
        mir.push(Aarch64Inst::Label { id: label });
        mir.push(Aarch64Inst::SubImm {
            dst: Operand::Physical(Reg::Sp),
            src: Operand::Physical(Reg::Sp),
            imm: 8,
        });
        mir.push(Aarch64Inst::B { label });

        let err = verify_stack_alignment(&mir).unwrap_err().to_string();
        assert!(err.contains("control flow join has inconsistent stack depth: expected 0, got 8"));
        assert!(err.contains("instruction 2"));
        assert!(err.contains("b .L"));
        assert!(err.contains("depth: 8 bytes"));
    }

    #[test]
    fn test_repeated_forward_jump_with_inconsistent_depth_fails_at_jump() {
        let mut mir = Aarch64Mir::new();
        let label = mir.alloc_label();
        mir.push(Aarch64Inst::BCond {
            cond: Cond::Eq,
            label,
        });
        mir.push(Aarch64Inst::SubImm {
            dst: Operand::Physical(Reg::Sp),
            src: Operand::Physical(Reg::Sp),
            imm: 8,
        });
        mir.push(Aarch64Inst::B { label });
        mir.push(Aarch64Inst::Label { id: label });
        mir.push(Aarch64Inst::Ret);

        let err = verify_stack_alignment(&mir).unwrap_err().to_string();
        assert!(err.contains("control flow join has inconsistent stack depth: expected 0, got 8"));
        assert!(err.contains("instruction 2"));
        assert!(err.contains("b .L"));
        assert!(err.contains("depth: 8 bytes"));
    }

    #[test]
    fn test_multiple_calls_aligned() {
        let mut mir = Aarch64Mir::new();
        let sym1 = mir.intern_symbol("func1");
        let sym2 = mir.intern_symbol("func2");

        mir.push(Aarch64Inst::call(sym1));
        mir.push(Aarch64Inst::call(sym2));
        mir.push(Aarch64Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_cbz_cbnz_branches() {
        let mut mir = Aarch64Mir::new();
        let label1 = mir.alloc_label();
        let label2 = mir.alloc_label();

        mir.push(Aarch64Inst::Cbz {
            src: Operand::Physical(Reg::X0),
            label: label1,
        });
        mir.push(Aarch64Inst::Cbnz {
            src: Operand::Physical(Reg::X1),
            label: label2,
        });
        mir.push(Aarch64Inst::Label { id: label1 });
        mir.push(Aarch64Inst::Label { id: label2 });
        mir.push(Aarch64Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_overflow_branch() {
        let mut mir = Aarch64Mir::new();
        let label = mir.alloc_label();

        mir.push(Aarch64Inst::Bvs { label });
        mir.push(Aarch64Inst::Label { id: label });
        mir.push(Aarch64Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_unbalanced_sub_sp_before_return_fails() {
        let mir = make_mir(vec![
            Aarch64Inst::SubImm {
                dst: Operand::Physical(Reg::Sp),
                src: Operand::Physical(Reg::Sp),
                imm: 16,
            },
            Aarch64Inst::Ret,
        ]);

        let result = verify_stack_alignment(&mir);
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(err.to_string().contains("balanced stack depth"));
    }
}
