#!/usr/bin/env python3
"""Generate the function-count scaling probe (RUE-1264).

One axis: the number of functions in a single module. Every function has the
same small body — a handful of arithmetic operations and one branch, enough
to give instruction selection, register allocation, and scheduling real
per-function work without concentrating cost in any single construct. The
pipeline from CFG construction through machine emission runs once per
function, so this probe isolates `cfg_and_optimization` and `backend`, where
a superlinear per-function regression would show first.

`main` roots every function through a flat accumulator chain: one statement
per function, no nesting growth with N (the RUE-1139 failure shape), because
an unrooted function would be dead to the demand-driven pipeline and the
probe would measure nothing. The root module's size therefore also grows
with N; that is the same axis, not a second one.

Deterministic on purpose: no timestamps, no randomness, sorted writes.
`--check` refuses drift from the committed sources; the epoch's
`workload_source_hashes` pin freezes the bytes independently.
"""

import argparse
import os
import sys

SIZES = [256, 1024]


def function_source(index: int) -> str:
    return "\n".join([
        "pub fn f_%04d(a: i64, b: i64) -> i64 {" % index,
        "    let t = a * 3 + b - %d;" % index,
        "    if t > a {",
        "        return t - b;",
        "    }",
        "    return t + b + %d;" % index,
        "}",
    ])


def functions_source(count: int) -> str:
    parts = [
        "// Generated by generate.py — do not edit by hand (RUE-1264).",
        "// %d functions of identical shape; the count is the only axis." % count,
        "",
    ]
    for index in range(count):
        parts.append(function_source(index))
        parts.append("")
    return "\n".join(parts)


def main_source(count: int) -> str:
    lines = [
        "// Generated by generate.py — do not edit by hand (RUE-1264).",
        "// Roots all %d functions through a flat accumulator chain." % count,
        'const funcs = @import("funcs.rue");',
        "",
        "fn main() -> i32 {",
        "    let mut acc: i64 = 0;",
    ]
    for index in range(count):
        lines.append("    acc = acc + funcs.f_%04d(%d, acc);" % (index, index))
    lines.extend([
        "    if acc == 20250815 {",
        "        return 1;",
        "    }",
        "    return 0;",
        "}",
        "",
    ])
    return "\n".join(lines)


def render(count: int) -> dict:
    return {
        "main.rue": main_source(count),
        "funcs.rue": functions_source(count),
    }


def run(check: bool) -> int:
    root = os.path.dirname(os.path.abspath(__file__))
    drift = []
    for count in SIZES:
        directory = os.path.join(root, "n%04d" % count)
        files = render(count)
        if check:
            expected = set(files)
            actual = {name for name in os.listdir(directory)
                      if name.endswith(".rue")} if os.path.isdir(directory) else set()
            for name in sorted(expected | actual):
                path = os.path.join(directory, name)
                if name not in expected:
                    drift.append("%s: not a generator output" % path)
                    continue
                if name not in actual:
                    drift.append("%s: missing" % path)
                    continue
                with open(path, "r", encoding="utf-8") as handle:
                    if handle.read() != files[name]:
                        drift.append("%s: differs from generator output" % path)
        else:
            os.makedirs(directory, exist_ok=True)
            for name in sorted(files):
                with open(os.path.join(directory, name), "w",
                          encoding="utf-8") as handle:
                    handle.write(files[name])
    if drift:
        for line in drift:
            print("scale_functions: %s" % line, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify committed sources match the generator")
    sys.exit(run(parser.parse_args().check))
