load("//crates:defs.bzl", "rue_crate")

filegroup(
    name = "runtime-abi-inventory-sources",
    srcs = glob(["src/**/*.rs"]),
    visibility = ["PUBLIC"],
)

rue_crate(
    name = "rue-oracle",
    deps = [
        "//crates/rue-compiler:rue-compiler",
        "//crates/rue-cfg:rue-cfg",
        "//crates/rue-air:rue-air",
        "//third-party:lasso",
    ],
)
