# Root BUCK file for the Rue programming language compiler
# This file defines project-wide targets and utilities

load("//tools/clippy:auto.bzl", "clippy_all_group")

# ==============================================================================
# Build Tools and Utilities
# ==============================================================================

# Expose dotslash buck2 for convenience
export_file(
    name = "buck2",
    src = "buck2", 
    visibility = ["PUBLIC"],
)

# Expose project scripts
export_file(
    name = "scripts",
    src = "scripts/",
    visibility = ["PUBLIC"],
)

# ==============================================================================
# Linting and Code Quality
# ==============================================================================

# Auto-discovered group of every //crates/**:clippy that exists
clippy_all_group(
    name = "clippy_all",
    root = "crates",
    visibility = ["PUBLIC"],
)

# Convenience alias for running clippy on all targets
alias(
    name = "clippy",
    actual = ":clippy_all",
    visibility = ["PUBLIC"],
)

# Format checking - use //tools/rustfmt:fmt_check_test
# Format fixing - use //tools/rustfmt:fmt_fix

# ==============================================================================
# Testing and CI/CD
# ==============================================================================


# Development utilities group
filegroup(
    name = "dev_tools",
    srcs = [
        ":buck2",
        ":scripts",
    ],
    visibility = ["PUBLIC"],
)

# ==============================================================================
# Documentation and Project Setup
# ==============================================================================

# Project documentation
filegroup(
    name = "docs", 
    srcs = glob(["docs/**/*"]),
    visibility = ["PUBLIC"],
)

# Project configuration files
filegroup(
    name = "config",
    srcs = [
        ".buckconfig",
        ".buckroot",
    ],
    visibility = ["PUBLIC"],
)

# ==============================================================================
# IDE Integration
# ==============================================================================

# Rust-Analyzer configuration (generated by //tools/bxl:rust_project.bxl)
# Note: rust-project.json is gitignored as it's user-specific
filegroup(
    name = "rust_project_json",
    srcs = glob(["rust-project.json"]),
    visibility = ["PUBLIC"],
)

# IDE configuration files
filegroup(
    name = "ide_config",
    srcs = glob([
        ".vscode/**/*",
        ".devcontainer/**/*",
    ]),
    visibility = ["PUBLIC"],
)

# ==============================================================================
# Convenient Aliases and Groups
# ==============================================================================

# All crates in the project
alias(
    name = "all_crates",
    actual = "//crates/rue:rue",
    visibility = ["PUBLIC"],
)

