load("//crates:defs.bzl", "rue_crate")

rue_crate(
    name = "rue-rir",
    deps = [
        "//crates/rue-builtins:rue-builtins",
        "//crates/rue-lexer:rue-lexer",
        "//crates/rue-error:rue-error",
        "//crates/rue-parser:rue-parser",
        "//crates/rue-span:rue-span",
        "//third-party:ahash",
        "//third-party:lasso",
    ],
)
