[package]
name = "rue"
version.workspace = true
edition.workspace = true

[[bin]]
name = "rue"
path = "src/main.rs"

[dependencies]
rue-compiler.workspace = true
rue-codegen.workspace = true
bpaf.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
criterion.workspace = true

[[bench]]
name = "compiler"
harness = false
