[package]
name = "rue"
version.workspace = true
edition.workspace = true

[[bin]]
name = "rue"
path = "src/main.rs"

[dependencies]
rue-compiler.workspace = true
rue-codegen.workspace = true
rue-diagnostic.workspace = true
atty.workspace = true
bpaf.workspace = true
tracing.workspace = true
anyhow.workspace = true

[dev-dependencies]
tempfile.workspace = true
criterion.workspace = true
rue-parser.workspace = true
rue-snapshot.workspace = true
rue-test-utils = { path = "../rue-test-utils" }

[[bench]]
name = "compiler"
harness = false
