load("//crates:defs.bzl", "rue_binary")

rue_binary(
    name = "rue-compiler-session-bench",
    deps = [
        "//crates/rue-air:rue-air",
        "//crates/rue-compiler:rue-compiler",
        "//crates/rue-span:rue-span",
        "//third-party:serde_json",
    ],
)
