load("@prelude//rust:cargo_package.bzl", "cargo")
load("//tools/rust:defs.bzl", "clippy_rust_library")

cargo.rust_library(
    name = "rue-target",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    visibility = ["PUBLIC"],
)

# Clippy version of the library target
clippy_rust_library(
    name = "clippy",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    visibility = ["PUBLIC"],
)