load("@prelude//rust:cargo_package.bzl", "cargo")

cargo.rust_library(
    name = "rue-target",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    visibility = ["PUBLIC"],
)