load("//crates:defs.bzl", "rue_crate")

rue_crate(
    name = "rue-lexer",
    deps = [
        "//crates/rue-error:rue-error",
        "//crates/rue-span:rue-span",
        "//third-party:lasso",
        "//third-party:logos",
    ],
)
