load("@prelude//rust:cargo_package.bzl", "cargo")

cargo.rust_library(
    name = "rue-lexer",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2021",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "test",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2021",
)

rust_test(
    name = "lexer_error_tests",
    srcs = glob(["tests/**/*.rs"]),
    crate_root = "tests/lexer_error_tests.rs",
    edition = "2021",
    deps = [":rue-lexer"],
)