load("@prelude//rust:cargo_package.bzl", "cargo")

cargo.rust_library(
    name = "rue-lowering",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//crates/rue-ir:rue-ir",
        "//crates/rue-lexer:rue-lexer",
        "//crates/rue-target:rue-target",
        "//third-party/rust:tracing",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "test",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//crates/rue-ir:rue-ir",
        "//crates/rue-lexer:rue-lexer",
        "//crates/rue-target:rue-target",
        "//third-party/rust:tracing",
    ],
)

rust_test(
    name = "test_direct_returns",
    srcs = glob(["tests/**/*.rs"]),
    crate_root = "tests/test_direct_returns.rs",
    edition = "2024",
    deps = [
        ":rue-lowering",
        "//crates/rue-ir:rue-ir",
        "//crates/rue-lexer:rue-lexer",
        "//crates/rue-target:rue-target",
        "//third-party/rust:tracing",
    ],
)