#!/usr/bin/env python3
"""Generate the type-instantiation scaling probe (RUE-1264).

One axis: the number of distinct generic instantiations. The module defines N
structurally identical POD structs and, for each, instantiates the same
generic collection (`std.arraybuf.ArrayBuf(S_i)`) through one small function
of fixed shape. Each instantiation forces its own specialization, layout, and
method-set analysis, so this probe isolates `semantic_analysis` — the
neighbourhood where RUE-1244's layout-cycle bug lived. The per-function body
is constant; only the count of distinct types varies.

`main` roots every function through a flat accumulator chain — one statement
per instantiation, no nesting growth with N (the RUE-1139 failure shape) —
because an unrooted function would be dead to the demand-driven pipeline.

Deterministic on purpose: no timestamps, no randomness, sorted writes.
`--check` refuses drift from the committed sources; the epoch's
`workload_source_hashes` pin freezes the bytes independently.
"""

import argparse
import os
import sys

SIZES = [32, 128]


def block_source(index: int) -> str:
    name = "S_%03d" % index
    return "\n".join([
        "pub struct %s {" % name,
        "    a: i64,",
        "    b: i64,",
        "}",
        "",
        "pub fn u_%03d() -> i64 {" % index,
        "    let Buf = std.arraybuf.ArrayBuf(%s);" % name,
        "    let mut items = Buf.new();",
        "    items.push(%s { a: %d, b: 2 });" % (name, index),
        "    let head = items.get_or(0, %s { a: 0, b: 0 });" % name,
        "    return head.a + head.b;",
        "}",
    ])


def types_source(count: int) -> str:
    parts = [
        "// Generated by generate.py — do not edit by hand (RUE-1264).",
        "// %d distinct ArrayBuf instantiations; the count is the only axis." % count,
        'const std = @import("std");',
        "",
    ]
    for index in range(count):
        parts.append(block_source(index))
        parts.append("")
    return "\n".join(parts)


def main_source(count: int) -> str:
    lines = [
        "// Generated by generate.py — do not edit by hand (RUE-1264).",
        "// Roots all %d instantiation sites through a flat chain." % count,
        'const types = @import("types.rue");',
        "",
        "fn main() -> i32 {",
        "    let mut acc: i64 = 0;",
    ]
    for index in range(count):
        lines.append("    acc = acc + types.u_%03d();" % index)
    lines.extend([
        "    if acc == -1 {",
        "        return 1;",
        "    }",
        "    return 0;",
        "}",
        "",
    ])
    return "\n".join(lines)


def render(count: int) -> dict:
    return {
        "main.rue": main_source(count),
        "types.rue": types_source(count),
    }


def run(check: bool) -> int:
    root = os.path.dirname(os.path.abspath(__file__))
    drift = []
    for count in SIZES:
        directory = os.path.join(root, "n%03d" % count)
        files = render(count)
        if check:
            expected = set(files)
            actual = {name for name in os.listdir(directory)
                      if name.endswith(".rue")} if os.path.isdir(directory) else set()
            for name in sorted(expected | actual):
                path = os.path.join(directory, name)
                if name not in expected:
                    drift.append("%s: not a generator output" % path)
                    continue
                if name not in actual:
                    drift.append("%s: missing" % path)
                    continue
                with open(path, "r", encoding="utf-8") as handle:
                    if handle.read() != files[name]:
                        drift.append("%s: differs from generator output" % path)
        else:
            os.makedirs(directory, exist_ok=True)
            for name in sorted(files):
                with open(os.path.join(directory, name), "w",
                          encoding="utf-8") as handle:
                    handle.write(files[name])
    if drift:
        for line in drift:
            print("scale_instantiations: %s" % line, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify committed sources match the generator")
    sys.exit(run(parser.parse_args().check))
