load("//crates:defs.bzl", "rue_binary")

rue_binary(
    name = "rue-spec",
    deps = [
        "//crates/rue-test-runner:rue-test-runner",
        "//third-party:libtest2-mimic",
        "//third-party:tempfile",
        "//third-party:toml",
    ],
)
