load("//crates:defs.bzl", "rue_crate")

rue_crate(
    name = "rue-codegen",
    test_platform = "native",
    deps = [
        "//crates/rue-air:rue-air",
        "//crates/rue-builtins:rue-builtins",
        "//crates/rue-cfg:rue-cfg",
        "//crates/rue-error:rue-error",
        "//crates/rue-runtime-abi:rue-runtime-abi",
        "//crates/rue-span:rue-span",
        "//crates/rue-target:rue-target",
        "//third-party:ahash",
        "//third-party:fixedbitset",
        "//third-party:lasso",
        "//third-party:smallvec",
        "//third-party:tracing",
    ],
)
