[package]
name = "rue-codegen"
version.workspace = true
edition.workspace = true

[dependencies]
rue-ast = { path = "../rue-ast" }
rue-lexer = { path = "../rue-lexer" }
rue-parser = { path = "../rue-parser" }
rue-semantic = { path = "../rue-semantic" }
rue-runtime = { path = "../rue-runtime" }
rue-ir = { path = "../rue-ir" }
rue-lowering = { path = "../rue-lowering" }
rue-optimize = { path = "../rue-optimize" }
indexmap.workspace = true
thiserror.workspace = true
object.workspace = true
tracing.workspace = true

[dev-dependencies]
criterion.workspace = true
regex.workspace = true
