[package]
name = "rue-codegen"
version.workspace = true
edition.workspace = true

[dependencies]
rue-ast.workspace = true
rue-lexer.workspace = true
rue-parser.workspace = true
rue-semantic.workspace = true
rue-ir.workspace = true
rue-lowering.workspace = true
rue-optimize.workspace = true
rue-target.workspace = true
indexmap.workspace = true
thiserror.workspace = true
object.workspace = true
tracing.workspace = true

[dev-dependencies]
criterion.workspace = true
regex.workspace = true
proptest.workspace = true
