[package]
name = "rue-codegen"
version.workspace = true
edition.workspace = true

[dependencies]
rue-ast = { path = "../rue-ast" }
rue-lexer = { path = "../rue-lexer" }
rue-parser = { path = "../rue-parser" }
rue-semantic = { path = "../rue-semantic" }
rue-runtime = { path = "../rue-runtime" }
rue-ir = { path = "../rue-ir" }
indexmap = "2"
thiserror = "2.0.12"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "alloc"
harness = false
