load("@prelude//rust:cargo_package.bzl", "cargo")

cargo.rust_library(
    name = "rue-ir",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//crates/rue-lexer:rue-lexer",
        "//crates/rue-target:rue-target",
        "//third-party/rust:rustc-hash",
        "//third-party/rust:tracing",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "test",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//crates/rue-lexer:rue-lexer",
        "//crates/rue-target:rue-target",
        "//third-party/rust:rustc-hash",
        "//third-party/rust:tracing",
    ],
)

rust_test(
    name = "test_hir_properties",
    srcs = glob(["tests/**/*.rs", "src/**/*.rs"]),
    crate_root = "tests/test_hir_properties.rs",
    edition = "2024",
    deps = [
        ":rue-ir",
        "//third-party/rust:proptest",
    ],
)

rust_test(
    name = "test_optimizer_properties",
    srcs = glob(["tests/**/*.rs", "src/**/*.rs"]),
    crate_root = "tests/test_optimizer_properties.rs",
    edition = "2024",
    deps = [
        ":rue-ir",
        "//third-party/rust:proptest",
    ],
)