//! Stack alignment verification for x86-64.
//!
//! This module provides compile-time verification that the stack remains properly
//! aligned throughout function execution. The System V AMD64 ABI requires RSP to
//! be 16-byte aligned at call sites.
//!
//! # Background
//!
//! After a `call` instruction, RSP points to the return address (8 bytes), leaving
//! RSP 8 bytes below a 16-byte boundary. Functions must ensure that before any
//! nested calls, RSP is again 16-byte aligned.
//!
//! # Verification Strategy
//!
//! We track a "stack depth" representing how many bytes have been pushed relative
//! to the aligned state after the prologue's `sub rsp, N`. Instructions that modify
//! the stack update this depth:
//!
//! - `push r64`: depth += 8
//! - `pop r64`: depth -= 8
//! - `call`: verify depth == 0 (RSP is 16-byte aligned)
//!
//! Note: The prologue is generated by the emitter, not present in the MIR. The
//! prologue ends with RSP 16-byte aligned, so we start verification with depth = 0.
//!
//! # Limitations
//!
//! This verification pass operates on the instruction stream before emission,
//! when the prologue hasn't been added yet. We verify that the body of the function
//! maintains alignment assuming the prologue left RSP aligned.
//!
//! The prologue's alignment is correct by construction (see `emit_prologue` in
//! emit.rs), and the starting-depth assumption is guaranteed to apply wherever
//! it matters: alignment is only checked at `call` instructions, any function
//! containing a call is planned as `FramePointer::Established`
//! (`codegen_pipeline::plan_frame_pointer`), and the emitter emits the
//! prologue for every established frame — even one with zero slots and no
//! callee-saved registers (RUE-1195). A function the emitter leaves without a
//! prologue is a frameless leaf, which contains no call for this pass to check.

use super::mir::{LabelId, Operand, Reg, X86Inst, X86Mir};
use crate::stack_verify::{self, StackVerifyAdapter};
use rue_error::{CompileError, CompileResult, ice_error};

/// Verifies that the stack is properly aligned throughout function execution.
///
/// This checks that:
/// 1. All call instructions occur when RSP is 16-byte aligned
/// 2. Push/pop sequences are balanced within basic blocks
/// 3. Control flow joins have consistent stack depths
///
/// # Arguments
///
/// * `mir` - The MIR instructions to verify (post-regalloc, pre-emit)
///
/// # Returns
///
/// `Ok(())` if verification passes, or `Err(CompileError)` with details about
/// the first alignment violation found.
pub fn verify_stack_alignment(mir: &X86Mir) -> CompileResult<()> {
    stack_verify::verify(&X86StackVerifyAdapter { mir })
}

struct X86StackVerifyAdapter<'a> {
    mir: &'a X86Mir,
}

impl StackVerifyAdapter for X86StackVerifyAdapter<'_> {
    type Inst = X86Inst;

    fn instructions(&self) -> &[Self::Inst] {
        self.mir.instructions()
    }

    fn stack_delta(&self, inst: &Self::Inst) -> i64 {
        match inst {
            // Instructions that increase stack depth (push onto stack).
            X86Inst::Push { .. } => 8,

            // Instructions that decrease stack depth (pop from stack). Negative
            // depths are allowed: the epilogue may pop callee-saved registers
            // before we've tracked their pushes (they're in the prologue, not
            // MIR).
            X86Inst::Pop { .. } => -8,

            // AddRI on RSP: used to deallocate stack space (positive imm) or
            // allocate stack space (negative imm, though rare in current codegen).
            X86Inst::AddRI { dst, imm } => {
                if let Operand::Physical(Reg::Rsp) = dst {
                    // add rsp, N → decreases depth (deallocates)
                    // add rsp, -N → increases depth (allocates)
                    -(*imm as i64)
                } else {
                    0
                }
            }

            _ => 0,
        }
    }

    fn label(&self, inst: &Self::Inst) -> Option<LabelId> {
        match inst {
            X86Inst::Label { id } => Some(*id),
            _ => None,
        }
    }

    fn jump_targets<'a>(&self, inst: &'a Self::Inst) -> &'a [LabelId] {
        match inst {
            X86Inst::Jz { label }
            | X86Inst::Jnz { label }
            | X86Inst::Jo { label }
            | X86Inst::Jno { label }
            | X86Inst::Jb { label }
            | X86Inst::Jae { label }
            | X86Inst::Jbe { label }
            | X86Inst::Jge { label }
            | X86Inst::Jle { label }
            | X86Inst::Jmp { label } => std::slice::from_ref(label),
            _ => &[],
        }
    }

    fn is_return(&self, inst: &Self::Inst) -> bool {
        matches!(inst, X86Inst::Ret)
    }

    fn alignment_violation(&self, inst: &Self::Inst, current_depth: i64) -> Option<String> {
        match inst {
            X86Inst::CallRel { .. } => {
                // At a call site, RSP must be 16-byte aligned.
                // Since the call will push an 8-byte return address,
                // the callee will see RSP 8 bytes below a 16-byte boundary,
                // which is correct (they'll push RBP to realign).
                //
                // Our depth tracking starts at 0 (aligned after prologue).
                // If depth % 16 != 0, we're misaligned.
                if current_depth % 16 != 0 {
                    Some(format!(
                        "call requires 16-byte aligned RSP, but stack is {} bytes off",
                        current_depth % 16
                    ))
                } else {
                    None
                }
            }
            _ => None,
        }
    }

    fn error(
        &self,
        idx: usize,
        inst: &Self::Inst,
        current_depth: i64,
        message: String,
    ) -> CompileError {
        ice_error!(
            "stack alignment verification failed",
            phase: "codegen/verify",
            details: {
                "instruction_index" => idx.to_string(),
                "instruction" => inst.to_string(),
                "stack_depth_bytes" => current_depth.to_string(),
                "message" => message
            }
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::x86_64::{Operand, Reg};

    fn make_mir(instructions: Vec<X86Inst>) -> X86Mir {
        let mut mir = X86Mir::new();
        for inst in instructions {
            mir.push(inst);
        }
        mir
    }

    #[test]
    fn test_empty_function() {
        let mir = make_mir(vec![X86Inst::Ret]);
        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_balanced_push_pop() {
        let mir = make_mir(vec![
            X86Inst::Push {
                src: Operand::Physical(Reg::Rax),
            },
            X86Inst::Push {
                src: Operand::Physical(Reg::Rbx),
            },
            X86Inst::Pop {
                dst: Operand::Physical(Reg::Rbx),
            },
            X86Inst::Pop {
                dst: Operand::Physical(Reg::Rax),
            },
            X86Inst::Ret,
        ]);
        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_call_after_even_pushes() {
        // Two pushes = 16 bytes, still aligned
        let mut mir = X86Mir::new();
        let sym_id = mir.intern_symbol("foo");
        mir.push(X86Inst::Push {
            src: Operand::Physical(Reg::Rax),
        });
        mir.push(X86Inst::Push {
            src: Operand::Physical(Reg::Rbx),
        });
        mir.push(X86Inst::call(sym_id));
        mir.push(X86Inst::Pop {
            dst: Operand::Physical(Reg::Rbx),
        });
        mir.push(X86Inst::Pop {
            dst: Operand::Physical(Reg::Rax),
        });
        mir.push(X86Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_call_after_odd_pushes_fails() {
        // One push = 8 bytes, misaligned
        let mut mir = X86Mir::new();
        let sym_id = mir.intern_symbol("foo");
        mir.push(X86Inst::Push {
            src: Operand::Physical(Reg::Rax),
        });
        mir.push(X86Inst::call(sym_id));
        mir.push(X86Inst::Pop {
            dst: Operand::Physical(Reg::Rax),
        });
        mir.push(X86Inst::Ret);

        let result = verify_stack_alignment(&mir);
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(err.to_string().contains("alignment"));
    }

    #[test]
    fn test_aligned_call() {
        let mut mir = X86Mir::new();
        let sym_id = mir.intern_symbol("test_func");
        mir.push(X86Inst::call(sym_id));
        mir.push(X86Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_jump_with_consistent_depth() {
        let mut mir = X86Mir::new();
        let label = mir.alloc_label();

        mir.push(X86Inst::CmpRI {
            src: Operand::Physical(Reg::Rax),
            imm: 0,
        });
        mir.push(X86Inst::Jz { label });
        // Fall through path: no pushes
        mir.push(X86Inst::Label { id: label });
        mir.push(X86Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_multiple_calls_aligned() {
        let mut mir = X86Mir::new();
        let sym1 = mir.intern_symbol("func1");
        let sym2 = mir.intern_symbol("func2");

        mir.push(X86Inst::call(sym1));
        mir.push(X86Inst::call(sym2));
        mir.push(X86Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_alignment_padding_with_addri() {
        // Simulates call with odd stack args: sub rsp,8 for padding, push arg, call, add rsp,16
        let mut mir = X86Mir::new();
        let sym_id = mir.intern_symbol("foo");

        // sub rsp, 8 (alignment padding) - implemented as add rsp, -8
        mir.push(X86Inst::AddRI {
            dst: Operand::Physical(Reg::Rsp),
            imm: -8,
        });
        // push one arg (8 bytes, total 16, aligned)
        mir.push(X86Inst::Push {
            src: Operand::Physical(Reg::Rax),
        });
        // call (should be aligned now)
        mir.push(X86Inst::call(sym_id));
        // cleanup: add rsp, 16 (arg + padding)
        mir.push(X86Inst::AddRI {
            dst: Operand::Physical(Reg::Rsp),
            imm: 16,
        });
        mir.push(X86Inst::Ret);

        assert!(verify_stack_alignment(&mir).is_ok());
    }

    #[test]
    fn test_unaligned_after_sub_rsp() {
        // sub rsp, 8 without corresponding push - misaligned call
        let mut mir = X86Mir::new();
        let sym_id = mir.intern_symbol("foo");

        // sub rsp, 8 via add rsp, -8
        mir.push(X86Inst::AddRI {
            dst: Operand::Physical(Reg::Rsp),
            imm: -8,
        });
        // call without proper alignment
        mir.push(X86Inst::call(sym_id));
        mir.push(X86Inst::Ret);

        let result = verify_stack_alignment(&mir);
        assert!(result.is_err());
    }

    #[test]
    fn test_unbalanced_push_before_return_fails() {
        let mir = make_mir(vec![
            X86Inst::Push {
                src: Operand::Physical(Reg::Rax),
            },
            X86Inst::Ret,
        ]);

        let result = verify_stack_alignment(&mir);
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(err.to_string().contains("balanced stack depth"));
    }

    #[test]
    fn test_unbalanced_sub_rsp_before_return_fails() {
        let mir = make_mir(vec![
            X86Inst::AddRI {
                dst: Operand::Physical(Reg::Rsp),
                imm: -8,
            },
            X86Inst::Ret,
        ]);

        let result = verify_stack_alignment(&mir);
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(err.to_string().contains("balanced stack depth"));
    }
}
