import Lean
import RueCore

/-!
# RueCore.Digest — the expert validation surface (RUE-2247)

Two generated reports, for a reader who knows type systems or proof
assistants and wants to decide whether to believe the mechanization without
trusting its authors:

* **`DIGEST.md`** (`lake exe ruecore-digest`): every theorem of the `RueCore`
  namespace with its fully elaborated statement and its doc-comment, and
  every definition those statements are written in terms of. Statements, not
  proofs — a proof body is not the evidence here, the kernel is.
* **`TRUST.md`** (`lake exe ruecore-digest --trust`): for every theorem, the
  axioms it actually depends on (`Lean.collectAxioms`), the `sorry` count
  taken from those axioms rather than from a grep, the axioms the package
  declares itself, and the pinned toolchain.

Both are read out of the compiled environment (`Lean.Environment`), so they
cannot drift from the sources the way a hand-written summary can: this module
imports nothing about the calculus and knows no declaration by name.

The definitions a statement is "written in terms of" are its transitive
*type*-level dependencies: the constants of the theorem's statement, of those
constants' types, of an inductive's constructor types, and — for a definition
that **is** a type or a predicate (its type ends in a sort) — of its value
too, since such a definition's body is part of what the statement says. A
function definition (`eval`, `check`) is reported by signature and
doc-comment; its body lives in the module named beside it. The result is a
file with a checkable closure property: every `RueCore` constant occurring in
a signature printed in `DIGEST.md` is itself an entry of `DIGEST.md`.

The fragment boundary — which calculus rules and which syntactic forms have a
core image at all — is not something the environment knows; it is `INDEX.md`'s,
generated by `scripts/validate-lean-xref-index.py`. The digest quotes that
file's coverage lines rather than restating them.
-/

open Lean

namespace RueCore.Digest

/-! ## What the reports cover -/

/-- (helper) The namespace both reports are about. -/
def root : Name := `RueCore

/-- (helper) Is this declaration one of the mechanization's own? -/
def inRoot (n : Name) : Bool := root.isPrefixOf n

/-- (helper) Last components Lean generates for a declaration of its own
accord (recursors, `deriving` images, equation lemmas). None of them is
authored, so none is evidence. -/
def generatedComponents : List String :=
  ["rec", "recOn", "casesOn", "brecOn", "below", "ibelow", "binductionOn",
   "noConfusion", "noConfusionType", "toCtorIdx", "ctorIdx", "ofNat_ctorIdx",
   "decEq", "repr", "reprPrec", "sizeOf", "sizeOf_spec", "ofNat", "eq", "eq_def",
   "inj", "injEq", "congr", "induct", "unfold", "beq", "hEq"]

/-- (helper) A field projection of a structure: implied by the structure's
own entry, so never listed separately. -/
def isFieldProjection (env : Environment) : Name → Bool
  | .str p f => isStructure env p && (getStructureFields env p).contains (Name.mkSimple f)
  | _ => false

/-- (helper) Declarations no report lists: Lean's own auxiliaries, the
`deriving` and `instance` images, field projections, and everything hanging
off one of those (a constructor's injectivity lemmas, a recursor's equations).
Nothing here was authored, so nothing here is evidence. -/
partial def isGenerated (env : Environment) : Name → Bool
  | .anonymous => false
  | .num _ _ => true
  | n@(.str p s) =>
      n.isInternalDetail || isFieldProjection env n
        || generatedComponents.contains s || s.startsWith "inst" || s.startsWith "_"
        || (match env.find? p with | some (.ctorInfo _) => true | _ => false)
        || isGenerated env p

/-- (helper) The declarations of the mechanization proper, in the imported
environment. -/
def declarations (env : Environment) : Array (Name × ConstantInfo) := Id.run do
  let mut out := #[]
  for (name, info) in env.constants.toList do
    if inRoot name && !isGenerated env name then
      out := out.push (name, info)
  return out.qsort (fun a b => a.1.toString < b.1.toString)

/-- (helper) Trim ASCII whitespace from both ends of a string. -/
def trimmed (s : String) : String := s.trimAscii.toString

/-! ## Dependencies of a statement -/

/-- (helper) Does this type end in a sort — is the declaration a type
abbreviation or a predicate, whose body is part of what a statement using it
says? -/
def isTypeLike (type : Lean.Expr) : Bool := type.getForallBody.isSort

/-- (helper) The constants a declaration's *statement* mentions: its type,
plus its constructors' types if it is an inductive, plus its value if it is a
type or a predicate. A theorem's proof is never read. -/
def statementDeps (env : Environment) (info : ConstantInfo) : Array Name :=
  let fromType := info.type.getUsedConstants
  let fromValue :=
    match info with
    | .defnInfo v => if isTypeLike v.type then v.value.getUsedConstants else #[]
    | _ => #[]
  let fromCtors :=
    match info with
    | .inductInfo v =>
        v.ctors.foldl (init := #[]) fun acc c =>
          match env.find? c with
          | some ci => acc ++ ci.type.getUsedConstants
          | none => acc
    | _ => #[]
  fromType ++ fromValue ++ fromCtors

/-- (helper) A dependency as the reports name it: a constructor stands for
its inductive, and anything outside the mechanization or generated by Lean is
dropped. -/
def normalizeDep (env : Environment) (n : Name) : Option Name :=
  let n := match env.find? n with
    | some (.ctorInfo v) => v.induct
    | _ => n
  if inRoot n && !isGenerated env n then some n else none

/-- (helper) The normalized statement dependencies of one declaration,
without duplicates and in name order. -/
def depsOf (env : Environment) (name : Name) : Array Name :=
  match env.find? name with
  | none => #[]
  | some info =>
    let names := (statementDeps env info).filterMap (normalizeDep env)
    let unique := names.foldl (init := (#[] : Array Name)) fun acc n =>
      if acc.contains n || n == name then acc else acc.push n
    unique.qsort (fun a b => a.toString < b.toString)

/-- (helper) Every declaration reachable from `seeds` through statement
dependencies: the constants a set of statements is written in terms of. -/
partial def closureFrom (env : Environment) : List Name → Array Name → Array Name
  | [], seen => seen
  | n :: rest, seen =>
      if seen.contains n then closureFrom env rest seen
      else closureFrom env ((depsOf env n).toList ++ rest) (seen.push n)

/-! ## Reading one declaration -/

/-- (helper) One declaration as a report prints it. -/
structure Item where
  /-- The declaration's fully qualified name. -/
  name : Name
  /-- `theorem`, `def`, `abbrev`, `inductive`, `structure`, `axiom`, … -/
  kind : String
  /-- The module it is declared in. -/
  module : Name
  /-- Import index and source line, for source order. -/
  order : Nat × Nat
  /-- Its doc-comment, verbatim. -/
  doc : Option String
  /-- Its fully elaborated signature, with no body. -/
  signature : String
  /-- For an inductive or a structure: each constructor's signature and
  doc-comment. -/
  ctors : Array (Name × String × Option String)
  /-- Its statement dependencies, normalized. -/
  deps : Array Name
  /-- Does its doc-comment mark it `(helper)`, the repository's
  cross-reference convention for a declaration that mechanizes nothing on its
  own (`README.md`)? -/
  helper : Bool
deriving Inhabited

/-- (helper) The declaration keyword a report prints for a constant. -/
def kindOf : ConstantInfo → String
  | .axiomInfo _ => "axiom"
  | .thmInfo _ => "theorem"
  | .opaqueInfo _ => "opaque"
  | .quotInfo _ => "quotient primitive"
  | .inductInfo _ => "inductive"
  | .ctorInfo _ => "constructor"
  | .recInfo _ => "recursor"
  | .defnInfo v => if isTypeLike v.type && v.hints.isAbbrev then "abbrev" else "def"

/-- (helper) Pretty-print a declaration's signature at the report's width. -/
def ppDecl (name : Name) : MetaM String := do
  let sig ← PrettyPrinter.ppSignature name
  return sig.fmt.pretty 78

/-- (helper) Pretty-print the body of a definition that *is* a type or a
predicate, under the binders its signature already names: for such a
definition the body is part of what a statement using it says, so a digest
that hid it would be hiding the claim. -/
def ppValue (value : Lean.Expr) : MetaM String :=
  Meta.lambdaTelescope value fun _ body => do
    return (← Meta.ppExpr body).pretty 74

/-- (helper) The source line a declaration starts on, or 0 when the
environment records no range for it. -/
def lineOf (name : Name) : CoreM Nat := do
  match ← findDeclarationRanges? name with
  | some ranges => return ranges.range.pos.line
  | none => return 0

/-- (helper) Read one declaration out of the environment. -/
def readItem (env : Environment) (name : Name) (info : ConstantInfo) : CoreM Item := do
  let doc := (← findDocString? env name).map trimmed
  let head ← Meta.MetaM.run' (ppDecl name)
  let signature ← match info with
    | .defnInfo v =>
        if isTypeLike v.type then
          let body ← Meta.MetaM.run' (ppValue v.value)
          pure (s!"{kindOf info} {head} :=\n  " ++ String.intercalate "\n  " (body.splitOn "\n"))
        else pure s!"{kindOf info} {head}"
    | _ => pure s!"{kindOf info} {head}"
  let moduleIdx := (env.getModuleIdxFor? name).map (·.toNat) |>.getD 0
  let module := env.header.moduleNames[moduleIdx]!
  let line ← lineOf name
  let mut ctors := #[]
  if let .inductInfo v := info then
    for c in v.ctors do
      let csig ← Meta.MetaM.run' (ppDecl c)
      let cdoc ← findDocString? env c
      ctors := ctors.push (c, csig, cdoc)
  return {
    name, kind := kindOf info, module, order := (moduleIdx, line), doc, signature, ctors,
    deps := depsOf env name,
    helper := ((doc.getD "").splitOn "(helper)").length > 1 }

/-! ## Ordering -/

/-- (helper) Source order: by import position, then by line, then by name, so
a report reads in the order the sources do. -/
def bySource (a b : Item) : Bool :=
  if a.order.1 != b.order.1 then a.order.1 < b.order.1
  else if a.order.2 != b.order.2 then a.order.2 < b.order.2
  else a.name.toString < b.name.toString

/-- (helper) A deterministic topological order: dependencies before
dependents, with a name tiebreak among the declarations that are ready, so
the generated file is stable under anything but a real change. -/
partial def topological (items : Array Item) : Array Item := Id.run do
  let names := items.map (·.name)
  let mut remaining := items.qsort (fun a b => a.name.toString < b.name.toString)
  let mut emitted : Array Name := #[]
  let mut out : Array Item := #[]
  while remaining.size > 0 do
    let ready := remaining.filter fun it =>
      it.deps.all fun d => !names.contains d || emitted.contains d
    -- A dependency cycle (mutual definitions) would leave nothing ready;
    -- fall back to the name order already imposed, rather than looping.
    let batch := if ready.size == 0 then remaining.extract 0 1 else ready
    for it in batch do
      out := out.push it
      emitted := emitted.push it.name
    remaining := remaining.filter fun it => !emitted.contains it.name
  return out

/-! ## Rendering -/

/-- (helper) A declaration's name without the `RueCore.` prefix both reports
are scoped to. -/
def shortName (n : Name) : String := (n.replacePrefix root .anonymous).toString

/-- (helper) A doc-comment folded onto one line, for a constructor's row. -/
def oneLine (s : String) : String :=
  String.intercalate " " (s.splitOn "\n" |>.map trimmed |>.filter (· != ""))

/-- (helper) One declaration, as a section of `DIGEST.md`. -/
def renderItem (it : Item) : List String :=
  let header := s!"### `{shortName it.name}`"
  let provenance := s!"*{it.kind}* · module `{it.module}`"
  let doc := match it.doc with
    | some d => ["", d]
    | none => ["", "*(no doc-comment)*"]
  let signature := ["", "```lean", it.signature, "```"]
  let ctors :=
    if it.ctors.isEmpty then []
    else
      ["", "Constructors:"] ++ (it.ctors.toList.flatMap fun (c, sig, cdoc) =>
        let note := match cdoc with
          | some d => s!" — {oneLine d}"
          | none => ""
        ["", s!"**`{shortName c}`**{note}", "", "```lean", sig, "```"])
  [header, "", provenance] ++ doc ++ signature ++ ctors ++ [""]

/-- (helper) The coverage sentence `INDEX.md` states under one of its
inverse tables. The digest quotes the generated index rather than recounting
the fragment boundary itself. -/
def coverageLine (index : String) (heading : String) : Option String :=
  let lines := index.splitOn "\n"
  let rec after : List String → Option String
    | [] => none
    | l :: rest =>
        if trimmed l == heading then
          (rest.find? (fun r => r.startsWith "Coverage:")).map
            (fun r => trimmed ((r.splitOn "Coverage:").getD 1 r))
        else after rest
  after lines

/-- (helper) The two coverage sentences, or an error naming what is missing:
a digest that cannot state its own scope is not one an expert can use. -/
def scopeSection (index : String) : Except String (List String) := do
  let rules ← (coverageLine index "## Calculus rules → declarations").elim
    (.error "INDEX.md has no coverage line under '## Calculus rules → declarations'") pure
  let forms ← (coverageLine index "## Abstract syntax forms → declarations").elim
    (.error "INDEX.md has no coverage line under '## Abstract syntax forms → declarations'") pure
  return [
    "## Scope",
    "",
    "The theorems below are about a *fragment* of the core calculus",
    "(`../01-core-calculus.md`). The generated `INDEX.md` states the boundary",
    "rule by rule and form by form; its two coverage lines, quoted here so the",
    "boundary is visible before the statements are:",
    "",
    s!"- *Calculus rules → declarations*: {rules}",
    s!"- *Abstract syntax forms → declarations*: {forms}",
    "",
    "A row reading *not yet mechanized* in those tables is a rule or a syntactic",
    "form no theorem below says anything about. Nothing in this file claims",
    "otherwise, and nothing outside the fragment is proved by omission.",
    ""]

/-- (helper) `DIGEST.md`: the theorems, the helper lemmas, and the
definitions their statements are written in terms of. -/
def renderDigest (index : String) (theorems helpers definitions : Array Item) :
    Except String String := do
  let scope ← scopeSection index
  let preamble := [
    "# RueCore statement digest",
    "",
    "<!-- Generated by `lake exe ruecore-digest`; do not edit by hand. -->",
    "",
    "Every theorem the mechanization proves, with the statement Lean checked —",
    "elaborated, not transcribed — and every definition those statements are",
    "written in terms of. Read it to decide what is claimed, before deciding",
    "whether to believe it; `TRUST.md` (`lake exe ruecore-digest --trust`) says",
    "what each proof rests on, and `GUIDE.md` has a thirty-minute validation",
    "procedure that uses both.",
    "",
    "What is *not* here, deliberately: proof bodies. A proof is checked by the",
    "kernel, and `TRUST.md` reports the axioms that check appealed to; reading",
    "the tactic script is not how this is validated. Definition bodies are not",
    "here either, with one exception: a definition that **is** a type or a",
    "predicate (`Ctx`, `CellMatches`, `InBounds`) is part of what a statement",
    "says, so the constants its body mentions are included as entries of their",
    "own. A function definition (`eval`, `check`) appears by signature and",
    "doc-comment, and its body lives in the module named beside it.",
    "",
    "That gives this file a property worth checking: every `RueCore` constant",
    "occurring in any signature printed below has an entry of its own below.",
    "Doc-comments are reproduced verbatim from the sources, and cite the",
    "calculus rule, section, or specification paragraph the declaration",
    "mechanizes (`README.md`, \"Doc-comment convention\"); `INDEX.md` is the",
    "generated inverse of those citations.",
    ""]
  let theoremSection := [
    "## Theorems",
    "",
    "In source order. These are the claims; a claim's meaning is its statement",
    "together with the definitions in the last section, not its doc-comment.",
    ""] ++ theorems.toList.flatMap renderItem
  let helperSection := [
    "## Helper lemmas",
    "",
    "Also proved, and listed so that nothing proved is hidden, but each is a",
    "step of another proof rather than a claim about the language: these are",
    "the declarations whose doc-comment marks them `(helper)` under the",
    "repository's cross-reference convention.",
    ""] ++ helpers.toList.flatMap renderItem
  let definitionSection := [
    "## Definitions the statements depend on",
    "",
    "In dependency order — every definition appears after everything its own",
    "statement mentions — with ties broken by name, so this file changes only",
    "when the mechanization does.",
    ""] ++ definitions.toList.flatMap renderItem
  return String.intercalate "\n"
    (preamble ++ scope ++ theoremSection ++ helperSection ++ definitionSection)

/-! ## The trust report -/

/-- (helper) Lean's two kernel-checked assumptions that this project's policy
allows: propositional extensionality and the soundness of quotient types. -/
def allowedAxioms : List Name := [``propext, ``Quot.sound]

/-- (helper) What one axiom means for the trust boundary, and whether its
presence should fail the report. -/
def axiomVerdict (a : Name) : String × Bool :=
  if allowedAxioms.contains a then ("standard, allowed by this project's policy", false)
  else if a == ``Classical.choice then
    ("kernel-checked, but outside this project's policy of constructive proofs", true)
  else if a == ``sorryAx then
    ("**hole**: an unfinished proof — this is what `sorry` leaves behind", true)
  else if a == ``Lean.ofReduceBool || a == ``Lean.ofReduceNat then
    ("**hole**: `native_decide` — a result the kernel did not verify itself", true)
  else if inRoot a then
    ("a declared assumption of this package; read its doc-comment below", false)
  else ("**unknown axiom** — review it before trusting anything that uses it", true)

/-- (helper) `TRUST.md`: every theorem with the axioms it actually depends
on, the `sorry` count read from those axioms, the package's own declared
assumptions, and the toolchain that checked all of it. The `Bool` is false
when the report contains something the reader must act on. -/
def renderTrust (theorems : Array (Item × Array Name)) (declared : Array Item) :
    String × Bool :=
  let flagged := theorems.filterMap fun (it, axs) =>
    let bad := axs.filter fun a => (axiomVerdict a).2
    if bad.isEmpty then none else some (it.name, bad)
  let sorryCount := (theorems.filter fun (_, axs) => axs.contains ``sorryAx).size
  let usedAxioms := theorems.foldl (init := (#[] : Array Name)) fun acc (_, axs) =>
    axs.foldl (init := acc) fun acc a => if acc.contains a then acc else acc.push a
  let verdict :=
    if flagged.isEmpty then
      ["Every theorem depends only on axioms this project's policy allows, and",
       "on nothing else. There is no `sorry` and no `native_decide` anywhere in",
       "the mechanization."]
    else
      ["**This report needs attention.** These theorems depend on an axiom",
       "outside the policy:",
       ""] ++ (flagged.toList.map fun (n, bad) =>
        s!"- `{shortName n}`: " ++ String.intercalate ", " (bad.toList.map (s!"`{·}`")))
  let header := [
    "# RueCore trust report",
    "",
    "<!-- Generated by `lake exe ruecore-digest --trust`; do not edit by hand. -->",
    "",
    "What each proved statement rests on. A Lean proof's trust boundary is the",
    "set of axioms the kernel appealed to while checking it, which",
    "`Lean.collectAxioms` reads out of the compiled environment — so the `sorry`",
    "count below is taken from the axioms, not from grepping the sources, and a",
    "`sorry` hidden behind a macro or an unfinished helper would still appear.",
    "`DIGEST.md` says what the statements are.",
    "",
    s!"- Toolchain: Lean {Lean.versionString} (the pin in `lean-toolchain` and in",
    "  `toolchains/lean/defs.bzl`, held equal by",
    "  `scripts/validate-lean-toolchain-pin.py`).",
    s!"- Theorems checked: {theorems.size}.",
    s!"- Proofs depending on `sorryAx`: {sorryCount}.",
    s!"- Axioms declared by this package: {declared.size}.",
    s!"- Distinct axioms used: " ++
      (if usedAxioms.isEmpty then "none."
       else String.intercalate ", "
         ((usedAxioms.qsort (fun a b => a.toString < b.toString)).toList.map (s!"`{·}`")) ++ "."),
    ""] ++ verdict ++ [""]
  let policy := [
    "## The policy, and what would break it",
    "",
    "Lean's logic has three standard axioms, all kernel-checked assumptions",
    "rather than holes: `propext` (propositional extensionality), `Quot.sound`",
    "(quotient soundness), and `Classical.choice`. This project uses the first",
    "two and not the third, so its proofs are constructive; `Classical.choice`",
    "is reported as a policy break rather than as an unsound step. Two other",
    "things are genuine holes: `sorryAx`, which is what an unfinished proof",
    "leaves behind, and `Lean.ofReduceBool`/`Lean.ofReduceNat`, which",
    "`native_decide` introduces for a result the kernel did not verify itself.",
    "An axiom this package declares is neither: it is a stated assumption, and",
    "it is listed with its doc-comment below so a reader can judge the source",
    "it comes from.",
    "",
    "The Buck target `root//:lean-ruecore` checks the same boundary from the",
    "other side: it re-checks the compiled modules with the toolchain's own",
    "`leanchecker`, prints `#print axioms` for the theorems it names in `trust`,",
    "and fails the build on any axiom outside `propext`/`Quot.sound`. This",
    "report covers *every* theorem, including the ones no trusted theorem uses.",
    "Neither check runs in CI yet: nothing in CI runs the Lean build until",
    "ADR-0097's gate is met (RUE-2241), so a reviewer regenerates both reports",
    "and diffs them against the committed copies.",
    ""]
  let table := [
    "## Every theorem and its axioms",
    "",
    "| Theorem | Module | Axioms |",
    "| --- | --- | --- |"] ++ (theorems.toList.map fun (it, axs) =>
      let cell :=
        if axs.isEmpty then "*none*"
        else String.intercalate ", " (axs.toList.map (s!"`{·}`"))
      s!"| `{shortName it.name}` | `{it.module}` | {cell} |") ++ [""]
  let legend := [
    "What each axiom that appears above means:",
    ""] ++ (usedAxioms.qsort (fun a b => a.toString < b.toString)).toList.map (fun a =>
      s!"- `{a}` — {(axiomVerdict a).1}") ++ [""]
  let assumptions :=
    if declared.isEmpty then
      ["## Declared assumptions",
       "",
       "None. The package declares no axiom of its own, so nothing here is",
       "assumed beyond Lean's logic. When the project's obligation interfaces",
       "arrive (the library obligations of §6.13.5, and the adequacy obligation",
       "`../03-metatheory.md` records), each will appear in this section with",
       "its doc-comment, which is where its source belongs.",
       ""]
    else
      ["## Declared assumptions",
       "",
       "Assumed, not proved. Each is an axiom this package declares; its",
       "doc-comment states where the assumption comes from and who owes the",
       "proof.",
       ""] ++ declared.toList.flatMap renderItem
  (String.intercalate "\n" (header ++ policy ++ table ++ legend ++ assumptions), flagged.isEmpty)

end RueCore.Digest
