load("//crates:defs.bzl", "rue_binary")

rue_binary(
    name = "rue-air-profile",
    deps = [
        "//crates/rue-air:rue-air",
        "//crates/rue-compiler:rue-compiler",
        "//crates/rue-span:rue-span",
        "//third-party:lasso",
        "//third-party:serde_json",
    ],
)
