#!/usr/bin/env python3
"""Generate the module-count scaling probe (RUE-1264).

One axis: the number of modules. Every module is identical in shape — one
trivial function and one import of the next module in the chain — so the only
thing that grows with N is the number of modules the compiler must discover,
parse, and assemble. Bodies are deliberately at the floor so semantic
analysis, CFG, and the backend contribute a constant per module and the
probe isolates `source_discovery_and_parsing` and `program_construction`.

The chain is an import chain, not an expression chain: nesting depth inside
any one file is constant regardless of N, so the parser's nesting ceiling can
never become the thing this probe measures (the RUE-1139 failure shape).

Deterministic on purpose: no timestamps, no randomness, sorted writes. The
committed sources are this script's output, and `--check` refuses drift so
the sources cannot be hand-maintained by accident. The epoch's
`workload_source_hashes` pin freezes the bytes a second, independent way.
"""

import argparse
import os
import sys

SIZES = [64, 256]


def module_name(index: int) -> str:
    return "m_%03d.rue" % index


def module_source(index: int, count: int) -> str:
    lines = [
        "// Generated by generate.py — do not edit by hand (RUE-1264).",
        "// Module %d of %d in the import chain." % (index, count),
    ]
    last = index == count - 1
    if not last:
        lines.append('const next = @import("%s");' % module_name(index + 1))
    lines.append("")
    if last:
        lines.append("pub fn f_%03d(x: i64) -> i64 {" % index)
        lines.append("    return x + %d;" % index)
        lines.append("}")
    else:
        lines.append("pub fn f_%03d(x: i64) -> i64 {" % index)
        lines.append("    return next.f_%03d(x) + 1;" % (index + 1))
        lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main_source(count: int) -> str:
    return "\n".join([
        "// Generated by generate.py — do not edit by hand (RUE-1264).",
        "// Roots the %d-module import chain through one call." % count,
        'const chain = @import("%s");' % module_name(0),
        "",
        "fn main() -> i32 {",
        "    if chain.f_000(0) > 0 {",
        "        return 0;",
        "    }",
        "    return 1;",
        "}",
        "",
    ])


def render(count: int) -> dict:
    files = {"main.rue": main_source(count)}
    for index in range(count):
        files[module_name(index)] = module_source(index, count)
    return files


def run(check: bool) -> int:
    root = os.path.dirname(os.path.abspath(__file__))
    drift = []
    for count in SIZES:
        directory = os.path.join(root, "n%03d" % count)
        files = render(count)
        if check:
            expected = set(files)
            actual = {name for name in os.listdir(directory)
                      if name.endswith(".rue")} if os.path.isdir(directory) else set()
            for name in sorted(expected | actual):
                path = os.path.join(directory, name)
                if name not in expected:
                    drift.append("%s: not a generator output" % path)
                    continue
                if name not in actual:
                    drift.append("%s: missing" % path)
                    continue
                with open(path, "r", encoding="utf-8") as handle:
                    if handle.read() != files[name]:
                        drift.append("%s: differs from generator output" % path)
        else:
            os.makedirs(directory, exist_ok=True)
            for name in sorted(files):
                with open(os.path.join(directory, name), "w",
                          encoding="utf-8") as handle:
                    handle.write(files[name])
    if drift:
        for line in drift:
            print("scale_modules: %s" % line, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify committed sources match the generator")
    sys.exit(run(parser.parse_args().check))
