load("@prelude//rust:cargo_package.bzl", "cargo")

cargo.rust_library(
    name = "rue-parser",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2021",
    deps = [
        "//crates/rue-ast:rue-ast",
        "//crates/rue-diagnostic:rue-diagnostic",
        "//crates/rue-lexer:rue-lexer",
        "//third-party/rust:thiserror",
        "//third-party/rust:serde",
        "//third-party/rust:serde_json",
        "//third-party/rust:toml",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "test",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2021",
    deps = [
        "//crates/rue-ast:rue-ast",
        "//crates/rue-diagnostic:rue-diagnostic",
        "//crates/rue-lexer:rue-lexer",
        "//third-party/rust:thiserror",
        "//third-party/rust:serde",
        "//third-party/rust:serde_json",
        "//third-party/rust:toml",
    ],
)