[package]
name = "rue-parser"
version.workspace = true
edition.workspace = true

[dependencies]
rue-ast.workspace = true
rue-diagnostic.workspace = true
rue-ir.workspace = true
rue-lexer.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

[dev-dependencies]
rue-snapshot.workspace = true
anyhow.workspace = true
proptest.workspace = true
regex.workspace = true