load("//crates:defs.bzl", "rue_crate")

rue_crate(
    name = "rue-test-runner",
    deps = [
        "//crates/rue-error:rue-error",
        "//third-party:serde",
        "//third-party:tempfile",
        "//third-party:toml",
    ],
)
