load("//crates:defs.bzl", "rue_binary")

rue_binary(
    name = "rue-parser-profile",
    deps = [
        "//crates/rue-lexer:rue-lexer",
        "//crates/rue-parser:rue-parser",
        "//crates/rue-span:rue-span",
        "//third-party:lasso",
        "//third-party:serde_json",
    ],
)
