[package]
name = "rue-compiler"
version.workspace = true
edition.workspace = true

[dependencies]
rue-ast.workspace = true
rue-diagnostic.workspace = true
rue-ir.workspace = true
rue-lexer.workspace = true
rue-parser.workspace = true
rue-semantic.workspace = true
rue-codegen.workspace = true
rue-lowering.workspace = true
rue-optimize.workspace = true
rue-target.workspace = true
salsa.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-tree.workspace = true
atty.workspace = true
thiserror.workspace = true

[dev-dependencies]
regex.workspace = true
criterion.workspace = true

[[bench]]
name = "ast_performance"
harness = false

