load("@prelude//rust:cargo_package.bzl", "cargo")

cargo.rust_library(
    name = "rue-snapshot",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//third-party/rust:similar",
        "//third-party/rust:serde",
        "//third-party/rust:serde_json",
        "//third-party/rust:toml",
        "//third-party/rust:anyhow",
        "//third-party/rust:camino",
        "//third-party/rust:once_cell",
        "//third-party/rust:regex",
        "//third-party/rust:tempfile",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "test",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//third-party/rust:similar",
        "//third-party/rust:serde",
        "//third-party/rust:serde_json",
        "//third-party/rust:toml",
        "//third-party/rust:anyhow",
        "//third-party/rust:camino",
        "//third-party/rust:once_cell",
        "//third-party/rust:regex",
        "//third-party/rust:tempfile",
    ],
)