load("//crates:defs.bzl", "rue_crate")

rue_crate(
    name = "rue-cfg",
    deps = [
        "//crates/rue-air:rue-air",
        "//crates/rue-error:rue-error",
        "//crates/rue-span:rue-span",
        "//third-party:lasso",
    ],
    test_deps = [
        "//crates/rue-lexer:rue-lexer",
        "//crates/rue-parser:rue-parser",
        "//crates/rue-rir:rue-rir",
    ],
)
