load("//crates:defs.bzl", "rue_binary")

rue_binary(
    name = "rue-fuzz",
    deps = [
        "//crates/rue-codegen:rue-codegen",
        "//crates/rue-air:rue-air",
        "//crates/rue-air:rue-air-fuzz-support",
        "//crates/rue-cfg:rue-cfg",
        "//crates/rue-cfg:rue-cfg-fuzz-support",
        "//crates/rue-compiler:rue-compiler",
        "//crates/rue-error:rue-error",
        "//crates/rue-lexer:rue-lexer",
        "//crates/rue-parser:rue-parser",
        "//crates/rue-rir:rue-rir",
        "//crates/rue-rir:rue-rir-fuzz-support",
        "//crates/rue-test-runner:rue-test-runner",
        "//third-party:anyhow",
        "//third-party:ahash",
        "//third-party:libc",
        "//third-party:proptest",
    ],
)
