load("//crates:defs.bzl", "rue_binary")

rue_binary(
    name = "rue-fuzz",
    deps = [
        "//crates/rue-codegen:rue-codegen",
        "//crates/rue-compiler:rue-compiler",
        "//crates/rue-lexer:rue-lexer",
        "//crates/rue-parser:rue-parser",
        "//third-party:anyhow",
        "//third-party:libc",
        "//third-party:proptest",
    ],
)
