load("@prelude//rust:cargo_package.bzl", "cargo")

cargo.rust_library(
    name = "rue-semantic",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//crates/rue-ast:rue-ast",
        "//crates/rue-diagnostic:rue-diagnostic",
        "//crates/rue-ir:rue-ir",
        "//crates/rue-lexer:rue-lexer",
        "//crates/rue-parser:rue-parser",
        "//third-party/rust:salsa",
        "//third-party/rust:thiserror",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "test",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//crates/rue-ast:rue-ast",
        "//crates/rue-diagnostic:rue-diagnostic",
        "//crates/rue-ir:rue-ir",
        "//crates/rue-lexer:rue-lexer",
        "//crates/rue-parser:rue-parser",
        "//third-party/rust:salsa",
        "//third-party/rust:thiserror",
    ],
)