load("@prelude//rust:cargo_package.bzl", "cargo")

cargo.rust_library(
    name = "rue-lsp-lib",
    srcs = glob(["src/**/*.rs"]),
    crate = "rue_lsp",
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//crates/rue-ast:rue-ast",
        "//crates/rue-compiler:rue-compiler", 
        "//crates/rue-lexer:rue-lexer",
        "//crates/rue-parser:rue-parser",
        "//crates/rue-semantic:rue-semantic",
        "//:tokio",
        "//:tower-lsp",
        "//:serde_json",
    ],
    visibility = ["PUBLIC"],
)

cargo.rust_binary(
    name = "rue-lsp",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    edition = "2024",
    deps = [
        ":rue-lsp-lib",
        "//:tokio",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "test",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//crates/rue-ast:rue-ast",
        "//crates/rue-compiler:rue-compiler", 
        "//crates/rue-lexer:rue-lexer",
        "//crates/rue-parser:rue-parser",
        "//crates/rue-semantic:rue-semantic",
        "//:tokio",
        "//:tower-lsp",
        "//:serde_json",
    ],
)