[package]
name = "rue-lsp"
version.workspace = true
edition.workspace = true

[[bin]]
name = "rue-lsp"
path = "src/main.rs"

[dependencies]
rue-compiler.workspace = true
rue-parser.workspace = true
rue-lexer.workspace = true
rue-ast.workspace = true
rue-semantic.workspace = true
rue-diagnostic.workspace = true
tokio.workspace = true
tower-lsp.workspace = true
serde_json.workspace = true