#!/usr/bin/env python3
"""Backend-scaling probe for the liveness dataflow (RUE-1545).

Two jobs, one script, so the RUE-1545 claim and the evidence that a change
preserved emitted bytes stay reproducible from the repository rather than from
a maintainer's shell history:

* **scaling** — generate a single-function probe whose only axis is the number
  of statements in one function body, and a second probe whose statements sit
  inside a loop so the *cyclic* liveness solver is the one under measurement.
  Compile each size with a release compiler and report the `backend` phase from
  `--benchmark-json`, plus the ratio between adjacent sizes. A linear backend
  doubles when the size doubles; a quadratic one quadruples.

* **digests** — compile a fixed set of programs at every optimisation level on
  every target and print the sha256 of each executable. Liveness feeds register
  allocation, so a representation change that alters one emitted byte is a bug.
  Capture the digests before a change, capture them after, and `compare` the
  two records.

The generated sources are written to a scratch directory and are deliberately
not committed: they are inputs to a measurement, not a maintained workload, and
the committed scale probes under `performance/workloads/` cover the axes the
scheduled curve tracks.

Python 3.9 and no third-party imports, per docs/process/tooling-baseline.md.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DEFAULT_SIZES = [1000, 2000, 4000, 8000]
DEFAULT_TARGETS = ["x86-64-linux", "aarch64-linux"]
DIGEST_TARGETS = ["x86-64-linux", "aarch64-linux", "aarch64-macos"]
OPT_LEVELS = ["-O0", "-O1", "-O2", "-O3"]


# ----------------------------------------------------------------------------
# Probe sources
# ----------------------------------------------------------------------------


def straight_line_source(count):
    """`acc = acc + k * (acc % m);` repeated `count` times in one function.

    One function, one straight-line body: the size of a single MIR body is the
    only axis. Every statement reads the previous accumulator and mints fresh
    temporaries, so instruction count and virtual-register count grow together
    — which is what makes an instructions x vregs table quadratic.
    """
    lines = [
        "// Generated by scripts/liveness-scale-probe.py (RUE-1545).",
        "// %d straight-line statements in one function body." % count,
        "",
        "fn main() -> i32 {",
        "    let mut acc: i64 = 1;",
        "    let k: i64 = 7;",
        "    let m: i64 = 1000003;",
    ]
    for _ in range(count):
        lines.append("    acc = acc + k * (acc % m);")
    lines.extend([
        "    if acc == 0 {",
        "        return 1;",
        "    }",
        "    return 0;",
        "}",
        "",
    ])
    return "\n".join(lines)


def looped_source(count):
    """The same statements, wrapped in a loop so the body carries a back edge.

    A back edge selects the cyclic liveness solver, which has to reach a fixed
    point rather than converging in one reverse sweep. The loop runs once, so
    the compiled program does the same work as the straight-line probe; only
    the shape of the control-flow graph the backend sees differs.
    """
    lines = [
        "// Generated by scripts/liveness-scale-probe.py (RUE-1545).",
        "// %d statements inside a loop body: one back edge, same axis." % count,
        "",
        "fn main() -> i32 {",
        "    let mut acc: i64 = 1;",
        "    let k: i64 = 7;",
        "    let m: i64 = 1000003;",
        "    let mut i: i64 = 0;",
        "    while i < 1 {",
    ]
    for _ in range(count):
        lines.append("        acc = acc + k * (acc % m);")
    lines.extend([
        "        i = i + 1;",
        "    }",
        "    if acc == 0 {",
        "        return 1;",
        "    }",
        "    return 0;",
        "}",
        "",
    ])
    return "\n".join(lines)


SHAPES = {
    "straight": straight_line_source,
    "looped": looped_source,
}


def write_probes(directory, sizes, shapes):
    """Materialize every probe source; return {(shape, size): path}."""
    paths = {}
    for shape in shapes:
        render = SHAPES[shape]
        for size in sizes:
            probe_dir = os.path.join(directory, "%s_n%05d" % (shape, size))
            os.makedirs(probe_dir, exist_ok=True)
            path = os.path.join(probe_dir, "main.rue")
            with open(path, "w", encoding="utf-8") as handle:
                handle.write(render(size))
            paths[(shape, size)] = path
    return paths


# ----------------------------------------------------------------------------
# Compiler invocation
# ----------------------------------------------------------------------------


def compiler_env():
    env = dict(os.environ)
    env.setdefault("RUE_STD_PATH", os.path.join(REPO, "std"))
    return env


def compile_once(rue, source, output, opt, target, extra=()):
    command = [rue, source, "-o", output, opt, "--target", target, "-j1"]
    command.extend(extra)
    return subprocess.run(command, stdout=subprocess.PIPE,
                          stderr=subprocess.PIPE, universal_newlines=True,
                          env=compiler_env(), cwd=REPO)


def backend_ns(rue, source, opt, target):
    """One compile; return the nanoseconds the run charged to `backend`."""
    work = tempfile.mkdtemp(prefix="rue-1545-run-")
    try:
        output = os.path.join(work, "probe.out")
        result = compile_once(rue, source, output, opt, target,
                              extra=["--benchmark-json"])
        if result.returncode != 0:
            raise SystemExit(
                "probe compile failed (%s %s %s):\n%s"
                % (source, opt, target, result.stderr))
        report = json.loads(result.stdout)
    finally:
        shutil.rmtree(work, ignore_errors=True)
    return int(report["phase_accounting"]["phase_ns"]["backend"])


# ----------------------------------------------------------------------------
# Scaling
# ----------------------------------------------------------------------------


def run_scaling(args):
    directory = args.work or tempfile.mkdtemp(prefix="rue-1545-")
    os.makedirs(directory, exist_ok=True)
    shapes = args.shapes.split(",")
    sizes = [int(value) for value in args.sizes.split(",")]
    paths = write_probes(directory, sizes, shapes)

    record = {"label": args.label, "opt": args.opt, "target": args.target,
              "repeat": args.repeat, "sizes": sizes, "shapes": shapes,
              "backend_ms": {}}
    for shape in shapes:
        print("== %s probe (%s, %s, best of %d) =="
              % (shape, args.opt, args.target, args.repeat))
        print("%8s  %12s  %8s" % ("N", "backend ms", "ratio"))
        previous = None
        for size in sizes:
            samples = [backend_ns(args.rue, paths[(shape, size)], args.opt,
                                  args.target)
                       for _ in range(args.repeat)]
            best = min(samples) / 1000000.0
            record["backend_ms"]["%s/%d" % (shape, size)] = best
            ratio = "" if previous is None else "%.2fx" % (best / previous)
            print("%8d  %12.1f  %8s" % (size, best, ratio))
            previous = best
        print()
    if args.json:
        with open(args.json, "w", encoding="utf-8") as handle:
            json.dump(record, handle, indent=2, sort_keys=True)
            handle.write("\n")
        print("wrote %s" % args.json)
    if not args.work:
        shutil.rmtree(directory, ignore_errors=True)
    return 0


# ----------------------------------------------------------------------------
# Digests
# ----------------------------------------------------------------------------


def sha256_file(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def run_digests(args):
    directory = args.work or tempfile.mkdtemp(prefix="rue-1545-digest-")
    os.makedirs(directory, exist_ok=True)
    sizes = [int(value) for value in args.sizes.split(",")]
    shapes = args.shapes.split(",")
    probes = write_probes(directory, sizes, shapes)

    programs = [("lattice",
                 os.path.join(REPO, "examples", "lattice", "main.rue"),
                 DIGEST_TARGETS)]
    for key in sorted(probes):
        shape, size = key
        programs.append(("%s_n%05d" % (shape, size), probes[key],
                         DEFAULT_TARGETS))

    digests = {}
    work = tempfile.mkdtemp(prefix="rue-1545-out-")
    try:
        for name, source, targets in programs:
            for target in targets:
                for opt in OPT_LEVELS:
                    output = os.path.join(work, "out")
                    result = compile_once(args.rue, source, output, opt, target)
                    key = "%s|%s|%s" % (name, target, opt)
                    if result.returncode != 0:
                        digests[key] = "COMPILE-FAILED"
                        print("%s  %s" % (key, digests[key]))
                        print(result.stderr, file=sys.stderr)
                        continue
                    digests[key] = sha256_file(output)
                    os.remove(output)
                    print("%s  %s" % (key, digests[key]))
    finally:
        shutil.rmtree(work, ignore_errors=True)
    with open(args.out, "w", encoding="utf-8") as handle:
        json.dump({"digests": digests}, handle, indent=2, sort_keys=True)
        handle.write("\n")
    print("wrote %s (%d executables)" % (args.out, len(digests)))
    if not args.work:
        shutil.rmtree(directory, ignore_errors=True)
    return 0


def run_compare(args):
    with open(args.before, encoding="utf-8") as handle:
        before = json.load(handle)["digests"]
    with open(args.after, encoding="utf-8") as handle:
        after = json.load(handle)["digests"]
    unpaired = sorted(set(before) ^ set(after))
    differing = sorted(key for key in set(before) & set(after)
                       if before[key] != after[key])
    for key in unpaired:
        print("only in one record: %s" % key)
    for key in differing:
        print("DIFFERS: %s\n  before %s\n  after  %s"
              % (key, before[key], after[key]))
    if unpaired or differing:
        print("%d executables differ, %d unpaired"
              % (len(differing), len(unpaired)))
        return 1
    print("all %d executables identical" % len(before))
    return 0


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command")

    scaling = sub.add_parser("scaling",
                             help="backend-phase timings per probe size")
    scaling.add_argument("--rue", required=True, help="release compiler binary")
    scaling.add_argument("--sizes",
                         default=",".join(str(n) for n in DEFAULT_SIZES))
    scaling.add_argument("--shapes", default="straight,looped")
    scaling.add_argument("--opt", default="-O3")
    scaling.add_argument("--target", default="x86-64-linux")
    scaling.add_argument("--repeat", type=int, default=3)
    scaling.add_argument("--label", default="")
    scaling.add_argument("--work",
                         help="keep generated sources in this directory")
    scaling.add_argument("--json", help="write the measurements here")
    scaling.set_defaults(func=run_scaling)

    digests = sub.add_parser("digests",
                             help="sha256 of every emitted executable")
    digests.add_argument("--rue", required=True, help="release compiler binary")
    digests.add_argument("--sizes",
                         default=",".join(str(n) for n in DEFAULT_SIZES))
    digests.add_argument("--shapes", default="straight,looped")
    digests.add_argument("--out", required=True,
                         help="write the digest record here")
    digests.add_argument("--work",
                         help="keep generated sources in this directory")
    digests.set_defaults(func=run_digests)

    compare = sub.add_parser("compare", help="compare two digest records")
    compare.add_argument("before")
    compare.add_argument("after")
    compare.set_defaults(func=run_compare)

    args = parser.parse_args()
    if args.command is None:
        parser.print_help()
        return 2
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
