#!/usr/bin/env python3
"""The Caldera generator drift gate.

The committed sources under `examples/caldera/` are generator output, and the
example doubles as the 100K-line capacity corpus the CLI suite compiles. The
generator writes in place and `--check` asserts only the size contract, so
until this gate existed nothing compared the two: the corpus was migrated to
compound assignment while the generator kept emitting the long form, and the
782-file drift sat unnoticed until an audit regenerated by hand. This test
regenerates into the sandbox copy and byte-compares against the committed
corpus, so the next divergence fails a pull request instead of waiting for
the next hand run.

Determinism is asserted separately because a single regeneration cannot see
it: a generator that varied its output between runs would agree with the
corpus exactly once, at commit time, and start failing for whoever touches
it next.
"""

from __future__ import annotations

import filecmp
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
GENERATOR = REPO / "scripts" / "generate-caldera.py"
CORPUS = REPO / "examples" / "caldera"


def corpus_files(root: Path) -> list[Path]:
    return sorted(path.relative_to(root) for path in root.rglob("*") if path.is_file())


class CalderaGeneratorTests(unittest.TestCase):
    def test_committed_corpus_matches_its_generator(self) -> None:
        with tempfile.TemporaryDirectory() as scratch:
            committed = Path(scratch) / "committed"
            shutil.copytree(CORPUS, committed)

            result = subprocess.run(
                [sys.executable, str(GENERATOR), "--check"],
                capture_output=True,
                text=True,
            )
            self.assertEqual(
                result.returncode,
                0,
                f"generator --check failed:\n{result.stdout}{result.stderr}",
            )

            regenerated = corpus_files(CORPUS)
            self.assertEqual(
                corpus_files(committed),
                regenerated,
                "regeneration changed the corpus file set",
            )
            drifted = [
                str(rel)
                for rel in regenerated
                if not filecmp.cmp(committed / rel, CORPUS / rel, shallow=False)
            ]
            self.assertEqual(
                drifted,
                [],
                "committed examples/caldera no longer matches its generator; "
                "regenerate with scripts/generate-caldera.py or fix the generator",
            )

    def test_generator_is_deterministic(self) -> None:
        first = subprocess.run(
            [sys.executable, str(GENERATOR), "--check"],
            capture_output=True,
            text=True,
        )
        second = subprocess.run(
            [sys.executable, str(GENERATOR), "--check"],
            capture_output=True,
            text=True,
        )
        self.assertEqual(first.returncode, 0, first.stderr)
        self.assertEqual(second.returncode, 0, second.stderr)
        self.assertEqual(
            first.stdout,
            second.stdout,
            "generator digest line varies between runs on one tree",
        )


if __name__ == "__main__":
    unittest.main()
