#!/usr/bin/env python3
"""The Caldera generator drift gate.

The committed sources under `examples/caldera/` are generator output, and the
example doubles as the 100K-line capacity corpus the CLI suite compiles. The
generator writes in place and `--check` asserts only the size contract, so
until this gate existed nothing compared the two: the corpus was migrated to
compound assignment while the generator kept emitting the long form, and the
782-file drift sat unnoticed until an audit regenerated by hand. This test
regenerates and byte-compares against the committed corpus, so the next
divergence fails a pull request instead of waiting for the next hand run.

The regeneration runs in a scratch copy, never against the checkout. The
generator resolves its output directory relative to its own path, and this
test executes in place from the source tree, so running it directly would
rewrite the real `examples/caldera` — byte-identical, but with fresh file
metadata, which races the compiler's discovery-epoch stability check in any
concurrently running scan action (the `caldera-canary` premerge failure
mode). Build and test actions must not mutate the source tree; the scratch
copy keeps that invariant.

Determinism is asserted separately because a single regeneration cannot see
it: a generator that varied its output between runs would agree with the
corpus exactly once, at commit time, and start failing for whoever touches
it next.
"""

from __future__ import annotations

import filecmp
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
GENERATOR = REPO / "scripts" / "generate-caldera.py"
CORPUS = REPO / "examples" / "caldera"


def corpus_files(root: Path) -> list[Path]:
    return sorted(path.relative_to(root) for path in root.rglob("*") if path.is_file())


def regenerate_in_scratch(scratch: Path) -> tuple[subprocess.CompletedProcess, Path]:
    """Run the generator inside a scratch tree and return its output corpus.

    The generator writes to `../examples/caldera` relative to itself, so a
    copy of the script under `scratch/scripts/` confines every write to the
    scratch tree.
    """
    scripts_dir = scratch / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    scratch_generator = scripts_dir / GENERATOR.name
    shutil.copy2(GENERATOR, scratch_generator)
    out = scratch / "examples" / "caldera"
    out.mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        [sys.executable, str(scratch_generator), "--check"],
        capture_output=True,
        text=True,
    )
    return result, out


class CalderaGeneratorTests(unittest.TestCase):
    def test_committed_corpus_matches_its_generator(self) -> None:
        with tempfile.TemporaryDirectory() as scratch:
            result, regenerated_root = regenerate_in_scratch(Path(scratch))
            self.assertEqual(
                result.returncode,
                0,
                f"generator --check failed:\n{result.stdout}{result.stderr}",
            )

            committed = corpus_files(CORPUS)
            regenerated = corpus_files(regenerated_root)
            self.assertEqual(
                committed,
                regenerated,
                "regeneration produced a different corpus file set",
            )
            drifted = [
                str(rel)
                for rel in committed
                if not filecmp.cmp(CORPUS / rel, regenerated_root / rel, shallow=False)
            ]
            self.assertEqual(
                drifted,
                [],
                "committed examples/caldera no longer matches its generator; "
                "regenerate with scripts/generate-caldera.py or fix the generator",
            )

    def test_generator_is_deterministic(self) -> None:
        with tempfile.TemporaryDirectory() as first_dir, tempfile.TemporaryDirectory() as second_dir:
            first, _ = regenerate_in_scratch(Path(first_dir))
            second, _ = regenerate_in_scratch(Path(second_dir))
            self.assertEqual(first.returncode, 0, first.stderr)
            self.assertEqual(second.returncode, 0, second.stderr)
            self.assertEqual(
                first.stdout,
                second.stdout,
                "generator digest line varies between runs on one tree",
            )


if __name__ == "__main__":
    unittest.main()
