#!/usr/bin/env python3
"""Generate and check the RueCore cross-reference index (RUE-2245).

The mechanization (``docs/formal/lean/RueCore/*.lean``) cites the calculus
(``docs/formal/01-core-calculus.md``) from its doc-comments: a rule label as
the calculus writes it (``(Use-Move)``, ``(D-Let)``, ``(@Drop)``), a section
(``§5.5``), or a prose-specification paragraph (``3.8:73``). This gate reads
those doc-comments and the calculus and writes ``docs/formal/lean/INDEX.md``:
every declaration with what it cites, and the inverse, every labeled rule and
every section of the calculus's §5 and §6 with the declarations that mechanize
it or *not yet mechanized*. A third inverse covers the calculus's §2 grammar:
every alternative of the ``T``/``p``/``e`` productions with the constructor
that mechanizes it, from the explicit table ``SYNTAX_FORMS`` below. The
inverses are what make the fragment boundary visible instead of inferred.

The index cannot rot silently because the gate fails when:

* a declaration in a rule-bearing module has no doc-comment, or a doc-comment
  with no citation, unless the comment says ``(helper)``;
* a doc-comment cites a rule label the calculus does not define;
* the calculus grows or renames a §2 alternative ``SYNTAX_FORMS`` has no row
  for, or a row names a Lean constructor the sources no longer declare;
* the committed ``INDEX.md`` differs from what the sources generate (run
  ``--write`` to refresh it).

A module whose declarations are programs rather than rules (``Examples.lean``,
``Corpus.lean``) says ``xref: examples`` in its module docstring; its
declarations are indexed when they cite something and are never required to.
The conventions are spelled out for slice authors in ``docs/formal/lean/README.md``.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gatelib import run_gate

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_LEAN_DIR = ROOT / "docs" / "formal" / "lean"
DEFAULT_CALCULUS = ROOT / "docs" / "formal" / "01-core-calculus.md"
INDEX_NAME = "INDEX.md"
GENERATED_MARKER = "<!-- Generated by scripts/validate-lean-xref-index.py --write; do not edit by hand. -->"

# Rule-bearing modules are the default; a module opts out with this marker in
# its module docstring.
EXAMPLES_MARKER = "xref: examples"
HELPER_MARKER = "(helper)"

# Declaration keywords at column 0. `instance` and `example` are not indexed:
# an instance has no name worth citing and an example is a check, not a rule.
DECL_LINE = re.compile(
    r"^(?:(?:private|protected|noncomputable|partial|unsafe|scoped)\s+)*"
    r"(?P<kw>theorem|lemma|def|abbrev|inductive|structure|opaque|axiom)\s+"
    r"(?P<name>[^\s:({\[]+)"
)
CONSTRUCTOR_LINE = re.compile(r"^\s+\|\s+(?P<name>[^\s:({\[]+)")
ATTRIBUTE_PREFIX = re.compile(r"^(?:@\[[^\]]*\]\s*)+")
NAMESPACE_LINE = re.compile(r"^namespace\s+(?P<name>\S+)")
# `section`, `noncomputable section`, `mutual`: blocks that `end` closes
# without qualifying names.
BLOCK_LINE = re.compile(r"^(?:noncomputable\s+)?(?:section|mutual)\b")
END_LINE = re.compile(r"^end(?:\s+(?P<name>\S+))?\s*$")
# `set_option … in` / `open … in`: a prefix of the declaration that follows.
CONTINUATION_LINE = re.compile(r".*\bin$")

SECTION_CITATION = re.compile(r"§(\d+(?:\.\d+)*)")
PARAGRAPH_CITATION = re.compile(r"(?<![\d.])(\d+\.\d+):(\d+)(?!\d)")
# Any parenthesized label; which of them are rule citations is decided
# against the calculus's own inventory, and a label that looks like a rule
# (`(D-Foo)`, `(Use-Bar)`) but is not one is an error.
PAREN_LABEL = re.compile(r"\((@?[A-Z][A-Za-z0-9]*(?:-[A-Za-z0-9@]+)*)\)")
RULE_SHAPED = re.compile(r"^(?:D-)?@?[A-Z][a-z]*(?:-[A-Z@][A-Za-z]*)+$|^@[A-Z][A-Za-z]*$")

CALCULUS_HEADING = re.compile(r"^(?P<hashes>#{2,4})\s+(?P<number>\d+(?:\.\d+)*)\.?\s+(?P<title>.+?)\s*$")
CALCULUS_RULE = re.compile(r"─+\s*\((?P<label>[^)\s]+)\)")

# The §2 grammar block: ``T ::= first`` opens a production and each following
# ``| alternative  -- comment`` line is one alternative of it. Only the three
# productions a fragment of the core can mechanize are inventoried; ``D``,
# ``pat``, ``a``, ``F``, ``b``, and ``P`` are declaration and call shapes the
# fragment has no image of at all.
SYNTAX_SECTION = "2"
SYNTAX_PRODUCTION = re.compile(r"^\s*(?P<nt>[A-Za-z]+) ::= (?P<alt>.*)$")
SYNTAX_ALTERNATIVE = re.compile(r"^\s*\|\s+(?P<alt>.*)$")
SYNTAX_NONTERMINALS = ("T", "p", "e")
SYNTAX_TITLES = {"T": "types", "p": "places", "e": "expressions"}
ROOT_NAMESPACE = "RueCore"

# What the mechanization does with each §2 alternative, keyed by the
# alternative exactly as the calculus writes it. The status is one of:
#
# * ``"yes"`` — the fragment has this form, in the constructors named;
# * ``"partial"`` — a restricted or abstract stand-in for the form itself; the
#   note says what is missing, so the row is never read as full coverage;
# * ``"stand-in"`` — the fragment has no image of the form, but a construct of
#   the core stands in for part of its ownership shape. The row reads *not yet
#   mechanized* and the note names the stand-in, which is the rule
#   ``docs/formal/lean/README.md`` already states for the rules table ("A label
#   is a claim"): a stand-in is not coverage of the form it stands in for.
#   The constructors are still listed here, so the gate still checks that they
#   exist;
# * ``"no"`` — not yet mechanized; the note says what it would need.
#
# The table is explicit rather than inferred because only a human can say
# whether `mkres` really is a struct literal's image. It cannot rot: the gate
# fails on an alternative with no row, on a row for an alternative the
# calculus no longer has, and on a row naming a constructor the Lean sources
# no longer declare.
SYNTAX_FORMS: Dict[Tuple[str, str], Tuple[str, List[str], str]] = {
    ("T", "int(w, s)"): (
        "yes",
        ["Ty.int", "IntWidth", "Sign"],
        "every width and signedness, carried by the type, by the machine value "
        "(§6.1's `n_T`) and by a literal (`4.1:2`); `InBounds` is the `min_T ≤ n ≤ "
        "max_T` side condition and `valOf`/`wrapInt` are §6.4's `val_{w,s}(β_w(·))`",
    ),
    ("T", "float(w)"): ("no", [], "floats are in the core (§5.8, §6.4) and outside the fragment"),
    ("T", "bool"): ("yes", ["Ty.bool"], ""),
    ("T", "unit"): ("yes", ["Ty.unit"], ""),
    ("T", "never"): (
        "stand-in",
        ["Typed.ret", "Typed.panic"],
        "`return` and `@panic` are in the fragment (§5.7, §5.8) but `never` is not "
        "a type here: both rules fold (Sub-Never) in by concluding at any type, "
        "which is sound because `never` has no values (`3.4:1`), and neither ever "
        "needs a `HasTy` case. `break` and an infinite `loop` are the never-typed "
        "forms the fragment still has no image of",
    ),
    ("T", "S"): (
        "partial",
        ["Ty.struct", "StructDecl"],
        "a monomorphic struct declared by the program: named fields by position, "
        "the `@copy`/`linear` attribute, and whether it declares a destructor, with "
        "`class(S)` the field join of §3 (`WfStructs` is the equation). No "
        "projection and no partial move, so no per-field §5.6 drop obligation "
        "(RUE-2231), and no generics",
    ),
    ("T", "E"): ("no", [], "enums and their variants are outside the fragment"),
    ("T", "[T; n]"): ("no", [], "arrays and array indexing are outside the fragment"),
    ("p", "x"): (
        "yes",
        ["Expr.use", "Expr.drop", "Expr.assign"],
        "a place is a whole binding, written as a de Bruijn index rather than a "
        "name (elaboration resolves names), so it has no constructor of its own: "
        "it is the index argument of the three forms that take a place",
    ),
    ("p", "p . f"): (
        "no",
        [],
        "no field projection, hence no partial move and no per-field drop obligation",
    ),
    ("p", "p [ e ]"): ("no", [], "no array indexing, hence no `3.8:73` element-wise form"),
    ("e", "lit"): (
        "yes",
        ["Expr.intLit", "Expr.boolLit", "Expr.unitLit"],
        "an integer literal carries the `int(w,s)` elaboration resolved for it "
        "(`4.1:2`); float literals follow `float(w)`",
    ),
    ("e", "p"): ("yes", ["Expr.use"], "the §4.2 use, typed by (Use-Copy)/(Use-Move)"),
    ("e", "e1 ⊕ e2"): (
        "partial",
        ["Expr.binop", "BinOp"],
        "the whole integer operator set — `+ - * / %`, `& | ^`, `<< >>` — with "
        "§6.4's traps and its `val_{w,s}(β_w(·))` bit semantics; the float "
        "operators follow `float(w)`",
    ),
    ("e", "⊖ e"): (
        "partial",
        ["Expr.unop", "UnOp"],
        "`neg` on a signed integer, `not` on `bool`, and `bitnot` on any integer, "
        "by (Neg)/(Not)/(BitNot) §5.8; float negation follows `float(w)`",
    ),
    ("e", "e1 ≟ e2"): (
        "no",
        [],
        "equality compare borrows its operands (§4.1, `4.3:3f`) and the fragment has no loans",
    ),
    ("e", "e1 ⋚ e2"): (
        "partial",
        ["Expr.binop", "BinOp"],
        "all four ordering compares on integers, by (Ord) §5.8; the float ordering "
        "of (Float-Ord) follows `float(w)`",
    ),
    ("e", "S { f1: e1, ..., fk: ek }"): (
        "yes",
        ["Expr.mkStruct"],
        "one initializer per declared field, presented in declaration order "
        "(`3.6:15`: elaboration reorders a surface literal) and typed left to "
        "right with Σ threaded, by (Struct-Intro) §5.8",
    ),
    ("e", "E :: K ( e1, ..., em )"): ("no", [], "follows `E`: no enums, so no variant construction"),
    ("e", "[ e1, ..., en ]"): ("no", [], "follows `[T; n]`: no arrays, so no array construction"),
    ("e", "g ( a1, ..., am )"): (
        "partial",
        ["Expr.call"],
        "every argument by value: no `inout`/`borrow` argument forms, so no "
        "`Λ_call`, no law-of-exclusivity premise and no call-entry recheck, and no "
        "(Call-Bottom) companion since the fragment has no `never` type. "
        "`RueCore.Expr.consume` remains beside it as the fragment's whole-value "
        "struct elimination: it reads the first field's payload and consumes the "
        "value, which is the ownership shape of a one-argument by-value call and "
        "the stand-in for the projection `p . f` the calculus eliminates a struct "
        "through",
    ),
    ("e", "p . f ( e1, ..., ek )"): (
        "no",
        [],
        "an accessor (ADR-0062) yields a place and needs the loans §5.4 gives it",
    ),
    ("e", "@drop ( p )"): ("yes", ["Expr.drop"], "whole bindings only, as `p` above"),
    ("e", "@panic ( s )"): (
        "partial",
        ["Expr.panic"],
        "the message is a string *literal* carried by the form rather than an "
        "operand expression, because the fragment has no string type — so "
        "(Panic-Operand) §5.8 has no instance here. (Panic) itself is mechanized, "
        "with (Sub-Never) folded in and no scope-exit obligation, which is §5.7's "
        "`⊥_panic` exemption",
    ),
    ("e", "@dbg ( e )"): (
        "yes",
        ["Expr.dbg", "Event.dbg"],
        "an `int(w,s)` or `bool` operand ((Dbg) §5.8; floats follow `float(w)`), "
        "appending §6.12's observable output to the same trace the destructors "
        "write to, so the two channels come out in the order they happened",
    ),
    ("e", "@intCast ( e )"): (
        "yes",
        ["Expr.intCast"],
        "the target type is the one elaboration took from the use site "
        "(`4.13:26`), and `4.13:28`'s trap is §6.4's `(D-Int-Cast-Trap)`",
    ),
    ("e", "@f ( e1, ..., ek )"): ("no", [], "follows `float(w)`"),
    ("e", "if e0 { e1 } else { e2 }"): ("yes", ["Expr.ite"], "with the §5.5 branch join"),
    ("e", "match e0 { pat1 => e1, ..., patk => ek }"): ("no", [], "follows `E`: no enums, so no arms to match"),
    ("e", "let μ x = e1 ; e2"): (
        "yes",
        ["Expr.letIn"],
        "carrying the `μ ∈ {∅, mut}` mark, with §5.6's scope exit folded in",
    ),
    ("e", "e1 ; e2"): ("yes", ["Expr.seq"], "with the `3.8:64` discard check"),
    ("e", "loop { e }"): (
        "no",
        [],
        "no loops, so no `loopβ` boundary on the control stack and no back-edge "
        "invariance premise; the interpreter is fuel-indexed (calls already make "
        "its recursion unbounded), so a loop would not cost it its totality",
    ),
    ("e", "break"): ("no", [], "follows `loop { e }` and `never`"),
    ("e", "return e"): (
        "yes",
        ["Expr.ret"],
        "(Return-Value) §5.7 with (Sub-Never) folded into the same rule, and "
        "§5.6's obligation carried at the `⊥_exit` edge; (Return-Bottom) is "
        "subsumed rather than separate",
    ),
    ("e", "assign p = e"): (
        "yes",
        ["Expr.assign"],
        "whole bindings only, with the `3.8:77` premise on the post-RHS state",
    ),
}


class Declaration:
    """One indexed Lean declaration or constructor."""

    def __init__(self, module: str, name: str, kind: str, line: int, doc: Optional[str]) -> None:
        self.module = module
        self.name = name
        self.kind = kind
        self.line = line
        self.doc = doc
        self.sections: List[str] = []
        self.rules: List[str] = []
        self.paragraphs: List[str] = []
        self.unknown_rules: List[str] = []
        self.helper = False

    @property
    def cites(self) -> bool:
        return bool(self.sections or self.rules or self.paragraphs)


class Module:
    def __init__(self, name: str, path: Path) -> None:
        self.name = name
        self.path = path
        self.doc: Optional[str] = None
        self.examples = False
        self.declarations: List[Declaration] = []
        self.module_citation: Optional[Declaration] = None


class Form:
    """One alternative of a §2 production: ``| p . f  -- field projection``."""

    def __init__(self, nonterminal: str, text: str, comment: str) -> None:
        self.nonterminal = nonterminal
        self.text = text
        self.comment = comment

    @property
    def key(self) -> Tuple[str, str]:
        return (self.nonterminal, self.text)


class Calculus:
    def __init__(self) -> None:
        # (number, title, level) in document order.
        self.sections: List[Tuple[str, str, int]] = []
        # label -> section number, first occurrence wins.
        self.rules: Dict[str, str] = {}
        self.rule_order: List[str] = []
        # §2's T/p/e alternatives, in document order.
        self.forms: List[Form] = []


# --- Lean parsing -----------------------------------------------------------


def _strip_doc(text: str) -> str:
    return text.strip()


def parse_lean(path: Path, lean_dir: Path) -> Module:
    """Parse one Lean file into its declarations and their doc-comments.

    A line-based reader that understands what it must and nothing more:
    block comments nest (`/- … /- … -/ … -/`), `/-! … -/` is the module
    docstring, `/-- … -/` is the doc-comment of the next declaration or
    constructor, a declaration keyword (after any modifiers or `@[attr]`) at
    column 0 opens a declaration, `| name` lines under an `inductive` are its
    constructors until the next column-0 line, `namespace`/`section`/`mutual`
    open blocks that `end` closes (only namespaces qualify names), and a
    column-0 line ending in `in` (`set_option … in`, `open … in`) belongs to
    the declaration after it.
    """
    relative = path.relative_to(lean_dir).with_suffix("")
    module = Module(".".join(relative.parts), path)
    frames: List[Tuple[str, Optional[str]]] = []  # ("ns", name) | ("block", None)
    pending_doc: Optional[str] = None
    comment_kind: Optional[str] = None  # "module" | "doc" | "block"
    comment_depth = 0
    comment_lines: List[str] = []
    current_inductive: Optional[Declaration] = None

    def close_comment(text: str) -> None:
        nonlocal pending_doc
        comment_lines.append(text)
        body = _strip_doc("\n".join(comment_lines))
        if comment_kind == "module":
            module.doc = body if module.doc is None else module.doc + "\n" + body
        elif comment_kind == "doc":
            pending_doc = body
        comment_lines.clear()

    for number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        rest = raw.rstrip("\n")
        indented = bool(rest) and rest[0].isspace()
        while True:
            pending_doc_ref = [pending_doc]
            current_inductive_ref = [current_inductive]
            if comment_kind is not None:
                i = 0
                closed_at = -1
                while i < len(rest):
                    if rest.startswith("/-", i):
                        comment_depth += 1
                        i += 2
                    elif rest.startswith("-/", i):
                        comment_depth -= 1
                        i += 2
                        if comment_depth == 0:
                            closed_at = i
                            break
                    else:
                        i += 1
                if closed_at < 0:
                    comment_lines.append(rest)
                    break
                close_comment(rest[: closed_at - 2])
                comment_kind = None
                rest = rest[closed_at:]
                continue

            stripped = rest.strip()
            if not stripped:
                break
            line_comment = rest.find("--")
            block_comment = rest.find("/-")
            if line_comment >= 0 and (block_comment < 0 or line_comment < block_comment):
                rest = rest[:line_comment]
                stripped = rest.strip()
                if not stripped:
                    break
                block_comment = -1
            if block_comment >= 0:
                code = rest[:block_comment]
                opener = rest[block_comment:]
                if opener.startswith("/-!"):
                    comment_kind, skip = "module", 3
                elif opener.startswith("/--"):
                    comment_kind, skip = "doc", 3
                else:
                    comment_kind, skip = "block", 2
                comment_depth = 1
                if code.strip():
                    _process_code(module, code, indented, number, frames, current_inductive_ref, pending_doc_ref)
                    pending_doc = pending_doc_ref[0]
                    current_inductive = current_inductive_ref[0]
                rest = opener[skip:]
                continue

            _process_code(module, rest, indented, number, frames, current_inductive_ref, pending_doc_ref)
            pending_doc = pending_doc_ref[0]
            current_inductive = current_inductive_ref[0]
            break

    if module.doc is not None:
        module.examples = EXAMPLES_MARKER in module.doc
        module.module_citation = Declaration(module.name, f"{path.name} (module)", "module", 1, module.doc)
    return module


def _process_code(
    module: Module,
    code: str,
    indented: bool,
    number: int,
    frames: List[Tuple[str, Optional[str]]],
    current_inductive_ref: List[Optional[Declaration]],
    pending_doc_ref: List[Optional[str]],
) -> None:
    """Handle one comment-free fragment of a source line."""
    current_inductive = current_inductive_ref[0]
    pending_doc = pending_doc_ref[0]
    if indented:
        ctor = CONSTRUCTOR_LINE.match(code)
        if current_inductive is not None and ctor is not None:
            module.declarations.append(
                Declaration(
                    module.name,
                    f"{current_inductive.name}.{ctor.group('name')}",
                    "constructor",
                    number,
                    pending_doc,
                )
            )
            pending_doc_ref[0] = None
        elif ctor is None:
            # A doc-comment on an indented non-constructor line (a structure
            # field, say) attaches to nothing we index.
            pending_doc_ref[0] = None
        return

    # Column 0: whatever the line is, it closes an open inductive. A fragment
    # after a same-line comment (`/-- doc -/ def x …`) keeps its column-0
    # standing, so leading space inside the fragment is not indentation.
    current_inductive_ref[0] = None
    code = code.lstrip()
    # `@[simp] theorem …` or an attribute line of its own: the attribute is
    # not the declaration, and a doc-comment above it belongs to the
    # declaration that follows.
    code = ATTRIBUTE_PREFIX.sub("", code)
    stripped = code.strip()
    if not stripped:
        return
    if CONTINUATION_LINE.match(stripped):
        return
    ns = NAMESPACE_LINE.match(code)
    if ns is not None:
        frames.append(("ns", ns.group("name")))
        pending_doc_ref[0] = None
        return
    if BLOCK_LINE.match(code):
        frames.append(("block", None))
        pending_doc_ref[0] = None
        return
    if END_LINE.match(code):
        if frames:
            frames.pop()
        pending_doc_ref[0] = None
        return
    decl_match = DECL_LINE.match(code)
    if decl_match is None:
        # `instance`, `example`, `#eval`, `open`, `import`, `deriving`, ...
        pending_doc_ref[0] = None
        return
    kind = decl_match.group("kw")
    name = decl_match.group("name")
    prefix = ".".join(frame_name for frame_kind, frame_name in frames if frame_kind == "ns" and frame_name)
    qualified = f"{prefix}.{name}" if prefix else name
    decl = Declaration(module.name, qualified, kind, number, pending_doc)
    pending_doc_ref[0] = None
    module.declarations.append(decl)
    if kind in ("inductive", "structure"):
        current_inductive_ref[0] = decl


def cite(decl: Declaration, calculus: Calculus) -> None:
    """Extract the citations of one declaration's doc-comment."""
    if decl.doc is None:
        return
    decl.helper = HELPER_MARKER in decl.doc
    seen_sections: List[str] = []
    for match in SECTION_CITATION.finditer(decl.doc):
        if match.group(1) not in seen_sections:
            seen_sections.append(match.group(1))
    decl.sections = seen_sections
    paragraphs: List[str] = []
    for match in PARAGRAPH_CITATION.finditer(decl.doc):
        ref = f"{match.group(1)}:{match.group(2)}"
        if ref not in paragraphs:
            paragraphs.append(ref)
    decl.paragraphs = paragraphs
    for match in PAREN_LABEL.finditer(decl.doc):
        label = match.group(1)
        if label in calculus.rules:
            if label not in decl.rules:
                decl.rules.append(label)
        elif RULE_SHAPED.match(label) and label not in decl.unknown_rules:
            decl.unknown_rules.append(label)


# --- Calculus parsing -------------------------------------------------------


def parse_calculus(path: Path) -> Calculus:
    """The calculus's section headings and its labeled inference rules.

    A rule is labeled where its horizontal bar ends: ``─── (Use-Copy)``.
    Only §5 and §6 rules are inventoried; the other sections contribute
    headings so a citation of them has a row to land in.
    """
    calculus = Calculus()
    current = ""
    production: Optional[str] = None
    for line in path.read_text(encoding="utf-8").splitlines():
        heading = CALCULUS_HEADING.match(line)
        if heading is not None:
            number = heading.group("number")
            calculus.sections.append((number, heading.group("title"), len(heading.group("hashes"))))
            current = number
            production = None
            continue
        top = current.split(".")[0] if current else ""
        if top == SYNTAX_SECTION:
            production = _read_syntax_line(calculus, line, production)
            continue
        if top not in ("5", "6"):
            continue
        for match in CALCULUS_RULE.finditer(line):
            label = match.group("label")
            if label not in calculus.rules:
                calculus.rules[label] = current
                calculus.rule_order.append(label)
    return calculus


def _read_syntax_line(calculus: Calculus, line: str, production: Optional[str]) -> Optional[str]:
    """Read one line of §2's grammar block, returning the open production.

    A production stays open across its ``|`` alternatives and across the
    comment-only continuation lines that wrap a long ``--`` gloss; a blank
    line or an unindented line closes it.
    """
    opener = SYNTAX_PRODUCTION.match(line)
    if opener is not None:
        production = opener.group("nt")
        text = opener.group("alt")
    else:
        alternative = SYNTAX_ALTERNATIVE.match(line)
        if alternative is None or production is None:
            if not line.strip() or not line.startswith(" "):
                return None
            return production
        text = alternative.group("alt")
    if production in SYNTAX_NONTERMINALS:
        head, _, comment = text.partition("--")
        calculus.forms.append(Form(production, head.strip(), comment.strip()))
    return production


# --- Rendering --------------------------------------------------------------


def _section_key(number: str) -> Tuple[int, ...]:
    return tuple(int(part) for part in number.split("."))


def _paragraph_key(ref: str) -> Tuple[int, ...]:
    chapter, paragraph = ref.split(":")
    return _section_key(chapter) + (int(paragraph),)


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def _are(count: int) -> str:
    return "is" if count == 1 else "are"


def render_index(modules: List[Module], calculus: Calculus) -> str:
    """The whole INDEX.md."""
    lines: List[str] = []
    out = lines.append
    out("# RueCore cross-reference index")
    out("")
    out(GENERATED_MARKER)
    out("")
    out(
        "Every declaration of the mechanization with the calculus rules, sections, "
        "and prose-specification paragraphs its doc-comment cites, and the inverses: "
        "every alternative of the calculus's §2 grammar, every labeled rule and every "
        "section of its §5 and §6, with the declarations that mechanize them. A row "
        "reading *not yet mechanized* is the fragment boundary, stated rather than "
        "inferred. Sections, rules, and syntactic forms are those of "
        "`../01-core-calculus.md`; paragraphs are `docs/spec` paragraph IDs. "
        "Regenerate with `scripts/validate-lean-xref-index.py --write`; the gate "
        "fails when this file is stale or a declaration lacks its citation "
        "(`GUIDE.md` and `README.md` say what to write)."
    )
    out("")

    # Table A: declarations.
    out("## Declarations → calculus")
    out("")
    out("| Module | Declaration | Kind | Calculus | Paragraphs |")
    out("| --- | --- | --- | --- | --- |")
    helpers: List[Tuple[str, List[str]]] = []
    for module in modules:
        rows = list(module.declarations)
        if module.module_citation is not None:
            rows.insert(0, module.module_citation)
        module_helpers: List[str] = []
        for decl in rows:
            if decl.helper and not decl.cites:
                module_helpers.append(decl.name)
                continue
            if not decl.cites:
                continue
            calculus_cell = ", ".join(
                [f"({rule})" for rule in decl.rules]
                + [f"§{section}" for section in sorted(decl.sections, key=_section_key)]
            )
            paragraph_cell = ", ".join(f"`{ref}`" for ref in decl.paragraphs) or "—"
            name = decl.name if decl.kind == "module" else f"`{decl.name}`"
            out(
                f"| `{module.name}` | {_cell(name)} | {decl.kind} | "
                f"{_cell(calculus_cell) or '—'} | {_cell(paragraph_cell)} |"
            )
        if module_helpers:
            helpers.append((module.name, module_helpers))
    out("")
    if helpers:
        out("Helpers, cited by nothing in the calculus and marked `(helper)`:")
        out("")
        for module_name, names in helpers:
            out(f"- `{module_name}`: " + ", ".join(f"`{name}`" for name in names))
        out("")

    # Inverse maps.
    by_rule: Dict[str, List[str]] = {label: [] for label in calculus.rule_order}
    by_section: Dict[str, List[str]] = {number: [] for number, _, _ in calculus.sections}
    by_paragraph: Dict[str, List[str]] = {}
    for module in modules:
        rows = list(module.declarations)
        if module.module_citation is not None:
            rows.insert(0, module.module_citation)
        for decl in rows:
            display = decl.name if decl.kind == "module" else f"`{decl.name}`"
            for rule in decl.rules:
                by_rule.setdefault(rule, []).append(display)
            for section in decl.sections:
                by_section.setdefault(section, []).append(display)
            for ref in decl.paragraphs:
                by_paragraph.setdefault(ref, []).append(display)

    out("## Abstract syntax forms → declarations")
    out("")
    out(
        "Every alternative of the calculus's §2 grammar for types (`T`), places "
        "(`p`), and expressions (`e`), with the `Syntax.lean` constructors that "
        "mechanize it. *partial* marks a restricted or abstract version of the "
        "form itself and says in the same row what is missing, so no row reads as "
        "more coverage than there is. A form the fragment abstracts away rather "
        "than models reads *not yet mechanized* even where a construct of the core "
        "stands in for part of its ownership shape; the row names the stand-in. "
        "With the rules table below, this is the whole fragment boundary."
    )
    out("")
    statuses = [SYNTAX_FORMS[form.key][0] for form in calculus.forms if form.key in SYNTAX_FORMS]
    with_image = sum(1 for status in statuses if status in ("yes", "partial"))
    partial = sum(1 for status in statuses if status == "partial")
    out(
        f"Coverage: {with_image} of {len(calculus.forms)} §2 forms have a core image "
        f"({partial} of them partial); {len(calculus.forms) - with_image} "
        f"{_are(len(calculus.forms) - with_image)} *not yet mechanized*."
    )
    out("")
    out("| Production | Form | Mechanized by | Scope |")
    out("| --- | --- | --- | --- |")
    for form in calculus.forms:
        status, constructors, note = SYNTAX_FORMS.get(form.key, ("no", [], ""))
        if constructors and status in ("yes", "partial"):
            cell = ", ".join(f"`{ROOT_NAMESPACE}.{name}`" for name in constructors)
            if status == "partial":
                cell += " *(partial)*"
        else:
            cell = "*not yet mechanized*"
        out(
            f"| `{form.nonterminal}` | `{_cell(form.text)}` | {_cell(cell)} | "
            f"{_cell(note) or '—'} |"
        )
    out("")

    out("## Calculus rules → declarations")
    out("")
    out("Every labeled inference rule of §5 and §6, in the calculus's order.")
    out("")
    mechanized_rules = sum(1 for label in calculus.rule_order if by_rule.get(label))
    out(
        f"Coverage: {mechanized_rules} of {len(calculus.rule_order)} labeled §5/§6 rules are "
        f"mechanized; {len(calculus.rule_order) - mechanized_rules} "
        f"{_are(len(calculus.rule_order) - mechanized_rules)} *not yet mechanized*."
    )
    out("")
    out("| Section | Rule | Mechanized by |")
    out("| --- | --- | --- |")
    for label in calculus.rule_order:
        who = by_rule.get(label, [])
        out(f"| §{calculus.rules[label]} | `({label})` | {', '.join(who) if who else '*not yet mechanized*'} |")
    out("")

    out("## Calculus sections → declarations")
    out("")
    out(
        "Every heading of the calculus. A citation of a section counts for that "
        "section only, not for its parent or its subsections. Being cited is weaker "
        "than being mechanized: an example or a module docstring may cite a section "
        "no rule of which is mechanized, so the rules table above is the authority "
        "on coverage."
    )
    out("")
    out("| Section | Title | Cited by |")
    out("| --- | --- | --- |")
    for number, title, _ in calculus.sections:
        who = by_section.get(number, [])
        top = number.split(".")[0]
        empty = "*not cited*" if top in ("5", "6") else "—"
        out(f"| §{number} | {_cell(title)} | {', '.join(who) if who else empty} |")
    stray = sorted(
        (number for number in by_section if number not in {n for n, _, _ in calculus.sections}),
        key=_section_key,
    )
    if stray:
        out("")
        out("Cited sections the calculus has no heading for:")
        out("")
        for number in stray:
            out(f"- §{number}: {', '.join(by_section[number])}")
    out("")

    out("## Prose paragraphs → declarations")
    out("")
    out("| Paragraph | Cited by |")
    out("| --- | --- |")
    for ref in sorted(by_paragraph, key=_paragraph_key):
        out(f"| `{ref}` | {', '.join(by_paragraph[ref])} |")
    out("")
    return "\n".join(lines)


# --- The gate ---------------------------------------------------------------


def check_syntax_forms(calculus: Calculus, modules: List[Module]) -> List[str]:
    """Hold ``SYNTAX_FORMS`` against the calculus and the Lean sources.

    A new or renamed §2 alternative has no row and is an error, a row for an
    alternative the calculus no longer writes is an error, and a row naming a
    constructor the sources no longer declare is an error — so the fragment
    boundary this table states cannot quietly stop being true.
    """
    errors: List[str] = []
    if not calculus.forms:
        errors.append("found no §2 alternatives for `T`, `p`, or `e`; did the grammar block move?")
        return errors
    declared = {declaration.name for module in modules for declaration in module.declarations}
    seen = set()
    for form in calculus.forms:
        if form.key in seen:
            errors.append(
                f"§2 lists `{form.text}` twice under `{form.nonterminal} ::=`; "
                f"SYNTAX_FORMS is keyed by the alternative's text"
            )
        seen.add(form.key)
        if form.key not in SYNTAX_FORMS:
            errors.append(
                f"§2 alternative `{form.nonterminal} ::= {form.text}` has no SYNTAX_FORMS row; "
                f"add one saying which constructor mechanizes it, or that it is not yet mechanized"
            )
    for (nonterminal, text), (_, constructors, _) in sorted(SYNTAX_FORMS.items()):
        if (nonterminal, text) not in seen:
            errors.append(
                f"SYNTAX_FORMS has a row for `{nonterminal} ::= {text}`, which §2 no longer writes"
            )
        for name in constructors:
            qualified = f"{ROOT_NAMESPACE}.{name}"
            if qualified not in declared:
                errors.append(
                    f"SYNTAX_FORMS maps `{nonterminal} ::= {text}` to `{qualified}`, "
                    f"which the Lean sources do not declare"
                )
    return errors


def collect(lean_dir: Path, calculus_path: Path) -> Tuple[List[Module], Calculus, List[str]]:
    calculus = parse_calculus(calculus_path)
    errors: List[str] = []
    if not calculus.rule_order:
        errors.append(f"{calculus_path}: found no labeled §5/§6 rules; is this the calculus?")
    modules: List[Module] = []
    source_root = lean_dir / "RueCore"
    paths = sorted(source_root.rglob("*.lean")) if source_root.is_dir() else []
    if not paths:
        errors.append(f"{source_root}: no Lean sources found")
    for path in paths:
        module = parse_lean(path, lean_dir)
        rows = list(module.declarations)
        if module.module_citation is not None:
            rows.insert(0, module.module_citation)
        for decl in rows:
            cite(decl, calculus)
            where = f"{path.relative_to(lean_dir)}:{decl.line}"
            for label in decl.unknown_rules:
                errors.append(f"{where}: `{decl.name}` cites `({label})`, which is not a rule the calculus labels")
            if module.examples or decl.kind in ("module", "constructor"):
                continue
            if decl.doc is None:
                errors.append(
                    f"{where}: `{decl.name}` has no doc-comment; cite the calculus rule, section, "
                    f"or paragraph it mechanizes, or say `(helper)`"
                )
            elif not decl.cites and not decl.helper:
                errors.append(
                    f"{where}: `{decl.name}` cites nothing; add a `§`, `(Rule)`, or `X.Y:Z` "
                    f"citation, or say `(helper)`"
                )
        modules.append(module)
    errors.extend(check_syntax_forms(calculus, modules))
    return modules, calculus, errors


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--lean-dir", type=Path, default=DEFAULT_LEAN_DIR, help="the Lake package directory")
    parser.add_argument("--calculus", type=Path, default=DEFAULT_CALCULUS, help="docs/formal/01-core-calculus.md")
    parser.add_argument("--write", action="store_true", help="regenerate INDEX.md instead of checking it")
    args = parser.parse_args(argv)
    index_path = args.lean_dir / INDEX_NAME

    def validate() -> Iterable[str]:
        modules, calculus, errors = collect(args.lean_dir, args.calculus)
        if errors:
            return errors
        expected = render_index(modules, calculus)
        if args.write:
            index_path.write_text(expected, encoding="utf-8")
            return []
        if not index_path.exists():
            return [f"{index_path} is missing; run scripts/validate-lean-xref-index.py --write"]
        if index_path.read_text(encoding="utf-8") != expected:
            return [f"{index_path} is stale; run scripts/validate-lean-xref-index.py --write"]
        return []

    return run_gate(
        validate,
        summary=f"Lean cross-reference index {'written' if args.write else 'current'}: {index_path}",
        failure_heading="Lean cross-reference index problems:",
    )


if __name__ == "__main__":
    sys.exit(main())
