#!/usr/bin/env python3
"""Assert the CLI test shards in BUCK are exactly mirrored by the CI matrix.

RUE-1116 splits //:cli-tests into CLI_TEST_SHARD_COUNT parallel shard targets
(//:cli-tests-shard-0 .. //:cli-tests-shard-{N-1}) that CI runs on separate
`platform-corpus` jobs. Nothing else re-runs those slices on CI, so a shard that
exists in BUCK but is missing from the matrix silently drops that fraction of
the corpus — exactly the RUE-924 false-green failure mode. This gate fails the
build when BUCK and the workflow disagree.

The set of platforms that must run the CLI corpus is derived from the existing
`*-cli-caldera` jobs (every platform that runs Caldera also runs the ordinary
CLI corpus), so no platform list is hardcoded here.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_BUCK = ROOT / "BUCK"
DEFAULT_WORKFLOW = ROOT / ".github" / "workflows" / "ci.yml"

SHARD_COUNT_RE = re.compile(r"^\s*CLI_TEST_SHARD_COUNT\s*=\s*(\d+)\s*$", re.MULTILINE)
# Shard targets may be written either as literal names or generated by a loop
# over range(CLI_TEST_SHARD_COUNT); support both.
BUCK_SHARD_RE = re.compile(r'name\s*=\s*"cli-tests-shard-(\d+)"')
BUCK_SHARD_LOOP_RE = re.compile(r'name\s*=\s*"cli-tests-shard-\{\}"\.format\(')
BUCK_SHARD_RANGE_RE = re.compile(r"range\(\s*CLI_TEST_SHARD_COUNT\s*\)")
# platform-corpus jobs are identified by their check_name, e.g.
#   check_name: linux-arm64-cli-shard-2
#   check_name: macos-cli-caldera
# The non-greedy platform group stops at the "-cli-shard"/"-cli-caldera" suffix.
CHECK_SHARD_RE = re.compile(r"([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*?)-cli-shard-(\d+)\b")
CHECK_CALDERA_RE = re.compile(r"([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*?)-cli-caldera\b")


def shard_count(buck_text: str) -> int | None:
    match = SHARD_COUNT_RE.search(buck_text)
    return int(match.group(1)) if match else None


def validate(buck_path: Path, workflow_path: Path) -> list[str]:
    errors: list[str] = []
    buck_text = buck_path.read_text()
    workflow_text = workflow_path.read_text()

    count = shard_count(buck_text)
    if count is None:
        return [f"{buck_path}: CLI_TEST_SHARD_COUNT is not defined"]
    if count < 1:
        return [f"{buck_path}: CLI_TEST_SHARD_COUNT must be >= 1, got {count}"]

    expected = set(range(count))

    # 1. BUCK defines shard targets 0..count-1. Literal names are checked
    #    exactly; a `range(CLI_TEST_SHARD_COUNT)` generator is exhaustive by
    #    construction and only needs to be present.
    buck_shards = sorted(int(n) for n in BUCK_SHARD_RE.findall(buck_text))
    if buck_shards:
        if set(buck_shards) != expected or len(buck_shards) != count:
            errors.append(
                f"{buck_path}: cli-tests-shard targets are {buck_shards}, expected "
                f"exactly 0..{count - 1} (CLI_TEST_SHARD_COUNT={count})"
            )
    elif not (BUCK_SHARD_LOOP_RE.search(buck_text) and BUCK_SHARD_RANGE_RE.search(buck_text)):
        errors.append(
            f"{buck_path}: found no cli-tests-shard targets — neither literal "
            '"cli-tests-shard-<n>" names nor a "cli-tests-shard-{}".format(...) '
            "generator over range(CLI_TEST_SHARD_COUNT)"
        )

    # 2. Every platform that runs the CLI corpus (i.e. has a *-cli-caldera job)
    #    must list all shards 0..count-1, and no others.
    platforms = sorted(set(CHECK_CALDERA_RE.findall(workflow_text)))
    if not platforms:
        errors.append(
            f"{workflow_path}: no *-cli-caldera platform-corpus jobs found; "
            "cannot determine which platforms must run the CLI shards"
        )

    by_platform: dict[str, set[int]] = {}
    for platform, shard in CHECK_SHARD_RE.findall(workflow_text):
        by_platform.setdefault(platform, set()).add(int(shard))

    for platform in platforms:
        got = by_platform.get(platform, set())
        if got != expected:
            detail = []
            missing = sorted(expected - got)
            extra = sorted(got - expected)
            if missing:
                detail.append(f"missing shards {missing}")
            if extra:
                detail.append(f"unexpected shards {extra}")
            errors.append(
                f"{workflow_path}: platform {platform!r} cli shards = {sorted(got)}, "
                f"expected 0..{count - 1} ({'; '.join(detail)})"
            )

    # 3. No shard jobs for a platform that does not run the CLI corpus.
    for platform in sorted(set(by_platform) - set(platforms)):
        errors.append(
            f"{workflow_path}: platform {platform!r} has cli-shard jobs but no "
            "*-cli-caldera job — shard/platform sets are inconsistent"
        )

    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--buck", type=Path, default=DEFAULT_BUCK)
    parser.add_argument("--workflow", type=Path, default=DEFAULT_WORKFLOW)
    args = parser.parse_args()

    errors = validate(args.buck, args.workflow)
    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        return 1

    count = shard_count(args.buck.read_text())
    print(f"CLI shard coverage valid: {count} shard(s) mirrored on every CLI platform")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
