#!/usr/bin/env python3
"""Hold BUCK's `lean-ruecore` trust list to the theorems the package declares.

`root//:lean-ruecore` prints `#print axioms` for each name in its
`lean_package(trust = [...])` list, and fails when one of them is not a
constant. The target is deliberately not a test target (RUE-2241), so no CI
lane builds it, and a renamed theorem once left it broken on trunk for four
days (RUE-2525). This gate runs where CI does, and fails when:

* a listed name is not a theorem the Lean sources under `RueCore/` declare
  (read from the sources, which CI checks out, not from `TRUST.md`, which is
  regenerated by hand and could be as stale as the list), or is missing from
  `TRUST.md`, whose table is then stale;
* a spine theorem (`RueCore/Spec.lean`'s `spine`) is missing from the list,
  since the list exists to report what the claim rests on; or
* a name is listed twice.

Both parsers are textual: comments are stripped first, and a line of the
`spine` list or the trust list that is not an entry is an error, so a format
change fails loudly rather than shrinking what is checked.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_BUCK = ROOT / "BUCK"
DEFAULT_LEAN_DIR = ROOT / "docs" / "formal" / "lean"

PACKAGE = "lean-ruecore"
NAMESPACE = "RueCore."

# A `TRUST.md` row: | `name` | `Module` | axioms |
TRUST_ROW = re.compile(r"^\|\s*`(?P<name>[^`]+)`\s*\|\s*`RueCore[^`]*`\s*\|", re.M)
# One `spine` entry: (`RueCore.name, ``name_stmt),
SPINE_ENTRY = re.compile(r"^\(`(?P<name>RueCore\.[\w.']+)\s*,\s*``[\w.']+\s*\),?$")
# One trust-list entry: "RueCore.name",
TRUST_ENTRY = re.compile(r'^"(?P<name>[^"]+)",?$')
# Lean declarations and the scopes that qualify them.
LEAN_DECL = re.compile(
    r"^(?:@\[[^\]]*\]\s*)?(?:(?:private|protected|noncomputable|nonrec)\s+)*"
    r"(?:theorem|lemma)\s+(?P<name>[\w.']+)"
)
LEAN_OPEN = re.compile(r"^(?P<kind>namespace|section)\b\s*(?P<name>[\w.']*)")
LEAN_MUTUAL = re.compile(r"^mutual\b")
LEAN_END = re.compile(r"^end\b")


def strip_lean_comments(text: str) -> str:
    """Drop `--` line comments and nested `/- … -/` blocks, keeping line breaks and strings."""
    out: list[str] = []
    i, n, depth, in_string = 0, len(text), 0, False
    while i < n:
        if depth == 0 and not in_string and text.startswith("--", i):
            j = text.find("\n", i)
            i = n if j < 0 else j
            continue
        if not in_string and text.startswith("/-", i):
            depth += 1
            i += 2
            continue
        if depth and text.startswith("-/", i):
            depth -= 1
            i += 2
            continue
        if depth:
            if text[i] == "\n":
                out.append("\n")
            i += 1
            continue
        if in_string and text[i] == "\\":
            out.append(text[i : i + 2])
            i += 2
            continue
        if text[i] == '"':
            in_string = not in_string
        out.append(text[i])
        i += 1
    return "".join(out)


def strip_starlark_comments(text: str) -> str:
    """Drop `#` comments outside string literals."""
    lines = []
    for line in text.split("\n"):
        in_string, cut = False, len(line)
        for i, ch in enumerate(line):
            if ch == '"':
                in_string = not in_string
            elif ch == "#" and not in_string:
                cut = i
                break
        lines.append(line[:cut])
    return "\n".join(lines)


def bracketed(text: str, start: int) -> str:
    """The text between the `[` at `start` and its matching `]`, outside strings."""
    depth, in_string = 0, False
    for i in range(start, len(text)):
        ch = text[i]
        if ch == '"':
            in_string = not in_string
        elif in_string:
            continue
        elif ch == "[":
            depth += 1
        elif ch == "]":
            depth -= 1
            if depth == 0:
                return text[start + 1 : i]
    raise ValueError("unclosed `[`")


def trust_list(buck: Path) -> list[str]:
    text = strip_starlark_comments(buck.read_text())
    for call in re.finditer(r"^lean_package\(\n(?P<body>.*?)^\)", text, re.M | re.S):
        body = call.group("body")
        if not re.search(rf'^\s*name\s*=\s*"{re.escape(PACKAGE)}"\s*,', body, re.M):
            continue
        match = re.search(r"^\s*trust\s*=\s*\[", body, re.M)
        if match is None:
            raise ValueError(f"{buck}: `{PACKAGE}` has no `trust = [...]` list")
        names = []
        for item in re.split(r"\n", bracketed(body, match.end() - 1)):
            for part in filter(None, (p.strip() for p in re.split(r'(?<=",)', item.strip()))):
                entry = TRUST_ENTRY.match(part)
                if entry is None:
                    raise ValueError(f"{buck}: `{PACKAGE}`'s trust list has an entry it cannot read: {part!r}")
                names.append(entry.group("name"))
        return names
    raise ValueError(f'{buck}: no `lean_package(name = "{PACKAGE}", ...)` call')


def source_theorems(source_root: Path) -> set[str]:
    """Every `theorem`/`lemma` the Lean sources declare, fully qualified."""
    names: set[str] = set()
    for path in sorted(source_root.rglob("*.lean")):
        scopes: list[tuple[str, str]] = []
        for raw in strip_lean_comments(path.read_text()).split("\n"):
            line = raw.strip()
            if (opened := LEAN_OPEN.match(line)) is not None:
                scopes.append((opened.group("kind"), opened.group("name")))
            elif LEAN_MUTUAL.match(line):
                scopes.append(("mutual", ""))
            elif LEAN_END.match(line):
                if scopes:
                    scopes.pop()
            elif (decl := LEAN_DECL.match(line)) is not None:
                name = decl.group("name")
                if name.startswith("_root_."):
                    names.add(name[len("_root_.") :])
                    continue
                prefix = [part for kind, n in scopes if kind == "namespace" and n for part in n.split(".")]
                names.add(".".join(prefix + [name]))
    if not names:
        raise ValueError(f"{source_root}: found no theorem declarations")
    return names


def report_theorems(trust_md: Path) -> set[str]:
    names = {NAMESPACE + m.group("name") for m in TRUST_ROW.finditer(trust_md.read_text())}
    if not names:
        raise ValueError(f"{trust_md}: found no theorem rows; is this the generated trust report?")
    return names


def spine_theorems(spec: Path) -> list[str]:
    text = strip_lean_comments(spec.read_text())
    match = re.search(r"^def spine\b[^\n]*\[\s*\n(?P<body>.*?)^\]", text, re.M | re.S)
    if match is None:
        raise ValueError(f"{spec}: no `def spine … := [` list")
    names = []
    for line in match.group("body").split("\n"):
        line = line.strip()
        if not line:
            continue
        entry = SPINE_ENTRY.match(line)
        if entry is None:
            raise ValueError(f"{spec}: `spine` has a line this gate cannot read: {line!r}")
        names.append(entry.group("name"))
    if not names:
        raise ValueError(f"{spec}: `spine` names no theorem")
    return names


def check(buck: Path, lean_dir: Path) -> tuple[list[str], list[str]]:
    """The trust list, and the problems with it."""
    try:
        listed = trust_list(buck)
        declared = source_theorems(lean_dir / "RueCore")
        reported = report_theorems(lean_dir / "TRUST.md")
        spine = spine_theorems(lean_dir / "RueCore" / "Spec.lean")
    except (OSError, ValueError) as error:
        return [], [str(error)]
    problems: list[str] = []
    seen: set[str] = set()
    for name in listed:
        if name in seen:
            problems.append(f"{buck}: `{PACKAGE}`'s trust list names `{name}` twice")
        seen.add(name)
        if name not in declared:
            problems.append(
                f"{buck}: `{PACKAGE}`'s trust list names `{name}`, which no Lean source under "
                f"RueCore/ declares as a theorem; was it renamed or removed?"
            )
        elif name not in reported:
            problems.append(
                f"{lean_dir / 'TRUST.md'}: `{name}` is declared but missing from the trust report; "
                f"regenerate it (`lake exe ruecore-digest --trust`)"
            )
    for name in spine:
        if name not in seen:
            problems.append(
                f"{buck}: spine theorem `{name}` (RueCore/Spec.lean) is missing from "
                f"`{PACKAGE}`'s trust list"
            )
    return listed, problems


def errors(buck: Path, lean_dir: Path) -> list[str]:
    return check(buck, lean_dir)[1]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--buck", type=Path, default=DEFAULT_BUCK, help="the root BUCK file")
    parser.add_argument("--lean-dir", type=Path, default=DEFAULT_LEAN_DIR, help="the Lake package directory")
    args = parser.parse_args(argv)
    listed, problems = check(args.buck, args.lean_dir)
    for problem in problems:
        print(f"error: {problem}", file=sys.stderr)
    if not problems:
        print(f"Lean trust list current: {len(listed)} names, every one declared, every spine theorem listed")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
