load("//crates:defs.bzl", "rue_crate")

rue_crate(
    name = "rue-air",
    deps = [
        "//crates/rue-builtins:rue-builtins",
        "//crates/rue-error:rue-error",
        "//crates/rue-lexer:rue-lexer",
        "//crates/rue-parser:rue-parser",
        "//crates/rue-rir:rue-rir",
        "//crates/rue-runtime-abi:rue-runtime-abi",
        "//crates/rue-span:rue-span",
        "//crates/rue-target:rue-target",
        "//third-party:lasso",
        "//third-party:rayon",
    ],
)
