//! Exact model-gap inventory for the `rue-cli-tests` corpus.

use super::{InventoryScope, ModelGapAudit, ModelGapRegistration};
use rue_oracle::{
    ExternalDependencyKind, ImplementationDefinedKind, ModelGapKind, SemanticGapKind,
    UnsupportedIntrinsicKind, UnsupportedRuntimeCallKind,
};
use std::fmt;

/// Stable CLI corpus identity. File paths are deliberately excluded: cases
/// may move without resetting debt, while section/case renames must update it.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub(crate) struct CaseId {
    section: String,
    case: String,
}

impl CaseId {
    pub(crate) fn new(section: impl Into<String>, case: impl Into<String>) -> Self {
        Self {
            section: section.into(),
            case: case.into(),
        }
    }
}

impl fmt::Display for CaseId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{} :: {}", self.section, self.case)
    }
}

struct Entry {
    section: &'static str,
    case: &'static str,
    kind: ModelGapKind,
    only_on: &'static [&'static str],
}

impl Entry {
    const fn new(
        section: &'static str,
        case: &'static str,
        kind: ModelGapKind,
        only_on: &'static [&'static str],
    ) -> Self {
        Self {
            section,
            case,
            kind,
            only_on,
        }
    }

    fn registration(&self) -> ModelGapRegistration<CaseId> {
        ModelGapRegistration::new(
            CaseId::new(self.section, self.case),
            self.kind,
            self.only_on.iter().copied(),
        )
    }
}

/// The complete accepted CLI oracle-debt inventory.
///
/// Entries are generated from unknown-gap diagnostics emitted by the real
/// production classifier, then reviewed into this typed list. Dynamic
/// `Unsupported::detail` text is intentionally absent from the policy key.
///
/// Clusters marked `slot-model-default` cover corpus cases that pin the current
/// default eight-byte slot layout (byte offsets, per-slot sizes, aggregate
/// widths). The gap *reasons* here are layout-independent (they are unmodeled
/// raw-pointer / `@field_ptr` intrinsics), but the cases' expected values move
/// when the ratified compact layout (ADR-0052, `aggregate_layout`) becomes the
/// default, so the stabilization sweep (RUE-987) greps `slot-model-default` to
/// enumerate every ledger entry it must re-verify after the flip.
const ENTRIES: &[Entry] = &[
    Entry::new(
        "array_literal_string",
        "array_of_string_new_len",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "array_literal_string",
        "array_of_string_var_single",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "array_literal_string",
        "array_of_string_with_capacity",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "cli.abi",
        "string_return_by_value",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.abi",
        "string_return_with_args",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    // slot-model-default: the aggregate ABI matrix pins per-slot byte layout.
    Entry::new(
        "cli.aggregate_abi_matrix",
        "aos_ptr_rw",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    Entry::new(
        "cli.aggregate_abi_matrix",
        "arr_ptr_rw",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    Entry::new(
        "cli.aggregate_abi_matrix",
        "enum_ptr_rw",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    Entry::new(
        "cli.aggregate_abi_matrix",
        "nest_ptr_rw",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    Entry::new(
        "cli.aggregate_abi_matrix",
        "s1_ptr_rw",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    Entry::new(
        "cli.aggregate_abi_matrix",
        "s2_ptr_rw",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    Entry::new(
        "cli.aggregate_abi_matrix",
        "s3_ptr_rw",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    Entry::new(
        "cli.aggregate_abi_matrix",
        "s8_ptr_rw",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    // slot-model-default: ascending-layout cases assert "slot k at base + k*8".
    Entry::new(
        "cli.aggregate_ascending_layout",
        "heap_multislot_roundtrip_no_clobber",
        intrinsic(UnsupportedIntrinsicKind::Allocate),
        &[],
    ),
    Entry::new(
        "cli.aggregate_ascending_layout",
        "stack_raw_ptr_roundtrip",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    // slot-model-default: aggregate_slots pins per-slot 8-byte field layout.
    Entry::new(
        "cli.aggregate_slots",
        "dbg_string_from_field",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "cli.aggregate_slots",
        "store_string_from_field",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "cli.aggregate_slots",
        "string_array_pass_by_value",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.anon_struct_destructor",
        "generic_heap_buffer_auto_freed",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.arraybuf_library",
        "arraybuf_clear_set_free_drop_accounting",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.arraybuf_library",
        "arraybuf_drop_trace_ascending",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.arraybuf_library",
        "arraybuf_nested_drop_trace",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.arraybuf_library",
        "arraybuf_nested_i64_drain",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.arraybuf_library",
        "arraybuf_strbuf_elements",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.arraybuf_library",
        "arraybuf_zero_sized_element",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.borrow_sibling_moves",
        "byref_method_receiver_stays_usable_control",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "cli.builtin_assocfn_infer",
        "string_new_len_eq_literal",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.builtin_assocfn_infer",
        "string_new_result_is_empty",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.builtin_assocfn_infer",
        "with_capacity_literal_arg_is_u64",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "cli.builtin_method_infer",
        "capacity_compare_literal_compiles",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "cli.byref_params",
        "inout_forwarding_still_works",
        semantic(SemanticGapKind::InoutParameterForwarding),
        &[],
    ),
    Entry::new(
        "cli.byref_params",
        "inout_whole_string_reassign",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "cli.comptime_type_var_composite",
        "pointer_to_comptime_type_var",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.const_alias_inference",
        "intcast_infers_target_from_method_param",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.const_alias_inference",
        "negative_literal_arg_through_const_alias",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.const_init",
        "string_const_prints_and_measures",
        runtime_call(UnsupportedRuntimeCallKind::Println),
        &[],
    ),
    Entry::new(
        "cli.differential_opt",
        "fixed_string_inout_forwarding_and_projected_lvalues_across_opt_levels",
        semantic(SemanticGapKind::InoutParameterForwarding),
        &[],
    ),
    Entry::new(
        "cli.differential_opt",
        "raw_pointer_place_operands_across_opt_levels",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.differential_opt",
        "param_raw_mut_write_reread_across_opt_levels",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    Entry::new(
        "cli.divergence",
        "break_mid_block_no_double_drop",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "cli.divergence",
        "return_mid_block_in_untaken_branch",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "cli.drop_moves",
        "branch_divergent_string_field_move_no_double_free",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "cli.drop_moves",
        "partial_string_field_move_no_double_free",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "cli.field_type_inference",
        "string_field_method_receiver_anchors_literal",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.for_loops",
        "for_chars_invalid_utf8_traps",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.for_loops",
        "for_chars_lossy_replaces_raw_invalid_bytes",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.for_loops",
        "for_chars_lossy_valid_dbg",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.for_loops",
        "for_chars_scalars_dbg",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.for_loops",
        "for_string_bytes_dbg",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    // std.fs File IO v0 (RUE-712, ADR-0057): pure-Rue fs over @syscall. The
    // oracle model cannot execute the raw-pointer/syscall substrate (StrBuf/
    // ArrayBuf `@int_to_ptr` prologue, `@alloc_bytes`, `@syscall`), so every
    // case is accepted debt, exactly like the arraybuf/strbuf CLI cases. The
    // two error-detection cases run `only_on` Linux (macOS carry-flag gap,
    // ADR-0057 §3a), so their gap registration is Linux-scoped to match.
    Entry::new(
        "cli.fs_file_io",
        "fs_roundtrip",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.fs_file_io",
        "fs_append",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.fs_file_io",
        "fs_drop_close_reopen",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.fs_file_io",
        "fs_close_then_reopen_safe",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.fs_file_io",
        "fs_read_full_buffer_invalid",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.fs_file_io",
        "fs_read_whole_file_loop",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.fs_file_io",
        "fs_reserve_then_read_fills",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.fs_file_io",
        "fs_open_missing_not_found",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.fs_file_io",
        "fs_write_to_readonly",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.heap_intrinsics",
        "alloc_count_size_overflow_traps",
        intrinsic(UnsupportedIntrinsicKind::Allocate),
        &[],
    ),
    Entry::new(
        "cli.heap_intrinsics",
        "alloc_page_rounding_overflow_returns_null",
        intrinsic(UnsupportedIntrinsicKind::Allocate),
        &[],
    ),
    Entry::new(
        "cli.heap_intrinsics",
        "alloc_write_read_free",
        intrinsic(UnsupportedIntrinsicKind::Allocate),
        &[],
    ),
    Entry::new(
        "cli.heap_intrinsics",
        "free_from_destructor",
        intrinsic(UnsupportedIntrinsicKind::Allocate),
        &[],
    ),
    Entry::new(
        "cli.heap_intrinsics",
        "realloc_count_size_overflow_traps",
        intrinsic(UnsupportedIntrinsicKind::Allocate),
        &[],
    ),
    Entry::new(
        "cli.heap_intrinsics",
        "realloc_failure_preserves_original",
        intrinsic(UnsupportedIntrinsicKind::Allocate),
        &[],
    ),
    Entry::new(
        "cli.heap_intrinsics",
        "realloc_grows_and_preserves",
        intrinsic(UnsupportedIntrinsicKind::Allocate),
        &[],
    ),
    Entry::new(
        "cli.ice_regressions",
        "array_literal_string_element_rue96",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.ice_regressions",
        "array_literal_string_exprs_rue190",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.ice_regressions",
        "string_param_rebound_to_local_rue63",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.ice_regressions",
        "struct_field_string_eq_rue94",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.method_receiver_byref_places",
        "inout_self_through_inout_param",
        semantic(SemanticGapKind::InoutParameterForwarding),
        &[],
    ),
    // slot-model-default: offset_of_field_ptr pins @offset_of byte values
    // (0/8/16/24) and their @field_ptr agreement.
    Entry::new(
        "cli.offset_of_field_ptr",
        "field_ptr_on_param_struct",
        intrinsic(UnsupportedIntrinsicKind::FieldPointer),
        &[],
    ),
    Entry::new(
        "cli.offset_of_field_ptr",
        "field_ptr_read_roundtrip",
        intrinsic(UnsupportedIntrinsicKind::FieldPointer),
        &[],
    ),
    Entry::new(
        "cli.offset_of_field_ptr",
        "field_ptr_write_updates_field",
        intrinsic(UnsupportedIntrinsicKind::FieldPointer),
        &[],
    ),
    Entry::new(
        "cli.offset_of_field_ptr",
        "offset_of_ptr_offset_agrees_with_field_ptr",
        intrinsic(UnsupportedIntrinsicKind::FieldPointer),
        &[],
    ),
    // ADR-0052 phase 3 (RUE-974): the compact-layout CLI cases reach a field
    // through `@field_ptr`, which the oracle model does not model (same gap as
    // the `offset_of_field_ptr` cases above).
    // slot-model-default: aggregate_layout contrasts the default slot layout
    // with the compact preview, so its expected values track the flip.
    Entry::new(
        "cli.aggregate_layout",
        "compact_slot_identical_field_ptr_roundtrip",
        intrinsic(UnsupportedIntrinsicKind::FieldPointer),
        &[],
    ),
    Entry::new(
        "cli.aggregate_layout",
        "narrow_program_unchanged_without_the_preview",
        intrinsic(UnsupportedIntrinsicKind::FieldPointer),
        &[],
    ),
    // ADR-0052 phase 5.5 (RUE-989): the narrow-access execution cases reach
    // memory through `@field_ptr` and `@alloc`, both outside the oracle model
    // (same gaps as the entries above and the heap_intrinsics corpus).
    Entry::new(
        "cli.aggregate_layout",
        "compact_struct_field_narrow_roundtrip",
        intrinsic(UnsupportedIntrinsicKind::FieldPointer),
        &[],
    ),
    Entry::new(
        "cli.aggregate_layout",
        "mixed_struct_field_roundtrip",
        intrinsic(UnsupportedIntrinsicKind::FieldPointer),
        &[],
    ),
    Entry::new(
        "cli.aggregate_layout",
        "narrow_heap_array_walk",
        intrinsic(UnsupportedIntrinsicKind::Allocate),
        &[],
    ),
    Entry::new(
        "cli.aggregate_layout",
        "narrow_heap_roundtrip_scalars",
        intrinsic(UnsupportedIntrinsicKind::Allocate),
        &[],
    ),
    // ADR-0052 phase 5.6 (RUE-1000): the compact-enum heap round-trips reach
    // memory through `@alloc`, outside the oracle model (same gap as the narrow
    // heap cases above).
    Entry::new(
        "cli.aggregate_layout",
        "compact_enum_option_heap_roundtrip",
        intrinsic(UnsupportedIntrinsicKind::Allocate),
        &[],
    ),
    Entry::new(
        "cli.aggregate_layout",
        "compact_enum_mixed_payload_widths",
        intrinsic(UnsupportedIntrinsicKind::Allocate),
        &[],
    ),
    Entry::new(
        "cli.aggregate_layout",
        "compact_enum_uniform_multifield_heap",
        intrinsic(UnsupportedIntrinsicKind::Allocate),
        &[],
    ),
    Entry::new(
        "cli.partial_move_depth",
        "disjoint_sibling_after_subfield_move_ok",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.partial_move_depth",
        "disjoint_sibling_element_move_ok",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.pointers",
        "array_index_and_ptr_offset_agree",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.pointers",
        "ptr_across_function",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.pointers",
        "ptr_int_roundtrip",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.pointers",
        "ptr_offset_forward_is_higher_address",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.pointers",
        "ptr_offset_forward_on_mmap_pointer",
        external(ExternalDependencyKind::SystemCall),
        &["x86-64-linux"],
    ),
    Entry::new(
        "cli.pointers",
        "ptr_offset_negative_walks_backward",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.pointers",
        "ptr_offset_reads_offset_element",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.pointers",
        "ptr_offset_write_hits_offset_element",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    Entry::new(
        "cli.pointers",
        "ptr_read_roundtrip",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.pointers",
        "ptr_write_literal_infers_i64_pointee",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    Entry::new(
        "cli.pointers",
        "ptr_write_literal_infers_u8_pointee",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    Entry::new(
        "cli.pointers",
        "ptr_write_mutates_local",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    Entry::new(
        "cli.pointers",
        "raw_mut_of_parameter_mutates_it",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    Entry::new(
        "cli.pointers",
        "raw_of_local_still_works",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.pointers",
        "raw_of_param_struct_field",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.pointers",
        "raw_of_parameter_takes_address",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.print",
        "print_borrows_string_reusable_after_call",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.print",
        "print_empty_and_println_empty",
        runtime_call(UnsupportedRuntimeCallKind::Print),
        &[],
    ),
    Entry::new(
        "cli.print",
        "print_no_trailing_newline",
        runtime_call(UnsupportedRuntimeCallKind::Print),
        &[],
    ),
    Entry::new(
        "cli.print",
        "print_utf8_bytes_verbatim",
        runtime_call(UnsupportedRuntimeCallKind::Println),
        &[],
    ),
    Entry::new(
        "cli.print",
        "println_adds_single_newline",
        runtime_call(UnsupportedRuntimeCallKind::Println),
        &[],
    ),
    Entry::new(
        "cli.print",
        "println_composed_with_to_string_and_concat",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.programs",
        "dbg_string_then_use",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.programs",
        "string_builder_push_str",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.ptr_read_write_aggregate",
        "ptr_read_result_type_match_i32",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.ptr_read_write_aggregate",
        "ptr_read_two_field_struct",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.ptr_read_write_aggregate",
        "ptr_read_write_nested_struct",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.ptr_read_write_aggregate",
        "ptr_read_write_scalar",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    Entry::new(
        "cli.ptr_read_write_aggregate",
        "ptr_write_two_field_struct",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    Entry::new(
        "cli.raw_ptr_and_method_name",
        "raw_mut_ptr_does_not_suppress_destructor",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    Entry::new(
        "cli.raw_ptr_and_method_name",
        "raw_ptr_does_not_suppress_destructor",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.raw_ptr_and_method_name",
        "raw_ptr_operand_usable_after",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.raw_ptr_and_method_name",
        "raw_ptr_then_move_operand_single_drop",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.raw_ptr_and_method_name",
        "string_push_str_on_mut_ok",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.reexport_qualified_ctor",
        "std_chain_alias_types_wide_payload_literal",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.reserved_names",
        "builtin_method_name_allowed",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.slices",
        "method_and_assoc_forward_slice_view",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.slices",
        "method_and_assoc_slice_view_coercions",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.slices",
        "slice_param_constant_index",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.slices",
        "slice_param_empty_array_len_zero",
        intrinsic(UnsupportedIntrinsicKind::EmptySlicePointer),
        &[],
    ),
    Entry::new(
        "cli.slices",
        "slice_param_forwarding",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.slices",
        "slice_param_index_out_of_bounds_traps",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.slices",
        "slice_param_len",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.slices",
        "slice_param_negative_signed_index_traps",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.slices",
        "slice_param_sum_len_index",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.slices",
        "slice_param_u8_element",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "cli.std_bitset",
        "bitset_set_test_count_clear_toggle",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.std_collections",
        "std_collections_m2_smoke",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.std_core",
        "std_core_m1_smoke",
        // `std.mem.swap` now performs a bytewise exchange through `@raw_mut`
        // (RUE-943), so the oracle model's first unsupported intrinsic for this
        // case is the address-of rather than the later `@int_to_ptr`.
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    Entry::new(
        "cli.std_deque",
        "deque_both_ends_grow_drain",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    // std.env (RUE-935): argv/envp are captured process state, so the oracle
    // treats the `@arg_*`/`@env_*` reads as external dependencies (like
    // `@random_*`). Each case's first such read decides its registered kind.
    Entry::new(
        "cli.std_env",
        "arg_count_includes_argv0_and_passed_args",
        external(ExternalDependencyKind::ArgCount),
        &[],
    ),
    Entry::new(
        "cli.std_env",
        "arg_out_of_range_is_none",
        external(ExternalDependencyKind::ArgCount),
        &[],
    ),
    Entry::new(
        "cli.std_env",
        "args_are_echoed_in_order",
        external(ExternalDependencyKind::ArgCount),
        &[],
    ),
    Entry::new(
        "cli.std_env",
        "argv0_is_present",
        external(ExternalDependencyKind::ArgCount),
        &[],
    ),
    Entry::new(
        "cli.std_env",
        "var_absent_returns_none",
        external(ExternalDependencyKind::EnvCount),
        &[],
    ),
    Entry::new(
        "cli.std_env",
        "var_present_returns_value",
        external(ExternalDependencyKind::EnvCount),
        &[],
    ),
    Entry::new(
        "cli.std_exit",
        "std_exit_terminates_with_status",
        external(ExternalDependencyKind::SystemCall),
        &[],
    ),
    Entry::new(
        "cli.std_internal_raw_bytes",
        "ordinary_std_import_needs_no_raw_bytes_preview",
        external(ExternalDependencyKind::SystemCall),
        &[],
    ),
    Entry::new(
        "cli.std_byte_bridges",
        "all_three_representations_round_trip_without_consuming_sources",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "cli.std_byte_bridges",
        "byte_range_bridges_reject_out_of_bounds_ranges",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.std_byte_bridges",
        "empty_bridges_and_spare_capacity_are_preserved",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.std_m3",
        "std_rand_m3",
        semantic(SemanticGapKind::InoutParameterForwarding),
        &[],
    ),
    Entry::new(
        "cli.std_m3",
        "std_sort_m3",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.std_m3",
        "std_strbuf_chars_share_core_decoder",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.std_m3",
        "std_strbuf_chars_strict_invalid_utf8_traps",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.std_m3",
        "std_strbuf_compiler_cutover",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.std_m3",
        "std_strbuf_formatting_and_text_consumers",
        runtime_call(UnsupportedRuntimeCallKind::Print),
        &[],
    ),
    Entry::new(
        "cli.std_m3",
        "std_strings_count_chars_strict_invalid_utf8_traps",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.std_m3",
        "std_strings_m3",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.std_net_tcp",
        "tcp_connection_refused",
        external(ExternalDependencyKind::SystemCall),
        &["aarch64-linux", "x86-64-linux"],
    ),
    Entry::new(
        "cli.std_net_tcp",
        "tcp_loopback_round_trip",
        external(ExternalDependencyKind::SystemCall),
        &["aarch64-linux", "x86-64-linux"],
    ),
    Entry::new(
        "cli.std_strbuf",
        "aliased_three_word_layout_and_scope_drop",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.std_strbuf",
        "canonical_identity_drives_string_semantics",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.std_strbuf",
        "generic_inout_accepts_literal_initialized_strbuf",
        semantic(SemanticGapKind::InoutParameterForwarding),
        &[],
    ),
    Entry::new(
        "cli.std_strbuf",
        "mem_swap_exchanges_move_only_strbufs",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.std_strbuf",
        "owned_allocation_drop_and_early_free",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "cli.std_strbuf",
        "qualified_nonallocating_surface",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.std_strbuf",
        "source_allocation_failure_fails_fast",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "cli.std_strbuf",
        "source_byte_range_out_of_bounds",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.std_strbuf",
        "source_capacity_overflow_fails_fast",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.std_strbuf",
        "source_literal_promotion_self_append_and_adjacent_bytes",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.std_strbuf",
        "source_owned_algorithms_use_packed_bytes",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "cli.std_strbuf",
        "source_zero_capacity_empty_ranges_and_early_free",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.std_strmap",
        "std_strmap_smoke",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.str_fixed_type",
        "str_fixed_exact_borrow_is_by_reference",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.str_fixed_type",
        "str_fixed_exact_inout_is_by_reference",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.str_fixed_type",
        "str_fixed_len_and_first_byte",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.str_fixed_type",
        "str_fixed_len_independent_of_capacity",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.str_fixed_type",
        "str_fixed_packed_byte_indexing",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.str_fixed_type",
        "str_fixed_param_roundtrip",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.str_type",
        "str_preserves_explicit_strbuf_literal_context",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.str_type",
        "strbuf_field_borrow_str_view",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.str_type",
        "strbuf_read_through_borrow_str_view_values",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.strbuf_library",
        "strbuf_new_push_str_len_print",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.strbuf_library",
        "strbuf_with_capacity_concat",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "cli.string_alloc_failure",
        "arraybuf_growth_overflow_traps",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.string_alloc_failure",
        "arraybuf_with_capacity_huge_traps",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.string_alloc_failure",
        "arraybuf_zero_capacity_does_not_allocate",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.string_alloc_failure",
        "grid_capacity_overflow_traps",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.string_alloc_failure",
        "strbuf_with_capacity_huge_traps",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "cli.string_alloc_failure",
        "strbuf_zero_capacity_does_not_allocate",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.string_alloc_failure",
        "with_capacity_normal_reserves",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "cli.string_byte_access",
        "borrow_rooted_strbuf_byte_reads",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.string_byte_access",
        "substring_byte_range",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.string_byte_access",
        "substring_out_of_range_traps",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.string_byte_access",
        "substring_result_is_mutable",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.string_growth",
        "growth_does_not_corrupt_neighbor",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "cli.string_growth",
        "interleaved_repeated_growth_stress",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.string_mutation_receivers",
        "array_element_const_index_push",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.string_mutation_receivers",
        "array_element_dynamic_index_push",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.string_mutation_receivers",
        "field_receiver_push_str",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.string_mutation_receivers",
        "inout_param_receiver_push_str",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.string_mutation_receivers",
        "self_field_receiver_via_method",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.string_mutation_value_position",
        "statement_position_mutation_still_runs",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.string_phase1",
        "concat_chained_and_mutable_result",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.string_phase1",
        "concat_is_concatenation_not_addition",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.string_phase1",
        "contains_and_starts_with",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.string_phase1",
        "to_string_all_integer_widths",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.string_phase1",
        "to_string_demo",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "cli.string_phase1",
        "to_string_i32_no_cast_needed",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.try_operator",
        "try_string_payload",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.try_operator",
        "try_unwrap_and_short_circuit",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.unit_fields",
        "std_option_and_arraybuf_accept_unit",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.wildcard_payload_binding",
        "discarded_non_copy_payload_drops_once",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "cli.zst_drop_glue",
        "enum_payload_fields_keep_drop_offsets",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.zst_drop_glue",
        "nested_struct_array_keeps_drop_offsets_and_stride",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "cli.zst_drop_glue",
        "struct_fields_keep_drop_offsets",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "string_field",
        "string_field_rebound_then_eq",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "string_field",
        "string_param_rebound_to_local",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "string_field",
        "string_struct_field_eq_false",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "string_field",
        "string_struct_field_eq_true",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "string_field",
        "struct_with_string_field_eq",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
];

pub(crate) fn audit(scope: InventoryScope) -> ModelGapAudit<CaseId> {
    ModelGapAudit::new(
        "rue-cli-tests",
        scope,
        ENTRIES.iter().map(Entry::registration),
        render_registration,
    )
}

fn render_registration(identity: &CaseId, kind: ModelGapKind, only_on: &[String]) -> String {
    let only_on = if only_on.is_empty() {
        "&[]".to_string()
    } else {
        format!(
            "&[{}]",
            only_on
                .iter()
                .map(|platform| format!("{platform:?}"))
                .collect::<Vec<_>>()
                .join(", ")
        )
    };
    format!(
        "        Entry::new({:?}, {:?}, {}, {}),",
        identity.section,
        identity.case,
        render_kind(kind),
        only_on
    )
}

fn render_kind(kind: ModelGapKind) -> String {
    match kind {
        ModelGapKind::Semantic(SemanticGapKind::Intrinsic(kind)) => {
            format!("intrinsic(UnsupportedIntrinsicKind::{kind:?})")
        }
        ModelGapKind::Semantic(SemanticGapKind::RuntimeCall(kind)) => {
            format!("runtime_call(UnsupportedRuntimeCallKind::{kind:?})")
        }
        ModelGapKind::Semantic(SemanticGapKind::FlattenedParameterSlot) => {
            "semantic(SemanticGapKind::FlattenedParameterSlot)".to_string()
        }
        ModelGapKind::Semantic(SemanticGapKind::TextProjectionRead) => {
            "semantic(SemanticGapKind::TextProjectionRead)".to_string()
        }
        ModelGapKind::Semantic(SemanticGapKind::InoutParameterForwarding) => {
            "semantic(SemanticGapKind::InoutParameterForwarding)".to_string()
        }
        ModelGapKind::ExternalDependency(kind) => {
            format!("external(ExternalDependencyKind::{kind:?})")
        }
        ModelGapKind::ImplementationDefined(kind) => {
            format!("implementation_defined(ImplementationDefinedKind::{kind:?})")
        }
    }
}

const fn intrinsic(kind: UnsupportedIntrinsicKind) -> ModelGapKind {
    ModelGapKind::Semantic(SemanticGapKind::Intrinsic(kind))
}

const fn runtime_call(kind: UnsupportedRuntimeCallKind) -> ModelGapKind {
    ModelGapKind::Semantic(SemanticGapKind::RuntimeCall(kind))
}

const fn semantic(kind: SemanticGapKind) -> ModelGapKind {
    ModelGapKind::Semantic(kind)
}

const fn external(kind: ExternalDependencyKind) -> ModelGapKind {
    ModelGapKind::ExternalDependency(kind)
}

const fn implementation_defined(kind: ImplementationDefinedKind) -> ModelGapKind {
    ModelGapKind::ImplementationDefined(kind)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rendered_unknown_entry_is_directly_pasteable_registry_syntax() {
        assert_eq!(
            render_registration(
                &CaseId::new("cli.example", "random"),
                external(ExternalDependencyKind::RandomU32),
                &["x86-64-linux".to_string()],
            ),
            concat!(
                "        Entry::new(\"cli.example\", \"random\", ",
                "external(ExternalDependencyKind::RandomU32), &[\"x86-64-linux\"]),"
            )
        );
    }

    #[test]
    fn registry_identity_is_section_and_expanded_case_name() {
        assert_eq!(
            CaseId::new("cli.example", "case[expanded]").to_string(),
            "cli.example :: case[expanded]"
        );
    }
}
