//! Exact model-gap inventory for the expanded `rue-spec` corpus.

use super::{InventoryScope, ModelGapAudit, ModelGapRegistration};
use rue_oracle::{
    ExternalDependencyKind, ImplementationDefinedKind, ModelGapKind, SemanticGapKind,
    UnsupportedIntrinsicKind, UnsupportedRuntimeCallKind,
};
use std::fmt;

/// Stable spec-corpus identity. The case name is the post-template-expansion
/// name returned by `rue-test-runner`; file paths are deliberately excluded.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub(crate) struct CaseId {
    section: String,
    case: String,
}

impl CaseId {
    pub(crate) fn new(section: impl Into<String>, case: impl Into<String>) -> Self {
        Self {
            section: section.into(),
            case: case.into(),
        }
    }
}

impl fmt::Display for CaseId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{} :: {}", self.section, self.case)
    }
}

struct Entry {
    section: &'static str,
    case: &'static str,
    kind: ModelGapKind,
    only_on: &'static [&'static str],
}

impl Entry {
    const fn new(
        section: &'static str,
        case: &'static str,
        kind: ModelGapKind,
        only_on: &'static [&'static str],
    ) -> Self {
        Self {
            section,
            case,
            kind,
            only_on,
        }
    }

    fn registration(&self) -> ModelGapRegistration<CaseId> {
        ModelGapRegistration::new(
            CaseId::new(self.section, self.case),
            self.kind,
            self.only_on.iter().copied(),
        )
    }
}

/// The complete accepted spec oracle-debt inventory across every supported
/// host. Entries are generated from production typed diagnostics and reviewed
/// against the authoritative, post-template-expansion corpus.
const ENTRIES: &[Entry] = &[
    // Source-defined StrBuf methods expose their first unmodeled ordinary
    // projection, allocation, pointer, or inout operation to the oracle.
    Entry::new(
        "expressions.for",
        "for_chars_lossy_valid",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "expressions.for",
        "for_chars_scalars",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "expressions.for",
        "for_string_borrows_not_consumes",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "expressions.for",
        "for_string_bytes_count",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "expressions.for",
        "for_string_bytes_multibyte",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "dbg_string_borrows_not_consumed",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "dbg_string_dropped_exactly_once",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "items.general",
        "fn_builtin_method_name_allowed",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "types.destructors",
        "codegen_nontrivial_drop_call",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "types.destructors",
        "struct_with_destructor_field",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "types.destructors",
        "struct_with_string_fields_dropped",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "types.destructors",
        "type_with_destructor",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "types.destructors",
        "type_with_destructor_literal_no_heap",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "types.destructors",
        "type_with_destructor_literal_promoted",
        semantic(SemanticGapKind::InoutParameterForwarding),
        &[],
    ),
    Entry::new(
        "types.move-semantics",
        "borrow_method_receiver_still_usable_after",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_affine_move",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_building_message",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_byte_at_empty_none",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_byte_at_in_bounds",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_byte_at_last_byte_boundary",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_byte_at_loop_sum",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_byte_at_out_of_bounds_none",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_byte_semantics",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_clone_basic",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_clone_borrow",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_clone_independent",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_destructor_heap",
        semantic(SemanticGapKind::InoutParameterForwarding),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_destructor_literal",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_equality_after_mutation",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_is_empty_false",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_is_empty_true",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_len_empty",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_len_literal",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_new_empty",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_push_byte",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_push_str_basic",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_push_str_multiple",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_query_borrows_borrow_and_inout_rooted_places",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.str_type",
        "str_literal_explicit_strbuf_context",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_new_basic",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_new_equality_with_empty",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_new_is_empty",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_type_annotation",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_type_annotation_empty",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_with_capacity_basic",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_with_capacity_equality_with_empty",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "types.strings",
        "to_string_i32_default_literal",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "types.strings",
        "to_string_i64_extremes",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "types.strings",
        "to_string_negative_and_zero",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "types.strings",
        "to_string_positive",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "types.strings",
        "to_string_signed_widths",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "types.strings",
        "to_string_unsigned_widths_high_bit",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "expressions.comparison",
        "struct_raw_pointer_field_equality_by_address",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "expressions.for",
        "for_chars_invalid_utf8_traps",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "expressions.for",
        "for_chars_lossy_replaces_invalid",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "parse_empty_string_yields_none",
        intrinsic(UnsupportedIntrinsicKind::ParseI32),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "parse_i32_basic",
        intrinsic(UnsupportedIntrinsicKind::ParseI32),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "parse_i32_boundary",
        intrinsic(UnsupportedIntrinsicKind::ParseI32),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "parse_i32_leading_zeros",
        intrinsic(UnsupportedIntrinsicKind::ParseI32),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "parse_i32_max",
        intrinsic(UnsupportedIntrinsicKind::ParseI32),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "parse_i32_min",
        intrinsic(UnsupportedIntrinsicKind::ParseI32),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "parse_i32_negative",
        intrinsic(UnsupportedIntrinsicKind::ParseI32),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "parse_i32_string_not_consumed",
        intrinsic(UnsupportedIntrinsicKind::ParseI32),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "parse_i32_zero",
        intrinsic(UnsupportedIntrinsicKind::ParseI32),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "parse_i64_basic",
        intrinsic(UnsupportedIntrinsicKind::ParseI64),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "parse_i64_negative",
        intrinsic(UnsupportedIntrinsicKind::ParseI64),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "parse_invalid_char_yields_none",
        intrinsic(UnsupportedIntrinsicKind::ParseI32),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "parse_negative_unsigned_yields_none",
        intrinsic(UnsupportedIntrinsicKind::ParseU32),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "parse_overflow_i32_yields_none",
        intrinsic(UnsupportedIntrinsicKind::ParseI32),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "parse_overflow_u32_yields_none",
        intrinsic(UnsupportedIntrinsicKind::ParseU32),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "parse_u32_basic",
        intrinsic(UnsupportedIntrinsicKind::ParseU32),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "parse_u64_basic",
        intrinsic(UnsupportedIntrinsicKind::ParseU64),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "random_u32_entropy_failure_behavior",
        external(ExternalDependencyKind::RandomU32),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "random_u32_in_range_expression",
        external(ExternalDependencyKind::RandomU32),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "random_u32_multiple_calls",
        external(ExternalDependencyKind::RandomU32),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "random_u32_no_args",
        external(ExternalDependencyKind::RandomU32),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "random_u32_returns_u32",
        external(ExternalDependencyKind::RandomU32),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "random_u64_multiple_calls",
        external(ExternalDependencyKind::RandomU64),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "random_u64_no_args",
        external(ExternalDependencyKind::RandomU64),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "random_u64_returns_u64",
        external(ExternalDependencyKind::RandomU64),
        &[],
    ),
    // std.env's process-argument/environment intrinsics read captured process
    // state, an external dependency like `@random_*` (RUE-935). Each case's
    // first such read (its `@arg_count`/`@env_count`) decides the kind.
    Entry::new(
        "expressions.intrinsics",
        "arg_count_includes_argv0",
        external(ExternalDependencyKind::ArgCount),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "arg_len_and_ptr_in_and_out_of_range",
        external(ExternalDependencyKind::ArgCount),
        &[],
    ),
    Entry::new(
        "expressions.intrinsics",
        "env_len_and_ptr_out_of_range",
        external(ExternalDependencyKind::EnvCount),
        &[],
    ),
    Entry::new(
        "expressions.try",
        "try_parse_intrinsic_none_short_circuits",
        intrinsic(UnsupportedIntrinsicKind::ParseI64),
        &[],
    ),
    Entry::new(
        "expressions.try",
        "try_parse_intrinsic_some",
        intrinsic(UnsupportedIntrinsicKind::ParseI64),
        &[],
    ),
    Entry::new(
        "items.functions",
        "inout_array_forward",
        semantic(SemanticGapKind::InoutParameterForwarding),
        &[],
    ),
    Entry::new(
        "items.functions",
        "inout_forward_struct",
        semantic(SemanticGapKind::InoutParameterForwarding),
        &[],
    ),
    Entry::new(
        "items.impl-blocks",
        "method_and_assoc_string_view_coercions",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "items.unchecked",
        "ptr_ops_in_checked_ok",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    Entry::new(
        "runtime.allocation-failure",
        "strbuf_allocation_failure_traps",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "runtime.heap",
        "alloc_multiple_elements",
        intrinsic(UnsupportedIntrinsicKind::Allocate),
        &[],
    ),
    Entry::new(
        "runtime.heap",
        "alloc_then_free",
        intrinsic(UnsupportedIntrinsicKind::Allocate),
        &[],
    ),
    Entry::new(
        "runtime.heap",
        "alloc_write_read",
        intrinsic(UnsupportedIntrinsicKind::Allocate),
        &[],
    ),
    Entry::new(
        "runtime.heap",
        "realloc_failure_preserves_original",
        intrinsic(UnsupportedIntrinsicKind::Allocate),
        &[],
    ),
    Entry::new(
        "runtime.heap",
        "realloc_null_is_alloc",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "runtime.heap",
        "realloc_preserves_contents",
        intrinsic(UnsupportedIntrinsicKind::Allocate),
        &[],
    ),
    Entry::new(
        "runtime.raw_bytes",
        "alloc_bytes_result_type_is_inferred",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "runtime.raw_bytes",
        "alloc_bytes_zero_returns_null",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "runtime.raw_bytes",
        "byte_read_accepts_const_u8_pointer",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "runtime.raw_bytes",
        "byte_write_preserves_adjacent_bytes",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "runtime.raw_bytes",
        "failed_realloc_bytes_preserves_original",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "runtime.raw_bytes",
        "free_bytes_null_zero_is_permitted",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "runtime.raw_bytes",
        "packed_offsets_read_write_exactly_one_byte",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "runtime.raw_bytes",
        "raw_byte_allocation_failure_returns_null",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "runtime.raw_bytes",
        "realloc_bytes_zero_frees_and_returns_null",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "runtime.raw_bytes",
        "realloc_bytes_preserves_packed_prefix",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "runtime.pointers",
        "field_ptr_first_field",
        intrinsic(UnsupportedIntrinsicKind::FieldPointer),
        &[],
    ),
    Entry::new(
        "runtime.pointers",
        "field_ptr_read_matches_direct",
        intrinsic(UnsupportedIntrinsicKind::FieldPointer),
        &[],
    ),
    Entry::new(
        "runtime.pointers",
        "field_ptr_write_updates_field",
        intrinsic(UnsupportedIntrinsicKind::FieldPointer),
        &[],
    ),
    Entry::new(
        "runtime.pointers",
        "int_to_ptr_mutable_pointer",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "runtime.pointers",
        "int_to_ptr_u64_pointer",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "runtime.pointers",
        "int_to_ptr_with_type_annotation",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "runtime.pointers",
        "ptr_offset_add_backward",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "runtime.pointers",
        "ptr_offset_add_forward",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "runtime.pointers",
        "ptr_to_int_basic",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "runtime.pointers",
        "ptr_write_and_read",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    Entry::new(
        "runtime.pointers",
        "ptr_write_array_element",
        intrinsic(UnsupportedIntrinsicKind::RawMutableAddress),
        &[],
    ),
    Entry::new(
        "runtime.pointers",
        "raw_array_element",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "runtime.pointers",
        "raw_array_last_element",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "runtime.pointers",
        "raw_array_second_element",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "runtime.pointers",
        "raw_simple_local",
        intrinsic(UnsupportedIntrinsicKind::RawAddress),
        &[],
    ),
    Entry::new(
        "runtime.syscall",
        "syscall_basic_aarch64",
        external(ExternalDependencyKind::SystemCall),
        &["aarch64-linux"],
    ),
    Entry::new(
        "runtime.syscall",
        "syscall_basic_x86_64",
        external(ExternalDependencyKind::SystemCall),
        &["x86-64-linux"],
    ),
    Entry::new(
        "runtime.syscall",
        "syscall_checked_block_expression",
        external(ExternalDependencyKind::SystemCall),
        &["x86-64-linux"],
    ),
    Entry::new(
        "runtime.syscall",
        "syscall_checked_block_expression_aarch64",
        external(ExternalDependencyKind::SystemCall),
        &["aarch64-linux"],
    ),
    Entry::new(
        "runtime.syscall",
        "syscall_error_is_negative_aarch64_macos",
        external(ExternalDependencyKind::SystemCall),
        &["aarch64-macos"],
    ),
    Entry::new(
        "runtime.syscall",
        "syscall_max_args",
        external(ExternalDependencyKind::SystemCall),
        &["x86-64-linux"],
    ),
    Entry::new(
        "runtime.syscall",
        "syscall_returns_i64",
        external(ExternalDependencyKind::SystemCall),
        &["x86-64-linux"],
    ),
    Entry::new(
        "runtime.syscall",
        "syscall_returns_i64_aarch64",
        external(ExternalDependencyKind::SystemCall),
        &["aarch64-linux"],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_capacity_literal",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_clear",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_growth_on_append",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_heap_promotion",
        semantic(SemanticGapKind::InoutParameterForwarding),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_literal_no_capacity",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_literal_read_only",
        implementation_defined(ImplementationDefinedKind::StringCapacityValue),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_query_borrow_valid",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_representation_len_cap",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_reserve",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
    Entry::new(
        "types.mutable_strings",
        "string_with_capacity",
        intrinsic(UnsupportedIntrinsicKind::AllocateBytes),
        &[],
    ),
    Entry::new(
        "types.str_fixed_type",
        "str_fixed_exact_capacity_ok",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.str_fixed_type",
        "str_fixed_in_struct_field",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.str_fixed_type",
        "str_fixed_len_is_current_not_capacity",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.str_fixed_type",
        "str_fixed_returnable",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.str_type",
        "borrow_str_view_of_strbuf_reads_values",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.str_type",
        "inout_str_view_can_be_forwarded",
        semantic(SemanticGapKind::InoutParameterForwarding),
        &[],
    ),
    Entry::new(
        "types.strings",
        "print_borrows_argument_string",
        runtime_call(UnsupportedRuntimeCallKind::Print),
        &[],
    ),
    Entry::new(
        "types.strings",
        "print_empty_writes_nothing_println_empty_writes_newline",
        runtime_call(UnsupportedRuntimeCallKind::Print),
        &[],
    ),
    Entry::new(
        "types.strings",
        "print_writes_bytes_without_newline",
        runtime_call(UnsupportedRuntimeCallKind::Print),
        &[],
    ),
    Entry::new(
        "types.strings",
        "println_appends_single_newline",
        runtime_call(UnsupportedRuntimeCallKind::Println),
        &[],
    ),
    Entry::new(
        "types.strings",
        "println_composes_with_to_string_and_concat",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_concat_borrows_operands",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_concat_is_not_integer_add",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_concat_literals",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_contains_byte_level",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_dropped_implicitly",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_heap_freed_once",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_search_does_not_consume",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_starts_with_byte_level",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_substring_bytes",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_substring_does_not_consume",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_substring_empty",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_substring_len",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_substring_out_of_bounds_traps",
        semantic(SemanticGapKind::TextProjectionRead),
        &[],
    ),
    Entry::new(
        "types.strings",
        "string_with_capacity_zero",
        intrinsic(UnsupportedIntrinsicKind::IntToPointer),
        &[],
    ),
];

pub(crate) fn audit(scope: InventoryScope) -> ModelGapAudit<CaseId> {
    ModelGapAudit::new(
        "rue-spec",
        scope,
        ENTRIES.iter().map(Entry::registration),
        render_registration,
    )
}

fn render_registration(identity: &CaseId, kind: ModelGapKind, only_on: &[String]) -> String {
    let only_on = if only_on.is_empty() {
        "&[]".to_string()
    } else {
        format!(
            "&[{}]",
            only_on
                .iter()
                .map(|platform| format!("{platform:?}"))
                .collect::<Vec<_>>()
                .join(", ")
        )
    };
    format!(
        "        Entry::new({:?}, {:?}, {}, {}),",
        identity.section,
        identity.case,
        render_kind(kind),
        only_on
    )
}

fn render_kind(kind: ModelGapKind) -> String {
    match kind {
        ModelGapKind::Semantic(SemanticGapKind::Intrinsic(kind)) => {
            format!("intrinsic(UnsupportedIntrinsicKind::{kind:?})")
        }
        ModelGapKind::Semantic(SemanticGapKind::RuntimeCall(kind)) => {
            format!("runtime_call(UnsupportedRuntimeCallKind::{kind:?})")
        }
        ModelGapKind::Semantic(SemanticGapKind::FlattenedParameterSlot) => {
            "semantic(SemanticGapKind::FlattenedParameterSlot)".to_string()
        }
        ModelGapKind::Semantic(SemanticGapKind::TextProjectionRead) => {
            "semantic(SemanticGapKind::TextProjectionRead)".to_string()
        }
        ModelGapKind::Semantic(SemanticGapKind::InoutParameterForwarding) => {
            "semantic(SemanticGapKind::InoutParameterForwarding)".to_string()
        }
        ModelGapKind::ExternalDependency(kind) => {
            format!("external(ExternalDependencyKind::{kind:?})")
        }
        ModelGapKind::ImplementationDefined(kind) => {
            format!("implementation_defined(ImplementationDefinedKind::{kind:?})")
        }
    }
}

const fn intrinsic(kind: UnsupportedIntrinsicKind) -> ModelGapKind {
    ModelGapKind::Semantic(SemanticGapKind::Intrinsic(kind))
}

const fn runtime_call(kind: UnsupportedRuntimeCallKind) -> ModelGapKind {
    ModelGapKind::Semantic(SemanticGapKind::RuntimeCall(kind))
}

const fn semantic(kind: SemanticGapKind) -> ModelGapKind {
    ModelGapKind::Semantic(kind)
}

const fn external(kind: ExternalDependencyKind) -> ModelGapKind {
    ModelGapKind::ExternalDependency(kind)
}

const fn implementation_defined(kind: ImplementationDefinedKind) -> ModelGapKind {
    ModelGapKind::ImplementationDefined(kind)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rendered_unknown_entry_uses_expanded_spec_identity_and_exact_scope() {
        assert_eq!(
            render_registration(
                &CaseId::new("runtime.syscall", "syscall_basic_aarch64"),
                external(ExternalDependencyKind::SystemCall),
                &["aarch64-linux".to_string()],
            ),
            concat!(
                "        Entry::new(\"runtime.syscall\", \"syscall_basic_aarch64\", ",
                "external(ExternalDependencyKind::SystemCall), &[\"aarch64-linux\"]),"
            )
        );
    }

    #[test]
    fn registry_identity_is_section_and_expanded_case_name() {
        assert_eq!(
            CaseId::new("types.integers", "u8_overflow_addition").to_string(),
            "types.integers :: u8_overflow_addition"
        );
    }
}
