import RueCore.Spec

/-!
# Lean Comparator's challenge (RUE-2460)

Generated by `lake exe ruecore-digest --challenge` from `RueCore.Spec.spine`; do
not edit. One theorem per Spec statement, with the statement as its type and
`sorry` for a proof. It imports the Spec layer and, through it, layers L0 and
L1 only: the part of the package a reviewer trusts. `RueCore.Spine`, the
solution, states the same names with the same types and proves them;
`comparator/config.json` names them. How to run it: README, "The statement
layer".
-/

namespace RueCore.Spine

theorem soundness : RueCore.Spec.soundness_stmt := sorry
theorem run_safe : RueCore.Spec.run_safe_stmt := sorry
theorem no_violation : RueCore.Spec.no_violation_stmt := sorry
theorem no_use_after_move : RueCore.Spec.no_use_after_move_stmt := sorry
theorem no_use_after_drop : RueCore.Spec.no_use_after_drop_stmt := sorry
theorem no_linear_leak : RueCore.Spec.no_linear_leak_stmt := sorry
theorem no_linear_overwrite : RueCore.Spec.no_linear_overwrite_stmt := sorry
theorem no_linear_discard : RueCore.Spec.no_linear_discard_stmt := sorry
theorem fuel_mono : RueCore.Spec.fuel_mono_stmt := sorry
theorem no_masking : RueCore.Spec.no_masking_stmt := sorry
theorem run_ne_returned : RueCore.Spec.run_ne_returned_stmt := sorry
theorem check_sound : RueCore.Spec.check_sound_stmt := sorry
theorem checkProgram_sound : RueCore.Spec.checkProgram_sound_stmt := sorry
theorem no_double_free : RueCore.Spec.no_double_free_stmt := sorry
theorem freed_once : RueCore.Spec.freed_once_stmt := sorry
theorem dtor_once : RueCore.Spec.dtor_once_stmt := sorry
theorem drop_exactly_once : RueCore.Spec.drop_exactly_once_stmt := sorry
theorem rest_exactly_once : RueCore.Spec.rest_exactly_once_stmt := sorry
theorem drop_order : RueCore.Spec.drop_order_stmt := sorry
theorem Step.det : RueCore.Spec.Step.det_stmt := sorry
theorem Step.terminal : RueCore.Spec.Step.terminal_stmt := sorry
theorem Config.trichotomy : RueCore.Spec.Config.trichotomy_stmt := sorry
theorem step_iff : RueCore.Spec.step_iff_stmt := sorry
theorem Config.stuck_iff : RueCore.Spec.Config.stuck_iff_stmt := sorry
theorem step_stuck_isStuckState : RueCore.Spec.step_stuck_isStuckState_stmt := sorry
theorem step_progress : RueCore.Spec.step_progress_stmt := sorry
theorem step_preservation : RueCore.Spec.step_preservation_stmt := sorry
theorem step_type_safety : RueCore.Spec.step_type_safety_stmt := sorry
theorem eval_sound : RueCore.Spec.eval_sound_stmt := sorry
theorem run_sim : RueCore.Spec.run_sim_stmt := sorry
theorem eval_complete : RueCore.Spec.eval_complete_stmt := sorry
theorem run_complete : RueCore.Spec.run_complete_stmt := sorry
theorem never_stuck_iff : RueCore.Spec.never_stuck_iff_stmt := sorry
theorem step_never_stuck_of_run : RueCore.Spec.step_never_stuck_of_run_stmt := sorry
theorem run_stuck_of_step_stuck : RueCore.Spec.run_stuck_of_step_stuck_stmt := sorry
theorem eval_diverges_iff : RueCore.Spec.eval_diverges_iff_stmt := sorry

end RueCore.Spine
