import RueCore.Adequacy.Defs
import RueCore.Checker.Defs
import RueCore.Soundness.Defs
import RueCore.Trace.Defs

/-!
# Lean Comparator's challenge (RUE-2460)

Generated by `lake exe ruecore-digest --challenge` from `RueCore.Spec.spine`; do
not edit. It restates every Spec statement in full, as the kernel holds it (its
elaborated body, pretty-printed), over the L0 and L1 modules the Spec layer
imports and nothing else; then one theorem per statement, with the statement as
its type and `sorry` for a proof. `RueCore.Spine`, the solution, proves the same
names with the same types; Comparator checks that every constant these
statements use, each `_stmt` included, is the same in the solution's
environment, so a statement changed in the Spec layer fails Comparator until
this file is regenerated, and the change is then this file's diff.
`comparator/config.json` names the theorems. How to run it: README, "The
statement layer".
-/

set_option autoImplicit false

namespace RueCore.Spec

/-- The statement `soundness` proves. -/
def soundness_stmt : Prop :=
  ∀ (M : FloatModel) {P : Program},
    WfProgram P →
      ∀ (fuel : Nat) {R : Ty} {Γ : Ctx} {Ω : Out} {e : Expr} {T : Ty},
        Typed P R Γ e T Ω →
          ∀ {φ : Frame} {H : Store},
            FrameMatches P.decls Γ φ H →
              EvalOk P.decls T R Ω.norm Ω.brk φ H (eval M.toFloatOps fuel P H φ e)

/-- The statement `run_safe` proves. -/
def run_safe_stmt : Prop :=
  ∀ (M : FloatModel) {P : Program} {fd : FnDef},
    WfProgram P →
      P.fns[0]? = some fd →
        fd.params = [] →
          ∀ (fuel : Nat),
            run M.toFloatOps P fuel = EvalRes.outOfFuel ∨
              (∃ (k : PanicKind), ∃ (tr : List Event), run M.toFloatOps P fuel = EvalRes.panic k tr) ∨
                ∃ (H : Store),
                  ∃ (v : Val),
                    ∃ (tr : List Event),
                      run M.toFloatOps P fuel = EvalRes.ok H v tr ∧ HasTy P.decls v fd.ret

/-- The statement `no_violation` proves. -/
def no_violation_stmt : Prop :=
  ∀ (M : FloatModel) {P : Program},
    ProgramTyped P → ∀ (fuel : Nat) (w : Violation), run M.toFloatOps P fuel ≠ EvalRes.stuck w

/-- The statement `no_use_after_move` proves. -/
def no_use_after_move_stmt : Prop :=
  ∀ (M : FloatModel) {P : Program},
    ProgramTyped P → ∀ (fuel : Nat), run M.toFloatOps P fuel ≠ EvalRes.stuck Violation.useAfterMove

/-- The statement `no_use_after_drop` proves. -/
def no_use_after_drop_stmt : Prop :=
  ∀ (M : FloatModel) {P : Program},
    ProgramTyped P → ∀ (fuel : Nat), run M.toFloatOps P fuel ≠ EvalRes.stuck Violation.useAfterDrop

/-- The statement `no_linear_leak` proves. -/
def no_linear_leak_stmt : Prop :=
  ∀ (M : FloatModel) {P : Program},
    ProgramTyped P → ∀ (fuel : Nat), run M.toFloatOps P fuel ≠ EvalRes.stuck Violation.linearLeak

/-- The statement `no_linear_overwrite` proves. -/
def no_linear_overwrite_stmt : Prop :=
  ∀ (M : FloatModel) {P : Program},
    ProgramTyped P → ∀ (fuel : Nat), run M.toFloatOps P fuel ≠ EvalRes.stuck Violation.linearOverwrite

/-- The statement `no_linear_discard` proves. -/
def no_linear_discard_stmt : Prop :=
  ∀ (M : FloatModel) {P : Program},
    ProgramTyped P → ∀ (fuel : Nat), run M.toFloatOps P fuel ≠ EvalRes.stuck Violation.linearDiscard

/-- The statement `fuel_mono` proves. -/
def fuel_mono_stmt : Prop :=
  ∀ (M : FloatOps) {P : Program} {H : Store} {φ : Frame} {e : Expr} {n m : Nat},
    n ≤ m → eval M n P H φ e ≠ EvalRes.outOfFuel → eval M m P H φ e = eval M n P H φ e

/-- The statement `no_masking` proves. -/
def no_masking_stmt : Prop :=
  ∀ (M : FloatOps) {P : Program} {H : Store} {φ : Frame} {e : Expr} {n m : Nat} {w : Violation},
    eval M n P H φ e = EvalRes.stuck w →
      eval M m P H φ e ≠ EvalRes.outOfFuel → eval M m P H φ e = EvalRes.stuck w

/-- The statement `run_ne_returned` proves. -/
def run_ne_returned_stmt : Prop :=
  ∀ (M : FloatOps) {P : Program} {fuel : Nat} (H : Store) (v : Val) (tr : List Event),
    run M P fuel ≠ EvalRes.returned H v tr

/-- The statement `check_sound` proves. -/
def check_sound_stmt : Prop :=
  ∀ {P : Program} {R : Ty} (e : Expr) {Γ : Ctx} {c : CTy} {Ω : Out},
    check P R Γ e = some (c, Ω) → ∀ (T : Ty), c.fits T = true → Typed P R Γ e T Ω

/-- The statement `checkProgram_sound` proves. -/
def checkProgram_sound_stmt : Prop :=
  ∀ {P : Program}, checkProgram P = true → ProgramTyped P

/-- The statement `no_double_free` proves. -/
def no_double_free_stmt : Prop :=
  ∀ (M : FloatModel) {P : Program},
    ProgramTyped P →
      ∀ (fuel : Nat),
        (∀ (w : Violation), run M.toFloatOps P fuel ≠ EvalRes.stuck w) ∧
          (∀ (a : Nat), List.count a (freedIds P.decls (run M.toFloatOps P fuel).trace) ≤ 1) ∧
            ∀ (a : Nat), List.count a (dtorIds (run M.toFloatOps P fuel).trace) ≤ 1

/-- The statement `freed_once` proves. -/
def freed_once_stmt : Prop :=
  ∀ (M : FloatOps) (P : Program) (fuel a : Nat),
    List.count a (freedIds P.decls (run M P fuel).trace) ≤ 1

/-- The statement `dtor_once` proves. -/
def dtor_once_stmt : Prop :=
  ∀ (M : FloatOps) {P : Program},
    DtorNotCopy P.decls → ∀ (fuel a : Nat), List.count a (dtorIds (run M P fuel).trace) ≤ 1

/-- The statement `drop_exactly_once` proves. -/
def drop_exactly_once_stmt : Prop :=
  ∀ (M : FloatModel) {P : Program},
    ProgramTyped P →
      P.pendingSafe = true →
        ∀ {fuel : Nat} {R : Ty} {Γ : Ctx} {e : Expr} {T : Ty} {Ω : Out} {φ : Frame} {H : Store},
          Typed P R Γ e T Ω →
            FrameMatches P.decls Γ φ H →
              StoreCC P.decls H →
                e.pendingSafe = true →
                  (∀ (w : Violation), eval M.toFloatOps fuel P H φ e ≠ EvalRes.stuck w) ∧
                    Exact P.decls H [] (eval M.toFloatOps fuel P H φ e) ∧
                      Tidy φ H (eval M.toFloatOps fuel P H φ e)

/-- The statement `rest_exactly_once` proves. -/
def rest_exactly_once_stmt : Prop :=
  ∀ (M : FloatModel) {P : Program},
    ProgramTyped P →
      P.pendingSafe = true →
        ∀ {fuel : Nat} {R : Ty} {Γ : Ctx} {e : Expr} {T : Ty} {Ω : Out} {φ : Frame} {H : Store},
          Typed P R Γ e T Ω →
            FrameMatches P.decls Γ φ H →
              StoreCC P.decls H →
                e.pendingSafe = true →
                  ∀ {H₁ : Store} {vs : List Val} {tr : List Event},
                    Lead M.toFloatOps P fuel H φ H₁ vs tr e →
                      ∀ {r : EvalRes},
                        eval M.toFloatOps (fuel + 1) P H φ e = EvalRes.withTrace tr r →
                          (∀ (w : Violation), r ≠ EvalRes.stuck w) ∧
                            Exact P.decls H₁ (Contents.ownList P.decls (Contents.ofVals vs)) r ∧
                              Settled φ H₁ r

/-- The statement `drop_order` proves. -/
def drop_order_stmt : Prop :=
  ∀ (M : FloatModel) {P : Program},
    ProgramTyped P →
      (∀ (H : Store) (φ : Frame) (v : Val) (tr : List Event),
          Steps M.toFloatOps P Config.init (Config.run H φ [] (Focus.ret v) tr) → Blocks P.decls tr) ∧
        (∀ (κ : PanicKind) (tr : List Event),
            Steps M.toFloatOps P Config.init (Config.panic κ tr) → Blocks P.decls tr) ∧
          ∀ (C C' : Config),
            Steps M.toFloatOps P Config.init C →
              Step M.toFloatOps P C C' →
                ∃ (evs : List Event),
                  C'.trace = C.trace ++ evs ∧
                    NewestFirst (dropLocs evs) ∧
                      Lifo C.stack C'.stack (dropLocs evs) ∧
                        List.Pairwise (fun (x1 x2 : Nat) => x1 < x2) C.stack

/-- The statement `Step.det` proves. -/
def Step.det_stmt : Prop :=
  ∀ {M : FloatOps} {P : Program} {C C₁ C₂ : Config}, Step M P C C₁ → Step M P C C₂ → C₁ = C₂

/-- The statement `Step.terminal` proves. -/
def Step.terminal_stmt : Prop :=
  ∀ {M : FloatOps} {P : Program} {C C' : Config}, C.Terminal → ¬Step M P C C'

/-- The statement `Config.trichotomy` proves. -/
def Config.trichotomy_stmt : Prop :=
  ∀ (M : FloatOps) (P : Program) (C : Config),
    (∃ (C' : Config), Step M P C C') ∨ C.Terminal ∨ ∃ (w : Violation), Config.Stuck M P C w

/-- The statement `step_iff` proves. -/
def step_iff_stmt : Prop :=
  ∀ {M : FloatOps} {P : Program} {C C' : Config}, Step M P C C' ↔ step M P C = StepOut.next C'

/-- The statement `Config.stuck_iff` proves. -/
def Config.stuck_iff_stmt : Prop :=
  ∀ {M : FloatOps} {P : Program} {C : Config},
    (¬C.Terminal ∧ ∀ (C' : Config), ¬Step M P C C') ↔ ∃ (w : Violation), Config.Stuck M P C w

/-- The statement `step_stuck_isStuckState` proves. -/
def step_stuck_isStuckState_stmt : Prop :=
  ∀ {M : FloatOps} {P : Program} {C : Config} {w : Violation},
    Config.Stuck M P C w → w.isStuckState = true

/-- The statement `step_progress` proves. -/
def step_progress_stmt : Prop :=
  ∀ (M : FloatModel) {P : Program},
    ProgramTyped P →
      ∀ (C : Config),
        Steps M.toFloatOps P Config.init C → C.Terminal ∨ ∃ (C' : Config), Step M.toFloatOps P C C'

/-- The statement `step_preservation` proves. -/
def step_preservation_stmt : Prop :=
  ∀ (M : FloatModel) {P : Program},
    ProgramTyped P →
      ∃ (fd : FnDef),
        P.fns[0]? = some fd ∧
          ∀ (C : Config), Steps M.toFloatOps P Config.init C → Config.SafeAt M.toFloatOps P fd.ret C

/-- The statement `step_type_safety` proves. -/
def step_type_safety_stmt : Prop :=
  ∀ (M : FloatModel) {P : Program},
    ProgramTyped P →
      ∃ (fd : FnDef),
        P.fns[0]? = some fd ∧
          ∀ (n : Nat),
            (∃ (D : Config), StepsN M.toFloatOps P n Config.init D) ∨
              (∃ (H : Store),
                  ∃ (v : Val),
                    ∃ (tr : List Event),
                      Steps M.toFloatOps P Config.init
                          (Config.run H Frame.empty [] (Focus.ret v) tr) ∧
                        HasTy P.decls v fd.ret) ∨
                ∃ (κ : PanicKind),
                  ∃ (tr : List Event), Steps M.toFloatOps P Config.init (Config.panic κ tr)

/-- The statement `eval_sound` proves. -/
def eval_sound_stmt : Prop :=
  ∀ (M : FloatModel) {P : Program},
    ProgramTyped P →
      ∀ (fuel : Nat),
        (∀ (w : Violation), run M.toFloatOps P fuel ≠ EvalRes.stuck w) ∧
          (∀ (H : Store) (v : Val) (tr : List Event),
              run M.toFloatOps P fuel = EvalRes.ok H v tr →
                Steps M.toFloatOps P Config.init (Config.run H Frame.empty [] (Focus.ret v) tr)) ∧
            ∀ (k : PanicKind) (tr : List Event),
              run M.toFloatOps P fuel = EvalRes.panic k tr →
                Steps M.toFloatOps P Config.init (Config.panic k tr)

/-- The statement `run_sim` proves. -/
def run_sim_stmt : Prop :=
  ∀ (M : FloatOps) (P : Program) (fuel : Nat),
    (∀ (H : Store) (v : Val) (tr : List Event),
        run M P fuel = EvalRes.ok H v tr →
          Steps M P Config.init (Config.run H Frame.empty [] (Focus.ret v) tr)) ∧
      ∀ (k : PanicKind) (tr : List Event),
        run M P fuel = EvalRes.panic k tr → Steps M P Config.init (Config.panic k tr)

/-- The statement `eval_complete` proves. -/
def eval_complete_stmt : Prop :=
  ∀ (M : FloatModel) {P : Program},
    ProgramTyped P →
      (∀ (H : Store) (φ : Frame) (v : Val) (tr : List Event),
          Steps M.toFloatOps P Config.init (Config.run H φ [] (Focus.ret v) tr) →
            ∃ (n : Nat), ∀ (fuel : Nat), n < fuel → run M.toFloatOps P fuel = EvalRes.ok H v tr) ∧
        ∀ (κ : PanicKind) (tr : List Event),
          Steps M.toFloatOps P Config.init (Config.panic κ tr) →
            ∃ (n : Nat), ∀ (fuel : Nat), n < fuel → run M.toFloatOps P fuel = EvalRes.panic κ tr

/-- The statement `run_complete` proves. -/
def run_complete_stmt : Prop :=
  ∀ (M : FloatOps) (P : Program),
    (∀ (H : Store) (φ : Frame) (v : Val) (tr : List Event),
        Steps M P Config.init (Config.run H φ [] (Focus.ret v) tr) →
          ∃ (n : Nat),
            ∀ (fuel : Nat),
              n < fuel →
                run M P fuel = EvalRes.ok H v tr ∨
                  ∃ (w : Violation), run M P fuel = EvalRes.stuck w) ∧
      ∀ (κ : PanicKind) (tr : List Event),
        Steps M P Config.init (Config.panic κ tr) →
          ∃ (n : Nat),
            ∀ (fuel : Nat),
              n < fuel →
                run M P fuel = EvalRes.panic κ tr ∨ ∃ (w : Violation), run M P fuel = EvalRes.stuck w

/-- The statement `never_stuck_iff` proves. -/
def never_stuck_iff_stmt : Prop :=
  ∀ (M : FloatModel) {P : Program},
    ProgramTyped P →
      ((∀ (fuel : Nat) (w : Violation), run M.toFloatOps P fuel ≠ EvalRes.stuck w) ↔
        ∀ (C : Config),
          Steps M.toFloatOps P Config.init C → C.Terminal ∨ ∃ (C' : Config), Step M.toFloatOps P C C')

/-- The statement `step_never_stuck_of_run` proves. -/
def step_never_stuck_of_run_stmt : Prop :=
  ∀ (M : FloatOps) (P : Program),
    (∀ (fuel : Nat) (w : Violation), run M P fuel ≠ EvalRes.stuck w) →
      ∀ (C : Config), Steps M P Config.init C → C.Terminal ∨ ∃ (C' : Config), Step M P C C'

/-- The statement `run_stuck_of_step_stuck` proves. -/
def run_stuck_of_step_stuck_stmt : Prop :=
  ∀ (M : FloatOps) (P : Program) {C : Config} {w : Violation},
    Steps M P Config.init C →
      Config.Stuck M P C w →
        ∃ (n : Nat), ∀ (fuel : Nat), n < fuel → ∃ (w' : Violation), run M P fuel = EvalRes.stuck w'

/-- The statement `eval_diverges_iff` proves. -/
def eval_diverges_iff_stmt : Prop :=
  ∀ (M : FloatModel) {P : Program},
    ProgramTyped P →
      ((∀ (fuel : Nat), run M.toFloatOps P fuel = EvalRes.outOfFuel) ↔
        ∀ (n : Nat), ∃ (D : Config), StepsN M.toFloatOps P n Config.init D)

end RueCore.Spec

namespace RueCore.Spine

theorem soundness : RueCore.Spec.soundness_stmt := sorry
theorem run_safe : RueCore.Spec.run_safe_stmt := sorry
theorem no_violation : RueCore.Spec.no_violation_stmt := sorry
theorem no_use_after_move : RueCore.Spec.no_use_after_move_stmt := sorry
theorem no_use_after_drop : RueCore.Spec.no_use_after_drop_stmt := sorry
theorem no_linear_leak : RueCore.Spec.no_linear_leak_stmt := sorry
theorem no_linear_overwrite : RueCore.Spec.no_linear_overwrite_stmt := sorry
theorem no_linear_discard : RueCore.Spec.no_linear_discard_stmt := sorry
theorem fuel_mono : RueCore.Spec.fuel_mono_stmt := sorry
theorem no_masking : RueCore.Spec.no_masking_stmt := sorry
theorem run_ne_returned : RueCore.Spec.run_ne_returned_stmt := sorry
theorem check_sound : RueCore.Spec.check_sound_stmt := sorry
theorem checkProgram_sound : RueCore.Spec.checkProgram_sound_stmt := sorry
theorem no_double_free : RueCore.Spec.no_double_free_stmt := sorry
theorem freed_once : RueCore.Spec.freed_once_stmt := sorry
theorem dtor_once : RueCore.Spec.dtor_once_stmt := sorry
theorem drop_exactly_once : RueCore.Spec.drop_exactly_once_stmt := sorry
theorem rest_exactly_once : RueCore.Spec.rest_exactly_once_stmt := sorry
theorem drop_order : RueCore.Spec.drop_order_stmt := sorry
theorem Step.det : RueCore.Spec.Step.det_stmt := sorry
theorem Step.terminal : RueCore.Spec.Step.terminal_stmt := sorry
theorem Config.trichotomy : RueCore.Spec.Config.trichotomy_stmt := sorry
theorem step_iff : RueCore.Spec.step_iff_stmt := sorry
theorem Config.stuck_iff : RueCore.Spec.Config.stuck_iff_stmt := sorry
theorem step_stuck_isStuckState : RueCore.Spec.step_stuck_isStuckState_stmt := sorry
theorem step_progress : RueCore.Spec.step_progress_stmt := sorry
theorem step_preservation : RueCore.Spec.step_preservation_stmt := sorry
theorem step_type_safety : RueCore.Spec.step_type_safety_stmt := sorry
theorem eval_sound : RueCore.Spec.eval_sound_stmt := sorry
theorem run_sim : RueCore.Spec.run_sim_stmt := sorry
theorem eval_complete : RueCore.Spec.eval_complete_stmt := sorry
theorem run_complete : RueCore.Spec.run_complete_stmt := sorry
theorem never_stuck_iff : RueCore.Spec.never_stuck_iff_stmt := sorry
theorem step_never_stuck_of_run : RueCore.Spec.step_never_stuck_of_run_stmt := sorry
theorem run_stuck_of_step_stuck : RueCore.Spec.run_stuck_of_step_stuck_stmt := sorry
theorem eval_diverges_iff : RueCore.Spec.eval_diverges_iff_stmt := sorry

end RueCore.Spine
