load("@prelude//rust:cargo_package.bzl", "cargo")
load("//tools/rust:defs.bzl", "clippy_rust_library")

cargo.rust_library(
    name = "rue-diagnostic",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//crates/rue-lexer:rue-lexer",
        "//third-party/rust:thiserror",
    ],
    visibility = ["PUBLIC"],
)

# Clippy version of the library target
clippy_rust_library(
    name = "clippy",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//crates/rue-lexer:rue-lexer",
        "//third-party/rust:thiserror",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "test",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//crates/rue-lexer:rue-lexer",
        "//third-party/rust:thiserror",
    ],
)