load("@prelude//rust:cargo_package.bzl", "cargo")

cargo.rust_library(
    name = "rue-diagnostic",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//crates/rue-lexer:rue-lexer",
        "//third-party/rust:thiserror",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "test",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//crates/rue-lexer:rue-lexer",
        "//third-party/rust:thiserror",
    ],
)