//! Type-inference glue: running inference, projection analysis, and resolved-type lookups.
//!
//! This category connects the inference engine to the canonical semantic
//! analysis and records resolved expression types.

use super::super::ordinary_engine::{OrdinaryBodyAnalysisHost, OrdinaryBodyEngine};
use super::*;
use crate::inference::{FrontierParamOverlay, LazyInferenceFacts, ParamVarInfo};
use ahash::AHashMap;
use lasso::Key;
use std::collections::VecDeque;
use std::sync::Arc;
use std::time::Instant;

#[derive(Debug, Clone, Copy)]
pub(crate) struct InferenceBreakdown {
    pub(crate) precompute_ns: u64,
    pub(crate) precompute_structural_ns: u64,
    pub(crate) precompute_eval_provider_ns: u64,
    pub(crate) precompute_work: super::super::comptime_eval::ComptimePrecomputeAttribution,
    pub(crate) constraint_generation_ns: u64,
    pub(crate) unification_resolution_ns: u64,
    /// Number of distinct selected source-graph segments and resolved
    /// instruction facts generated by staged frontier passes.  These are
    /// published with the ordinary-body breakdown to make bounded work
    /// observable rather than silently discarding staging cost.
    pub(crate) staged_frontier_bodies: u64,
    pub(crate) staged_frontier_instructions: u64,
    pub(crate) staged_fact_nodes: u64,
    pub(crate) staged_canonical_evaluations: u64,
    /// Constraints generated by the staged probe and frontier passes. The
    /// final ordinary inference pass is intentionally excluded.
    pub(crate) staged_constraints_generated: u64,
    /// Persistent lexical checkpoint nodes created while walking selectors.
    pub(crate) staged_binding_scope_nodes: u64,
    /// Selector/frontier checkpoint visits. Persistent scope tries are not
    /// flattened; this additive counter records each staged scope handoff.
    pub(crate) staged_binding_materializations: u64,
    /// Path-copied trie nodes written by persistent lexical scope updates.
    pub(crate) staged_binding_trie_updates: u64,
    /// Bounded trie levels consulted by canonical runtime-name membership.
    pub(crate) staged_binding_trie_lookups: u64,
    /// Nodes examined by the preliminary reachable-body site probe.
    pub(crate) staged_probe_nodes: u64,
}

impl InferenceBreakdown {
    fn accrue(&mut self, other: Self) {
        self.precompute_ns = self.precompute_ns.saturating_add(other.precompute_ns);
        self.precompute_structural_ns = self
            .precompute_structural_ns
            .saturating_add(other.precompute_structural_ns);
        self.precompute_eval_provider_ns = self
            .precompute_eval_provider_ns
            .saturating_add(other.precompute_eval_provider_ns);
        self.precompute_work.accrue(other.precompute_work);
        self.constraint_generation_ns = self
            .constraint_generation_ns
            .saturating_add(other.constraint_generation_ns);
        self.unification_resolution_ns = self
            .unification_resolution_ns
            .saturating_add(other.unification_resolution_ns);
        self.staged_frontier_bodies = self
            .staged_frontier_bodies
            .saturating_add(other.staged_frontier_bodies);
        self.staged_frontier_instructions = self
            .staged_frontier_instructions
            .saturating_add(other.staged_frontier_instructions);
        self.staged_fact_nodes = self
            .staged_fact_nodes
            .saturating_add(other.staged_fact_nodes);
        self.staged_canonical_evaluations = self
            .staged_canonical_evaluations
            .saturating_add(other.staged_canonical_evaluations);
        self.staged_constraints_generated = self
            .staged_constraints_generated
            .saturating_add(other.staged_constraints_generated);
        self.staged_binding_scope_nodes = self
            .staged_binding_scope_nodes
            .saturating_add(other.staged_binding_scope_nodes);
        self.staged_binding_materializations = self
            .staged_binding_materializations
            .saturating_add(other.staged_binding_materializations);
        self.staged_binding_trie_updates = self
            .staged_binding_trie_updates
            .saturating_add(other.staged_binding_trie_updates);
        self.staged_binding_trie_lookups = self
            .staged_binding_trie_lookups
            .saturating_add(other.staged_binding_trie_lookups);
        self.staged_probe_nodes = self
            .staged_probe_nodes
            .saturating_add(other.staged_probe_nodes);
    }
}

/// A body whose constraints become reachable after a canonical comptime
/// selector has been evaluated.  Staged inference consumes these frontiers
/// once, preserving the already-generated probe rather than replaying the
/// function prefix for every selector.
#[derive(Debug, Clone)]
struct ComptimeInferenceFrontier {
    body: InstRef,
    bindings: FrontierScope,
}

/// Exact lexical checkpoint state captured at a selector boundary.  A local
/// binding is identified by its Alloc instruction, rather than reconstructed
/// from a name-only map (which is ambiguous under shadowing and repeated
/// lexical names). Pattern bindings have no standalone Alloc node, so their
/// exact payload type is carried directly from the matched enum definition.
#[derive(Debug, Clone)]
struct FrontierBinding {
    name: Spur,
    ty: Option<Type>,
    mode: RirParamMode,
}

/// Persistent lexical checkpoint. Cloning a scope for each child only clones
/// the checkpoint pointer; typed and runtime-name lookups use their persistent
/// bounded tries instead of copying or flattening the visible prefix.
type FrontierScope = Option<Arc<FrontierScopeNode>>;

#[derive(Debug, Clone)]
#[allow(dead_code)]
struct FrontierScopeNode {
    binding: FrontierBinding,
    parent: FrontierScope,
    overlay: Option<Arc<FrontierParamOverlay>>,
    runtime_names: Arc<RuntimeNameTrieNode>,
}

#[derive(Debug, Clone)]
struct RuntimeNameTrieNode {
    present: bool,
    children: [Option<Arc<RuntimeNameTrieNode>>; 2],
}

impl RuntimeNameTrieNode {
    fn empty() -> Arc<Self> {
        Arc::new(Self {
            present: false,
            children: [None, None],
        })
    }

    fn insert(node: &Arc<Self>, key: u32, bit: u32) -> Arc<Self> {
        if bit == 32 {
            return Arc::new(Self {
                present: true,
                children: node.children.clone(),
            });
        }
        let index = ((key >> (31 - bit)) & 1) as usize;
        let child = node.children[index].clone().unwrap_or_else(Self::empty);
        let updated = Self::insert(&child, key, bit + 1);
        let mut children = node.children.clone();
        children[index] = Some(updated);
        Arc::new(Self {
            present: node.present,
            children,
        })
    }

    fn contains(node: &Arc<Self>, key: u32, bit: u32) -> bool {
        if bit == 32 {
            return node.present;
        }
        let index = ((key >> (31 - bit)) & 1) as usize;
        node.children[index]
            .as_ref()
            .is_some_and(|child| Self::contains(child, key, bit + 1))
    }
}

impl<H: OrdinaryBodyAnalysisHost> OrdinaryBodyEngine<'_, H> {
    fn push_frontier_scope(
        &self,
        scope: &FrontierScope,
        binding: FrontierBinding,
    ) -> FrontierScope {
        let binding_name = binding.name;
        let parent_overlay = scope.as_ref().and_then(|node| node.overlay.clone());
        let parent_runtime_names = scope
            .as_ref()
            .map(|node| node.runtime_names.clone())
            .unwrap_or_else(RuntimeNameTrieNode::empty);
        let overlay = binding
            .ty
            .map(|ty| {
                FrontierParamOverlay::insert(
                    parent_overlay.as_ref(),
                    binding.name,
                    ParamVarInfo {
                        ty: self.type_to_infer_type(ty),
                        is_inout: binding.mode == RirParamMode::Inout,
                    },
                )
            })
            .or(parent_overlay);
        Some(Arc::new(FrontierScopeNode {
            binding,
            parent: scope.clone(),
            overlay,
            runtime_names: RuntimeNameTrieNode::insert(
                &parent_runtime_names,
                binding_name.into_usize() as u32,
                0,
            ),
        }))
    }
}

fn runtime_binding_membership_view(scope: &FrontierScope) -> std::sync::Arc<dyn Fn(&Spur) -> bool> {
    let scope = scope.clone();
    std::sync::Arc::new(move |name| {
        scope.as_ref().is_some_and(|node| {
            RuntimeNameTrieNode::contains(&node.runtime_names, name.into_usize() as u32, 0)
        })
    })
}

#[derive(Clone)]
struct PrecomputeSnapshot {
    comptime_local_bindings: Arc<AHashMap<InstRef, Type>>,
    inline_ctor_head_types: Arc<AHashMap<InstRef, Type>>,
}

fn elapsed_ns(started: Instant) -> u64 {
    u64::try_from(started.elapsed().as_nanos()).unwrap_or(u64::MAX)
}

impl<H: OrdinaryBodyAnalysisHost> OrdinaryBodyEngine<'_, H> {
    /// Run Hindley-Milner type inference on a function body.
    ///
    /// This is Phases 1-2 of the HM algorithm:
    /// 1. Generate constraints by walking the RIR
    /// 2. Solve constraints via unification
    ///
    /// The `infer_ctx` parameter provides pre-computed type information (function
    /// signatures, struct/enum types, method signatures) converted to InferType format.
    /// This avoids rebuilding these maps for each function, reducing O(n²) to O(n).
    ///
    /// Returns maps from RIR instruction refs to their resolved concrete types
    /// and normal-continuation facts.
    pub(crate) fn run_type_inference(
        &mut self,
        infer_ctx: &InferenceContext,
        return_type: Type,
        params: &[(Spur, Type, RirParamMode, bool)],
        body: InstRef,
        type_subst: Option<&AHashMap<Spur, Type>>,
        value_subst: Option<&AHashMap<Spur, ConstValue>>,
    ) -> CompileResult<(
        AHashMap<InstRef, Type>,
        AHashMap<InstRef, bool>,
        AHashMap<InstRef, crate::sema::ComptimeSelection>,
        InferenceBreakdown,
    )> {
        // Most bodies have no selector or computed comptime argument that can
        // benefit from a canonical pre-pass.  Keep those bodies on the normal
        // single inference pass: besides avoiding needless work, this keeps
        // provider observation counts tied to production queries rather than
        // to speculative staging.  Value-specialized bodies always need the
        // pass because their branch/match facts are the reason they are
        // specialized in the first place.
        let has_value_specialization = value_subst.is_some_and(|values| !values.is_empty());
        let (has_fact_sites, probe_nodes) = self.has_comptime_fact_sites(body)?;
        if !has_value_specialization && !has_fact_sites {
            let result = self.run_type_inference_pass(
                infer_ctx,
                return_type,
                params,
                body,
                type_subst,
                value_subst,
                None,
                None,
                false,
                false,
                None,
                None,
            )?;
            return Ok((result.0, result.1, AHashMap::new(), result.2));
        }
        let (probe_types, _probe_continues, probe_breakdown, precompute_snapshot) = self
            .run_type_inference_pass(
                infer_ctx,
                return_type,
                params,
                body,
                type_subst,
                value_subst,
                None,
                None,
                true,
                false,
                None,
                None,
            )?;
        let facts =
            self.collect_comptime_facts(&probe_types, params, body, type_subst, value_subst, None)?;
        let (
            mut selections,
            mut argument_values,
            mut frontier,
            mut fact_nodes,
            mut canonical_evaluations,
            mut scope_nodes,
            mut scope_materializations,
        ) = facts;
        // A selected body can contain another selector whose arithmetic type
        // is established by that body's constraints.  Consume a source-graph
        // frontier: each newly reachable body is generated exactly once, and
        // only the final pass revisits the root.  This is the checkpoint
        // boundary for staged inference; the work therefore scales with the
        // reachable body graph instead of multiplying the whole prefix by the
        // number of selectors.
        let mut staged_breakdown = probe_breakdown;
        staged_breakdown.staged_probe_nodes = probe_nodes;
        let mut staged_resolved_types = probe_types;
        let mut generated_frontier = ahash::AHashSet::new();
        // Type-producing calls are reduced by the canonical semantic type
        // authority after this probe.  Their selected blocks can contain
        // declaration-only type aliases, which have no standalone ordinary
        // expression return shape; leave those blocks to the final root pass.
        if return_type != Type::COMPTIME_TYPE {
            loop {
                let Some(front) = frontier.pop_front() else {
                    break;
                };
                if !generated_frontier.insert(front.body) {
                    continue;
                }
                scope_materializations = scope_materializations.saturating_add(1);
                self.staged_frontier_started();
                let staged = self.run_type_inference_pass(
                    infer_ctx,
                    return_type,
                    params,
                    front.body,
                    type_subst,
                    value_subst,
                    Some(&selections),
                    Some(&argument_values),
                    true,
                    true,
                    Some(&precompute_snapshot),
                    Some(&front.bindings),
                )?;
                staged_breakdown.staged_frontier_bodies =
                    staged_breakdown.staged_frontier_bodies.saturating_add(1);
                staged_breakdown.staged_frontier_instructions = staged_breakdown
                    .staged_frontier_instructions
                    .saturating_add(u64::try_from(staged.0.len()).unwrap_or(u64::MAX));
                staged_breakdown.accrue(staged.2);
                staged_resolved_types.extend(staged.0.iter().map(|(inst, ty)| (*inst, *ty)));
                let (
                    nested_selections,
                    nested_arguments,
                    nested_frontier,
                    nested_fact_nodes,
                    nested_canonical_evaluations,
                    nested_scope_nodes,
                    nested_scope_materializations,
                ) = self.collect_comptime_facts(
                    &staged.0,
                    params,
                    front.body,
                    type_subst,
                    value_subst,
                    front.bindings.clone(),
                )?;
                selections.extend(nested_selections);
                argument_values.extend(nested_arguments);
                frontier.extend(nested_frontier);
                fact_nodes = fact_nodes.saturating_add(nested_fact_nodes);
                canonical_evaluations =
                    canonical_evaluations.saturating_add(nested_canonical_evaluations);
                scope_nodes = scope_nodes.saturating_add(nested_scope_nodes);
                scope_materializations =
                    scope_materializations.saturating_add(nested_scope_materializations);
            }
        }
        let result = self.run_type_inference_pass(
            infer_ctx,
            return_type,
            params,
            body,
            type_subst,
            value_subst,
            Some(&selections),
            Some(&argument_values),
            false,
            false,
            Some(&precompute_snapshot),
            None,
        )?;
        let mut breakdown = result.2;
        breakdown.accrue(staged_breakdown);
        breakdown.staged_fact_nodes = breakdown.staged_fact_nodes.saturating_add(fact_nodes);
        breakdown.staged_canonical_evaluations = breakdown
            .staged_canonical_evaluations
            .saturating_add(canonical_evaluations);
        breakdown.staged_binding_scope_nodes = breakdown
            .staged_binding_scope_nodes
            .saturating_add(scope_nodes);
        breakdown.staged_binding_materializations = breakdown
            .staged_binding_materializations
            .saturating_add(scope_materializations);
        breakdown.staged_binding_trie_updates = breakdown
            .staged_binding_trie_updates
            .saturating_add(scope_nodes.saturating_mul(33));
        breakdown.staged_binding_trie_lookups = breakdown
            .staged_binding_trie_lookups
            .saturating_add(scope_materializations.saturating_mul(33));
        Ok((result.0, result.1, selections, breakdown))
    }

    fn has_comptime_fact_sites(&self, body: InstRef) -> CompileResult<(bool, u64)> {
        // Keep the probe decision local to this body.  Scanning the packed
        // module RIR here made every function observe unrelated generic calls
        // (and made the cost proportional to body_count * module_size).
        let mut pending = vec![body];
        let mut visited = ahash::AHashSet::new();
        let mut nodes = 0_u64;
        while let Some(inst_ref) = pending.pop() {
            self.check_canceled()?;
            nodes = nodes.saturating_add(1);
            if !visited.insert(inst_ref) {
                continue;
            }
            let inst = self.body_rir_ref().get(inst_ref);
            let found = match &inst.data {
                rue_rir::InstData::Call { name, args }
                | rue_rir::InstData::MethodCall {
                    method: name, args, ..
                } => {
                    let function_key = self
                        .resolve_function_name_local(*name, inst.span.file_id)
                        .unwrap_or(*name);
                    self.function_info(function_key).is_some_and(|function| {
                        if !function.is_generic {
                            false
                        } else {
                            let param_data = self.body_param_data(function.params);
                            let param_is_type = self.comptime_type_param_flags(&function);
                            self.body_rir_ref().call_args(args).iter().enumerate().any(
                                |(index, _)| {
                                    param_data.comptime().get(index).copied().unwrap_or(false)
                                        && !param_is_type.get(index).copied().unwrap_or(false)
                                },
                            )
                        }
                    })
                }
                _ => false,
            };
            if found {
                return Ok((true, nodes));
            }
            self.body_rir_ref()
                .child_instructions(inst_ref, &mut pending);
        }
        Ok((false, nodes))
    }

    fn run_type_inference_pass(
        &mut self,
        infer_ctx: &InferenceContext,
        return_type: Type,
        params: &[(Spur, Type, RirParamMode, bool)],
        body: InstRef,
        type_subst: Option<&AHashMap<Spur, Type>>,
        value_subst: Option<&AHashMap<Spur, ConstValue>>,
        selections: Option<&AHashMap<InstRef, crate::sema::ComptimeSelection>>,
        argument_values: Option<&AHashMap<InstRef, ConstValue>>,
        staged: bool,
        frontier_mode: bool,
        precompute_snapshot: Option<&PrecomputeSnapshot>,
        frontier_scope: Option<&FrontierScope>,
    ) -> CompileResult<(
        AHashMap<InstRef, Type>,
        AHashMap<InstRef, bool>,
        InferenceBreakdown,
        PrecomputeSnapshot,
    )> {
        let precompute_started = Instant::now();
        // Pre-resolve `let`-bound comptime type aliases (`let P = F();` where
        // `F` returns `type`) so inference can see the concrete anonymous
        // struct types behind them. Without this, `P { ... }`, `let p: P`,
        // and methods on `P`-typed receivers all fell through to `<error>`
        // or unconstrained variables (RUE-170, RUE-164). This may create the
        // anonymous structs (idempotently — analysis re-evaluates the same
        // initializers later and structural equality dedups them). Keyed by
        // binding site (the `let`'s Alloc); the generator brings each alias
        // into scope when its statement is reached and unwinds it with the
        // enclosing block (RUE-530).
        let runtime_params: Vec<Spur> = params
            .iter()
            .filter_map(|(name, _, _, is_comptime)| (!is_comptime).then_some(*name))
            .collect();
        let precompute_attribution_enabled = tracing::enabled!(
            target: "rue::timing",
            tracing::Level::INFO
        );
        let (comptime_local_bindings, precompute_work, inline_ctor_head_types) =
            if let Some(snapshot) = precompute_snapshot {
                // The probe already walked and evaluated all reachable
                // aliases/inline heads. Reuse that immutable checkpoint in
                // every frontier and the final root pass; replaying these
                // recursive walks per selected body was the remaining source
                // of quadratic staged work.
                (
                    snapshot.comptime_local_bindings.clone(),
                    Default::default(),
                    snapshot.inline_ctor_head_types.clone(),
                )
            } else {
                let (comptime_local_bindings, mut precompute_work) = self
                    .precompute_comptime_type_locals(
                        body,
                        type_subst,
                        value_subst,
                        &runtime_params,
                        precompute_attribution_enabled,
                    )?;

                // The inline-head pre-reduction below evaluates head expressions
                // without walking the body, so it can't replay lexical scope; give it
                // the flattened name view. Same-named ties resolve to the later
                // binding site deterministically (instruction order, which follows
                // program order) — matching the old flat map for this opportunistic
                // path.
                let mut flat_bindings: Vec<(InstRef, Type)> = comptime_local_bindings
                    .iter()
                    .map(|(inst_ref, ty)| (*inst_ref, *ty))
                    .collect();
                flat_bindings.sort_by_key(|(inst_ref, _)| inst_ref.as_u32());
                let comptime_local_types: AHashMap<Spur, Type> = flat_bindings
                    .into_iter()
                    .filter_map(
                        |(inst_ref, ty)| match self.body_rir_ref().get(inst_ref).data {
                            rue_rir::InstData::Alloc {
                                name: Some(name), ..
                            } => Some((name, ty)),
                            _ => None,
                        },
                    )
                    .collect();

                // Pre-reduce inline type-constructor heads (`F(args).Variant(..)`,
                // `F(args) { ... }`; RUE-596) to their concrete types, keyed by the
                // head's `InstRef` — the nameless analogue of the alias map above.
                // Without this, a construction argument on an inline head was never
                // constrained and an integer payload literal defaulted to `i32`
                // (RUE-599). Runs before the lazy-method collection below so methods
                // registered while reducing a head are included in it.
                let (inline_ctor_head_types, inline_work) = self
                    .precompute_inline_ctor_head_types(
                        body,
                        type_subst,
                        value_subst,
                        &comptime_local_types,
                        precompute_attribution_enabled,
                    )?;
                precompute_work.accrue(inline_work);
                (
                    Arc::new(comptime_local_bindings),
                    precompute_work,
                    Arc::new(inline_ctor_head_types),
                )
            };
        let precompute_ns = elapsed_ns(precompute_started);
        let precompute_eval_provider_ns = precompute_work.eval_provider_ns.min(precompute_ns);
        let precompute_structural_ns = precompute_ns - precompute_eval_provider_ns;

        // Demand-population provider for the inference-context families
        // (RUE-1091 slice r5b). It materializes each consulted function/method
        // signature and struct/enum/const on first lookup from the frozen
        // declaration state, reading the live method tables — so a method call
        // on an anonymous-struct receiver whose signature was registered lazily
        // (during comptime evaluation, including the pre-pass above) resolves to
        // its declared type on first consult, subsuming the old per-body
        // `extra_method_sigs` reconciliation (RUE-164) with no behavior change.
        //
        // The provider holds an immutable borrow of `self`; it is dropped right
        // after Phase-1 constraint generation completes, before any `&mut self`
        // access resumes. This is the detached-context wiring: the shared
        // `InferenceContext` cache carries no host borrow (it outlives every
        // body's `&mut self`), while the fill source is threaded here per body,
        // sound because constraint generation reads the host only immutably.
        // Phase 1 runs in its own scope so the provider's immutable borrow of
        // `self` ends before Phase 2 resumes `&mut self` access (RUE-1091 slice
        // r5b): the shared `InferenceContext` cache holds no host borrow, and
        // the fill source is threaded here per body.
        let constraint_generation_started = Instant::now();
        let (
            constraints,
            int_literal_vars,
            string_literal_vars,
            string_literal_default,
            expr_types,
            expr_continues,
            type_var_count,
            fixed_string_types,
        ) = {
            let facts = self.inference_facts(infer_ctx);

            // Create constraint generator driven by the demand-population provider.
            let mut cgen = ConstraintGenerator::with_lazy_facts(
                self.body_rir_ref(),
                self.body_interner(),
                self.body_type_pool(),
                type_subst,
                &facts,
            );
            if let Some(check) = self.cancellation_probe() {
                cgen = cgen.with_cancellation_check(check);
            }
            if let Some(hook) = self.sibling_attempt_hook() {
                cgen = cgen.with_sibling_attempt_hook(hook);
            }
            cgen = cgen.with_strbuf_type(self.strbuf_type());
            let str_name = self
                .body_interner()
                .get("str")
                .expect("stable string default was registered before inference");
            let str_ty = facts
                .builtin_struct_type(str_name)
                .expect("canonical str type is present in the inference context");
            cgen = cgen.with_string_literal_default(str_ty);
            let mut cgen = cgen
                .with_comptime_local_bindings(&comptime_local_bindings)
                .with_inline_ctor_head_types(&inline_ctor_head_types)
                .with_comptime_values(value_subst)
                .with_comptime_selections(selections, staged)
                .with_comptime_frontier_mode(frontier_mode)
                .with_comptime_argument_values(argument_values);

            // Build parameter map for constraint context.
            // Convert Type to InferType so arrays are represented structurally.
            let mut param_vars: AHashMap<Spur, ParamVarInfo> = params
                .iter()
                .map(|(name, ty, mode, _is_comptime)| {
                    (
                        *name,
                        ParamVarInfo {
                            ty: self.type_to_infer_type(*ty),
                            is_inout: *mode == RirParamMode::Inout,
                        },
                    )
                })
                .collect();

            // Add comptime value variables as if they were parameters
            // This allows constraint generation to see captured comptime values
            // (anonymous-struct methods capturing `comptime N` from the enclosing
            // function). Real parameters keep their declared type: in a
            // value-specialized body (RUE-166) the comptime value parameter is
            // also a runtime parameter with a precise type (e.g. `comptime n:
            // i64`), inserted into `param_vars` above, which the gap-filling
            // `or_insert` here must not clobber.
            //
            // A *captured* integer value carries only its magnitude — its declared
            // width is not threaded through the capture — so it is typed as a
            // fresh integer-literal variable and takes its width from use (a
            // `comptime N: u8` read where u8 is expected unifies to u8), exactly
            // like the literal it stands in for. Emission then reads that resolved
            // width back out of `resolved_types` instead of hard-coding i32
            // (RUE-216).
            if let Some(values) = value_subst {
                for (name, const_val) in values {
                    let ty = match const_val {
                        ConstValue::Integer(_) => {
                            param_vars.entry(*name).or_insert(ParamVarInfo {
                                ty: InferType::Var(cgen.fresh_int_literal_var()),
                                is_inout: false,
                            });
                            continue;
                        }
                        ConstValue::Bool(_) => Type::BOOL,
                        ConstValue::Type(t) => *t,
                        ConstValue::Function(_) => Type::COMPTIME_TYPE,
                        // No comptime parameter has a string type, so a captured
                        // string value never occurs (RUE-957); skip rather than
                        // fabricate a type for it.
                        ConstValue::String(_) => continue,
                        ConstValue::Unit => Type::UNIT,
                    };
                    param_vars.entry(*name).or_insert(ParamVarInfo {
                        ty: self.type_to_infer_type(ty),
                        is_inout: false,
                    });
                }
            }

            // Create constraint context
            let mut cgen_ctx = ConstraintContext::new(&param_vars, return_type)
                .with_frontier_overlay(
                    frontier_scope
                        .and_then(|scope| scope.as_ref().and_then(|node| node.overlay.clone())),
                );

            // Phase 1: Generate constraints
            let body_info = cgen.generate(body, &mut cgen_ctx);
            if cgen.was_canceled() {
                // The generator stops before adding a partial instruction's
                // constraints. Re-enter the owning query boundary so its
                // cancellation authority classifies this as QueryAbort and
                // prevents publication of staged facts.
                self.check_canceled()?;
            }

            // The function body's type must match the return type.
            // This handles implicit returns like `fn foo() -> i8 { 42 }`.
            // For arrays, we need to convert Type to InferType structurally.
            //
            // String literals use marked inference variables whose allowed nominal
            // targets include `str` and `Str(N)`, so this constraint retains the
            // implicit literal coercion while rejecting every other mismatched
            // tail before AIR/CFG construction (RUE-1652).
            if !frontier_mode {
                cgen.add_constraint(Constraint::equal(
                    body_info.ty,
                    self.type_to_infer_type(return_type),
                    body_info.span,
                ));
            }

            // Consume the constraint generator to release borrows
            let (
                constraints,
                int_literal_vars,
                string_literal_vars,
                string_literal_default,
                expr_types,
                expr_continues,
                type_var_count,
                fixed_string_types,
            ) = cgen.into_parts();
            (
                constraints,
                int_literal_vars,
                string_literal_vars,
                string_literal_default,
                expr_types,
                expr_continues,
                type_var_count,
                fixed_string_types,
            )
        };
        let constraint_generation_ns = elapsed_ns(constraint_generation_started);

        // Phase 2: Solve constraints via unification
        let unification_resolution_started = Instant::now();
        // Pre-size the substitution for better performance on large functions
        let mut unifier = Unifier::with_capacity(type_var_count);
        unifier.mark_int_literal_vars(&int_literal_vars);
        // Literal contextualization is nominal. Admit only compiler-owned
        // identities: core `str`, the trusted std StrBuf language item when
        // imported, and synthetic fixed strings.
        let mut string_literal_types = vec![string_literal_default];
        string_literal_types.extend(self.strbuf_type());
        string_literal_types.extend(
            self.generated_structs()
                .values()
                .copied()
                .map(Type::new_struct)
                .filter(|&ty| self.is_str_fixed_struct(ty)),
        );
        // A provider-backed body may first encounter a generated `Str(N)` as
        // the concrete result of a queried callable, before semantic analysis
        // visits the local annotation that publishes it in `generated_structs`.
        // Constraint generation already owns the exact concrete identities it
        // consulted, so admit those fixed-string identities directly instead
        // of depending on discovery order between body transactions.
        if self.is_str_fixed_struct(return_type) {
            string_literal_types.push(return_type);
        }
        string_literal_types.extend(expr_types.values().filter_map(|ty| match ty {
            InferType::Concrete(ty) if self.is_str_fixed_struct(*ty) => Some(*ty),
            _ => None,
        }));
        // Provider-backed constraint generation may consult a generated
        // fixed-string identity only through a structural payload shape (for
        // example `Message.Text(Str(8))`). Carry those exact identities from
        // the constraints into unification; the generated-name map is not a
        // complete authority for demand-populated declarations.
        string_literal_types.extend(fixed_string_types);
        string_literal_types.sort_unstable_by_key(Type::as_u32);
        string_literal_types.dedup();
        unifier.mark_string_literal_vars(&string_literal_vars, &string_literal_types);
        let equivalence_queries = std::cell::Cell::new(0usize);
        let errors = unifier.solve_constraints_with(&constraints, &|left, right| {
            if left == right {
                return true;
            }
            equivalence_queries.set(equivalence_queries.get() + 1);
            self.types_equivalent(left, right)
        });
        self.body_analysis_work_mut()
            .semantic_type_equivalence_queries += equivalence_queries.get();

        // Convert unification errors to compile errors
        // For now, we collect the first error. In the future, we could
        // report multiple errors for better diagnostics.
        if let Some(err) = errors.first() {
            // Map each UnifyResult variant to the appropriate ErrorKind
            let error_kind = match &err.kind {
                UnifyResult::Ok => unreachable!("UnificationError should never contain Ok"),
                UnifyResult::TypeMismatch { expected, found } => ErrorKind::TypeMismatch {
                    expected: self.format_infer_type_name(expected),
                    found: self.format_infer_type_name(found),
                },
                UnifyResult::IntLiteralNonInteger { found } => ErrorKind::TypeMismatch {
                    expected: "integer type".to_string(),
                    found: self.format_type_name(*found),
                },
                UnifyResult::StringLiteralNonString { found } => ErrorKind::TypeMismatch {
                    expected: "string type".to_string(),
                    found: self.format_infer_type_name(found),
                },
                UnifyResult::OccursCheck { var, ty } => ErrorKind::TypeMismatch {
                    expected: "non-recursive type".to_string(),
                    found: format!(
                        "{var} = {} (infinite type)",
                        self.format_infer_type_name(ty)
                    ),
                },
                UnifyResult::NotSigned { ty } => {
                    ErrorKind::CannotNegate(self.format_type_name(*ty))
                }
                UnifyResult::NotInteger { ty } => ErrorKind::TypeMismatch {
                    expected: "integer type".to_string(),
                    found: self.format_type_name(*ty),
                },
                UnifyResult::NotUnsigned { ty } => ErrorKind::TypeMismatch {
                    expected: "unsigned integer type".to_string(),
                    found: self.format_type_name(*ty),
                },
                UnifyResult::ArrayLengthMismatch { expected, found } => {
                    ErrorKind::ArrayLengthMismatch {
                        expected: *expected,
                        found: *found,
                    }
                }
            };

            let mut compile_error = CompileError::new(error_kind, err.span);

            // Add note for unsigned negation errors
            if matches!(err.kind, UnifyResult::NotSigned { .. }) {
                compile_error = compile_error.with_note("unsigned values cannot be negated");
            }

            return Err(compile_error);
        }

        // Default any unconstrained integer literals to i32
        unifier.default_int_literal_vars(&int_literal_vars);
        unifier.default_unconstrained_vars(&string_literal_vars, string_literal_default);

        // Pre-collect all array types from resolved InferTypes before converting them.
        // This ensures all array types are created before the conversion loop, which
        // enables parallelization of function analysis (mutation happens here, not in
        // infer_type_to_type).
        //
        // `expr_types` is an unordered lookup map. RIR instruction order is the
        // canonical order for pool allocation; relying on a map walk here would
        // make array Type values depend on the process hash seed.
        let ordered_expr_types = crate::inference::expr_types_in_rir_order(&expr_types);
        for (_, infer_ty) in &ordered_expr_types {
            let resolved = unifier.resolve_infer_type(infer_ty);
            self.pre_create_array_types_from_infer_type(&resolved);
        }

        // Build the resolved types map, converting InferType to Type.
        // Since we pre-created all array types above, infer_type_to_type only
        // performs lookups (no mutation).
        let mut resolved_types = AHashMap::new();
        for (inst_ref, infer_ty) in ordered_expr_types {
            let resolved = unifier.resolve_infer_type(infer_ty);
            let concrete_ty = self.infer_type_to_type(&resolved);
            resolved_types.insert(*inst_ref, concrete_ty);
        }

        let unification_resolution_ns = elapsed_ns(unification_resolution_started);
        Ok((
            resolved_types,
            expr_continues.into_iter().collect(),
            InferenceBreakdown {
                precompute_ns,
                precompute_structural_ns,
                precompute_eval_provider_ns,
                precompute_work,
                constraint_generation_ns,
                unification_resolution_ns,
                staged_frontier_bodies: 0,
                staged_frontier_instructions: 0,
                staged_fact_nodes: 0,
                staged_canonical_evaluations: 0,
                staged_constraints_generated: if staged { constraints.len() as u64 } else { 0 },
                staged_binding_scope_nodes: 0,
                staged_binding_materializations: 0,
                staged_binding_trie_updates: 0,
                staged_binding_trie_lookups: 0,
                staged_probe_nodes: 0,
            },
            PrecomputeSnapshot {
                comptime_local_bindings,
                inline_ctor_head_types,
            },
        ))
    }

    fn collect_comptime_facts(
        &mut self,
        resolved_types: &AHashMap<InstRef, Type>,
        params: &[(Spur, Type, RirParamMode, bool)],
        _body: InstRef,
        type_subst: Option<&AHashMap<Spur, Type>>,
        value_subst: Option<&AHashMap<Spur, ConstValue>>,
        inherited_scope: FrontierScope,
    ) -> CompileResult<(
        AHashMap<InstRef, crate::sema::ComptimeSelection>,
        AHashMap<InstRef, ConstValue>,
        VecDeque<ComptimeInferenceFrontier>,
        u64,
        u64,
        u64,
        u64,
    )> {
        let mut runtime_bindings = inherited_scope;
        let mut scope_nodes = 0_u64;
        if runtime_bindings.is_none() {
            for (name, ty, mode, is_comptime) in params {
                if !*is_comptime {
                    scope_nodes = scope_nodes.saturating_add(1);
                    runtime_bindings = self.push_frontier_scope(
                        &runtime_bindings,
                        FrontierBinding {
                            name: *name,
                            ty: Some(*ty),
                            mode: *mode,
                        },
                    );
                }
            }
        }
        let mut selections = AHashMap::new();
        let mut argument_values = AHashMap::new();
        let mut frontier = VecDeque::new();
        let can_select = value_subst.is_some_and(|values| !values.is_empty());
        enum FactTask {
            Visit {
                inst_ref: InstRef,
                bindings: FrontierScope,
            },
            SelectBranch {
                inst_ref: InstRef,
                condition: InstRef,
                bindings: FrontierScope,
            },
            BranchBody {
                inst_ref: InstRef,
                then_block: InstRef,
                else_block: Option<InstRef>,
                bindings: FrontierScope,
            },
            MatchBody {
                inst_ref: InstRef,
                scrutinee: InstRef,
                arms: rue_rir::RirMatchArmsRange,
                bindings: FrontierScope,
            },
            SelectMatch {
                inst_ref: InstRef,
                scrutinee: InstRef,
                arms: rue_rir::RirMatchArmsRange,
                bindings: FrontierScope,
            },
        }
        let mut tasks = vec![FactTask::Visit {
            inst_ref: _body,
            bindings: runtime_bindings,
        }];
        let mut visited = ahash::AHashSet::new();
        let mut fact_nodes = 0_u64;
        let mut canonical_evaluations = 0_u64;
        let mut scope_materializations = 0_u64;
        while let Some(task) = tasks.pop() {
            self.check_canceled()?;
            fact_nodes = fact_nodes.saturating_add(1);
            match task {
                FactTask::SelectBranch {
                    inst_ref,
                    condition,
                    bindings,
                } => {
                    if can_select {
                        canonical_evaluations = canonical_evaluations.saturating_add(1);
                        scope_materializations = scope_materializations.saturating_add(1);
                        if let Some(taken) = self
                            .select_comptime_branch_with_resolved_types_and_membership(
                                condition,
                                resolved_types,
                                type_subst,
                                value_subst,
                                runtime_binding_membership_view(&bindings),
                            )?
                        {
                            selections
                                .insert(inst_ref, crate::sema::ComptimeSelection::Branch { taken });
                        }
                    }
                }
                FactTask::BranchBody {
                    inst_ref,
                    then_block,
                    else_block,
                    bindings,
                } => {
                    if let Some(crate::sema::ComptimeSelection::Branch { taken }) =
                        selections.get(&inst_ref)
                    {
                        let selected = if *taken { Some(then_block) } else { else_block };
                        if let Some(selected) = selected {
                            frontier.push_back(ComptimeInferenceFrontier {
                                body: selected,
                                bindings: bindings.clone(),
                            });
                        }
                    } else {
                        if let Some(else_block) = else_block {
                            tasks.push(FactTask::Visit {
                                inst_ref: else_block,
                                bindings: bindings.clone(),
                            });
                        }
                        tasks.push(FactTask::Visit {
                            inst_ref: then_block,
                            bindings,
                        });
                    }
                }
                FactTask::MatchBody {
                    inst_ref,
                    scrutinee,
                    arms,
                    bindings,
                } => {
                    let arm_refs = self
                        .body_rir_ref()
                        .match_arms(&arms)
                        .iter()
                        .map(|(pattern, body)| {
                            let mut names = bindings.clone();
                            let payload_types = resolved_types
                                .get(&scrutinee)
                                .and_then(Type::as_enum)
                                .and_then(|enum_id| {
                                    let def = self.body_type_pool().enum_def(enum_id);
                                    let rue_rir::RirPatternView::Path { variant, .. } = &pattern
                                    else {
                                        return None;
                                    };
                                    let variant_name = self.body_interner().resolve(variant);
                                    def.find_variant(variant_name)
                                        .map(|index| def.variant_payload(index).to_vec())
                                });
                            if let rue_rir::RirPatternView::Path { bindings, .. } = pattern {
                                for (index, binding) in bindings.into_iter().enumerate() {
                                    scope_nodes = scope_nodes.saturating_add(1);
                                    names = self.push_frontier_scope(
                                        &names,
                                        FrontierBinding {
                                            name: binding,
                                            ty: payload_types
                                                .as_ref()
                                                .and_then(|types| types.get(index).copied()),
                                            mode: RirParamMode::Normal,
                                        },
                                    );
                                }
                            }
                            (body, names)
                        })
                        .collect::<Vec<_>>();
                    if let Some(crate::sema::ComptimeSelection::Match { arm }) =
                        selections.get(&inst_ref)
                    {
                        if let Some((body, names)) = arm_refs.get(*arm) {
                            frontier.push_back(ComptimeInferenceFrontier {
                                body: *body,
                                bindings: names.clone(),
                            });
                        }
                    } else {
                        for (body, names) in arm_refs.into_iter().rev() {
                            tasks.push(FactTask::Visit {
                                inst_ref: body,
                                bindings: names,
                            });
                        }
                    }
                }
                FactTask::SelectMatch {
                    inst_ref,
                    scrutinee,
                    arms,
                    bindings,
                } => {
                    if can_select {
                        canonical_evaluations = canonical_evaluations.saturating_add(1);
                        scope_materializations = scope_materializations.saturating_add(1);
                        if let Some(arm) = self
                            .select_comptime_match_with_resolved_types_and_membership(
                                scrutinee,
                                &arms,
                                resolved_types,
                                type_subst,
                                value_subst,
                                runtime_binding_membership_view(&bindings),
                            )?
                        {
                            selections
                                .insert(inst_ref, crate::sema::ComptimeSelection::Match { arm });
                        }
                    }
                }
                FactTask::Visit { inst_ref, bindings } => {
                    if !visited.insert(inst_ref) {
                        continue;
                    }
                    let (inst_data, inst_span) = {
                        let inst = self.body_rir_ref().get(inst_ref);
                        (inst.data.clone(), inst.span)
                    };
                    match &inst_data {
                        rue_rir::InstData::Branch {
                            cond,
                            then_block,
                            else_block,
                        } => {
                            tasks.push(FactTask::BranchBody {
                                inst_ref,
                                then_block: *then_block,
                                else_block: *else_block,
                                bindings: bindings.clone(),
                            });
                            tasks.push(FactTask::SelectBranch {
                                inst_ref,
                                condition: *cond,
                                bindings: bindings.clone(),
                            });
                            tasks.push(FactTask::Visit {
                                inst_ref: *cond,
                                bindings: bindings.clone(),
                            });
                        }
                        rue_rir::InstData::Match { scrutinee, arms } => {
                            tasks.push(FactTask::MatchBody {
                                inst_ref,
                                scrutinee: *scrutinee,
                                arms: arms.clone(),
                                bindings: bindings.clone(),
                            });
                            tasks.push(FactTask::SelectMatch {
                                inst_ref,
                                scrutinee: *scrutinee,
                                arms: arms.clone(),
                                bindings: bindings.clone(),
                            });
                            tasks.push(FactTask::Visit {
                                inst_ref: *scrutinee,
                                bindings: bindings.clone(),
                            });
                        }
                        rue_rir::InstData::Call { name, args } => {
                            let call_span = inst_span;
                            let function_key = self
                                .resolve_function_name_local(*name, call_span.file_id)
                                .unwrap_or(*name);
                            let call_args = self.body_rir_ref().call_args(args).to_vec();
                            canonical_evaluations = canonical_evaluations.saturating_add(
                                self.collect_generic_argument_facts(
                                    function_key,
                                    &call_args,
                                    call_span,
                                    resolved_types,
                                    type_subst,
                                    value_subst,
                                    &bindings,
                                    &mut argument_values,
                                ),
                            );
                        }
                        rue_rir::InstData::MethodCall {
                            receiver,
                            method,
                            args,
                        } => {
                            if let Some(module) =
                                resolved_types.get(receiver).and_then(Type::as_module)
                            {
                                let module_file = self.module_def(module).file_id;
                                if let Some(function_key) =
                                    self.resolve_function_name_local(*method, module_file)
                                {
                                    let call_args = self.body_rir_ref().call_args(args).to_vec();
                                    canonical_evaluations = canonical_evaluations.saturating_add(
                                        self.collect_generic_argument_facts(
                                            function_key,
                                            &call_args,
                                            inst_span,
                                            resolved_types,
                                            type_subst,
                                            value_subst,
                                            &bindings,
                                            &mut argument_values,
                                        ),
                                    );
                                }
                            }
                        }
                        _ => {}
                    }
                    if let rue_rir::InstData::Block { instructions } = &inst_data {
                        // A block is the one place where lexical bindings are
                        // introduced in sequence.  Carry a scope snapshot on
                        // each work item so a later selector sees a shadowing
                        // `let`, while its initializer still sees the outer
                        // scope.  The fact walk remains one bounded traversal.
                        let mut scoped = bindings;
                        let mut children = Vec::new();
                        for child in self.body_rir_ref().block_insts(instructions).values() {
                            children.push((child, scoped.clone()));
                            if let rue_rir::InstData::Alloc {
                                name: Some(name), ..
                            } = &self.body_rir_ref().get(child).data
                            {
                                scope_nodes = scope_nodes.saturating_add(1);
                                scoped = self.push_frontier_scope(
                                    &scoped,
                                    FrontierBinding {
                                        name: *name,
                                        ty: resolved_types.get(&child).copied(),
                                        mode: RirParamMode::Normal,
                                    },
                                );
                            }
                        }
                        for (child, names) in children.into_iter().rev() {
                            tasks.push(FactTask::Visit {
                                inst_ref: child,
                                bindings: names,
                            });
                        }
                    } else if !matches!(
                        inst_data,
                        rue_rir::InstData::Branch { .. } | rue_rir::InstData::Match { .. }
                    ) {
                        let mut children = Vec::new();
                        self.body_rir_ref()
                            .child_instructions(inst_ref, &mut children);
                        for child in children.into_iter().rev() {
                            tasks.push(FactTask::Visit {
                                inst_ref: child,
                                bindings: bindings.clone(),
                            });
                        }
                    }
                }
            }
        }
        Ok((
            selections,
            argument_values,
            frontier,
            fact_nodes,
            canonical_evaluations,
            scope_nodes,
            scope_materializations,
        ))
    }

    fn collect_generic_argument_facts(
        &mut self,
        function_key: Spur,
        call_args: &[rue_rir::RirCallArg],
        call_span: Span,
        resolved_types: &AHashMap<InstRef, Type>,
        type_subst: Option<&AHashMap<Spur, Type>>,
        value_subst: Option<&AHashMap<Spur, ConstValue>>,
        scope: &FrontierScope,
        argument_values: &mut AHashMap<InstRef, ConstValue>,
    ) -> u64 {
        let Some(function) = self.function_info(function_key) else {
            return 0;
        };
        if !function.is_generic {
            return 0;
        }
        let param_data = self.body_param_data(function.params);
        let param_names = param_data.names().to_vec();
        let param_is_type = self.comptime_type_param_flags(&function);
        let mut callee_types = AHashMap::new();
        let mut callee_values = AHashMap::new();
        let mut canonical_evaluations = 0_u64;
        for (index, arg) in call_args.iter().enumerate() {
            let Some(declared) = param_data.types().get(index).copied() else {
                continue;
            };
            if !param_data.comptime().get(index).copied().unwrap_or(false)
                || index >= param_names.len()
            {
                continue;
            }
            if param_is_type.get(index).copied().unwrap_or(false) {
                canonical_evaluations = canonical_evaluations.saturating_add(1);
                if let Some(ConstValue::Type(ty)) = self
                    .try_evaluate_const_with_resolved_types_and_membership(
                        arg.value,
                        resolved_types,
                        type_subst,
                        value_subst,
                        runtime_binding_membership_view(scope),
                        None,
                    )
                {
                    argument_values.insert(arg.value, ConstValue::Type(ty));
                    callee_types.insert(param_names[index], ty);
                }
                continue;
            }
            let expected = if declared.is_comptime_type() {
                self.resolve_substituted_param_type(
                    &function,
                    index,
                    declared,
                    &callee_types,
                    &callee_values,
                    call_span,
                )
                .ok()
            } else {
                Some(declared)
            };
            let Some(expected) = expected else {
                continue;
            };
            canonical_evaluations = canonical_evaluations.saturating_add(1);
            if let Some(value) = self.try_evaluate_const_with_resolved_types_and_membership(
                arg.value,
                resolved_types,
                type_subst,
                value_subst,
                runtime_binding_membership_view(scope),
                Some(expected),
            ) {
                argument_values.insert(arg.value, value);
                callee_values.insert(param_names[index], value);
            }
        }
        canonical_evaluations
    }
    /// Analyze an RIR instruction for projection (field access).
    ///
    /// This is like `analyze_inst` but does NOT mark non-Copy values as moved.
    /// Used for field access where we're reading from a struct without consuming it.
    /// We still check that the variable hasn't already been moved (fully moved).
    /// Field-level move checking is done at the FieldGet level, not here.
    pub(crate) fn analyze_inst_for_projection(
        &mut self,
        air: &mut Air,
        inst_ref: InstRef,
        ctx: &mut AnalysisContext,
    ) -> CompileResult<AnalysisResult> {
        let inst = {
            let source = self.body_rir_ref().get(inst_ref);
            rue_rir::Inst {
                data: source.data.clone(),
                span: source.span,
            }
        };

        // For VarRef, we handle it specially: check for full moves but don't mark as moved
        if let InstData::VarRef { name, anchor } = &inst.data {
            // Check if it's a parameter — unless a `let` shadowed it with a
            // same-named local, which then wins for all later references
            // (spec 5.1:10, RUE-278); the local is resolved just below.
            if !ctx.locals.contains_key(name) {
                if let Some(param_info) = ctx.param(*name) {
                    let ty = param_info.ty;

                    // Check if this parameter has been fully moved
                    // (Partial moves are checked at the FieldGet level)
                    if let Some(move_state) = self.moved_state(ctx, name) {
                        if let Some(moved_span) = move_state.full_move {
                            let name_str = self.body_interner().resolve(&*name);
                            return Err(CompileError::new(
                                ErrorKind::UseAfterMove(name_str.to_string()),
                                inst.span,
                            )
                            .with_label("value moved here", moved_span)
                            .with_help(super::borrow_instead_of_move_help(name_str)));
                        }
                    }

                    // NOTE: We do NOT mark as moved here - this is a projection

                    let air_ref = air.add_inst(AirInst {
                        data: AirInstData::Param {
                            index: param_info.abi_slot,
                        },
                        ty,
                        span: inst.span,
                    });
                    return Ok(AnalysisResult::new(air_ref, ty));
                }
            }

            // Look up the variable in locals
            let name_str = self.body_interner().resolve(&*name);
            let Some(local) = ctx.locals.get(name) else {
                // Not a param or local: fall back to the main VarRef path so
                // file-level constants (and comptime vars/type names) resolve
                // in projection positions too — e.g. `N == 1` routes its
                // operands through here (RUE-165). Constants inline a fresh
                // value, so there is no move state to preserve, and unknown
                // names still get E0201 from the fallback.
                let resolved_ty = ctx.resolved_type_of(inst_ref);
                return self.analyze_var_ref(
                    air,
                    *name,
                    anchor.clone(),
                    inst.span,
                    resolved_ty,
                    ctx,
                );
            };

            let ty = local.ty;
            let slot = local.slot;

            // Check if this variable has been fully moved
            // (Partial moves are checked at the FieldGet level)
            if let Some(move_state) = self.moved_state(ctx, name) {
                if let Some(moved_span) = move_state.full_move {
                    return Err(CompileError::new(
                        ErrorKind::UseAfterMove(name_str.to_string()),
                        inst.span,
                    )
                    .with_label("value moved here", moved_span)
                    .with_help(super::borrow_instead_of_move_help(name_str)));
                }
            }

            // NOTE: We do NOT mark as moved here - this is a projection

            // Mark variable as used
            ctx.used_locals.insert(*name);

            // Load the variable
            let air_ref = air.add_inst(AirInst {
                data: AirInstData::Load { slot },
                ty,
                span: inst.span,
            });
            return Ok(AnalysisResult::new(air_ref, ty));
        }

        // For nested field access (e.g., a.b.c), recursively use projection mode
        if let InstData::FieldGet { base, field } = &inst.data {
            let (base, field, field_span) = (*base, *field, inst.span);

            // `Enum.Variant` (RUE-488): a field access on a bare enum type name
            // is an enum-variant value, even in a projection/read position such
            // as a comparison operand (`Color.Red == Color.Red`). Mirror the
            // reroute in `analyze_field_get`, including the module-qualified
            // form `module.Enum.Variant`.
            if let InstData::VarRef { name, .. } = self.body_rir_ref().get(base).data
                && !self.is_runtime_value_binding(name, ctx)
                && let Some(result) =
                    self.try_analyze_dotted_enum_variant(air, name, field, field_span, ctx)?
            {
                return Ok(result);
            }
            if let InstData::FieldGet {
                base: module_ref,
                field: type_name,
            } = self.body_rir_ref().get(base).data
                && let Some(result) = self.try_analyze_module_dotted_enum_variant(
                    air, module_ref, type_name, field, field_span, ctx,
                )?
            {
                return Ok(result);
            }

            // Projection-mode reads borrow their source rather than moving it.
            // Keep addressable local/parameter chains as one canonical place;
            // only computed rvalues need the temporary spill below.
            if let Some(result) = self.try_read_traced_place(air, inst_ref, field_span, ctx)? {
                return Ok(result);
            }

            let base_result = self.analyze_inst_for_projection(air, base, ctx)?;
            let base_type = base_result.ty;

            // Module member access in a projection position: equality
            // operands are read through a shared borrow (4.3:3f), so a
            // module-qualified constant (`tag == m.CONST`) reaches this arm
            // with a module-typed base. Resolve it as a member access —
            // mirroring `analyze_field_get`'s fallback — instead of
            // rejecting it as field access on a non-struct (RUE-632). A
            // constant inlines a fresh value, so no move state applies.
            if let Some(module_id) = base_type.as_module() {
                return self.analyze_module_type_member_access(
                    air,
                    module_id,
                    field,
                    super::const_use_anchor_of(self.body_rir_ref(), base),
                    field_span,
                    ctx,
                );
            }

            let struct_id = match base_type.kind() {
                TypeKind::Struct(id) => id,
                _ => {
                    return Err(CompileError::new(
                        ErrorKind::FieldAccessOnNonStruct {
                            found: self.format_type_name(base_type),
                        },
                        field_span,
                    ));
                }
            };

            let struct_def = self.body_type_pool().struct_def(struct_id);
            let field_name = self.body_interner().resolve(&field);
            let Some((field_index, struct_field)) = struct_def.find_field(field_name) else {
                return Err(CompileError::new(
                    ErrorKind::UnknownField {
                        struct_name: self.format_type_name(Type::new_struct(struct_id)),
                        field_name: field_name.to_string(),
                    },
                    field_span,
                ));
            };

            let field_type = struct_field.ty;

            let air_ref = self.emit_projected_rvalue_read(
                air,
                base_result.air_ref,
                base_type,
                AirProjection::Field {
                    struct_id,
                    field_index: field_index as u32,
                },
                field_type,
                field_span,
                ctx,
            )?;
            return Ok(AnalysisResult::new(air_ref, field_type));
        }

        // For index access in projection mode (e.g., `arr[i].field`), we allow the
        // indexing without checking if the element type is Copy. This enables
        // accessing Copy fields of non-Copy array elements.
        if let InstData::IndexGet { base, index } = &inst.data {
            // Snapshot the base root's move state before analysis, in case this
            // is a String/str/slice byte index in projection mode (RUE-700).
            let base_root = self.extract_root_variable(*base);
            let base_move_state_before = self.snapshot_move_state_value(base_root, ctx);

            // Recursively analyze the base in projection mode
            let base_result = self.analyze_inst_for_projection(air, *base, ctx)?;
            let base_type = base_result.ty;

            // Binary-op operands are analyzed in projection mode (see
            // `analyze_builtin_binary_op`), so a String/str/slice byte index used
            // inside a condition — `if s[0] == 45`, `while s[i] != 0` — reaches
            // here with a non-array base. Mirror `analyze_index_get`'s non-array
            // delegation (`s[i] -> byte_at`) instead of rejecting it with E0900
            // (RUE-700); a let-bound `let c = s[0]` already goes through the
            // String-aware path.
            if self.is_strbuf(base_type) {
                return self.analyze_string_index_get(
                    air,
                    base_result,
                    base_root,
                    base_move_state_before,
                    *index,
                    inst.span,
                    ctx,
                );
            }
            if self.is_str_like(base_type) {
                return self.analyze_str_index_get(
                    air,
                    base_result,
                    base_root,
                    base_move_state_before,
                    *index,
                    inst.span,
                    ctx,
                );
            }
            if let Some(elem_ty) = self.slice_element_type(base_type) {
                return self.analyze_slice_index_get(
                    air,
                    base_result,
                    base_root,
                    base_move_state_before,
                    *index,
                    elem_ty,
                    inst.span,
                    ctx,
                );
            }

            let array_type_id = match base_type.kind() {
                TypeKind::Array(id) => id,
                _ => {
                    return Err(CompileError::new(
                        ErrorKind::IndexOnNonArray {
                            found: self.format_type_name(base_type),
                        },
                        inst.span,
                    ));
                }
            };

            let (element_type, length) = self.body_type_pool().array_def(array_type_id);

            // Index must be an integer type (signed or unsigned) per spec
            // 7.1:7. A negative or out-of-range runtime index is not a type
            // error; it traps at runtime via the bounds check (RUE-81).
            let index_result = self.analyze_inst(air, *index, ctx)?;
            // Use the AIR instruction's type as the final guard. During
            // generic analysis the lightweight result can be `ERROR` while
            // the emitted value still carries a concrete non-integer type;
            // allowing that value into a projection produces invalid AIR.
            let index_type = air.get(index_result.air_ref).ty;
            if !index_type.is_integer() {
                return Err(CompileError::new(
                    ErrorKind::TypeMismatch {
                        expected: "integer type".to_string(),
                        found: self.format_type_name(index_type),
                    },
                    self.body_rir_ref().get(*index).span,
                ));
            }

            let array_length = length;

            // Compile-time bounds check for constant indices, evaluated at the
            // index's resolved operand types so an overflowing index expression
            // is a compile-time error, not a folded runtime panic (RUE-234).
            if let Some(const_index) = self.try_get_const_index_checked(*index, ctx)? {
                if const_index < 0 || const_index >= array_length as i128 {
                    return Err(CompileError::new(
                        ErrorKind::IndexOutOfBounds {
                            index: const_index,
                            length: array_length,
                        },
                        self.body_rir_ref().get(*index).span,
                    ));
                }
            }

            // NOTE: We do NOT check if element_type is Copy here.
            // In projection mode, we allow accessing elements for further projection
            // (e.g., arr[i].field where field is Copy).

            let air_ref = self.emit_projected_rvalue_read(
                air,
                base_result.air_ref,
                base_type,
                AirProjection::Index {
                    array_type: base_type,
                    index: index_result.air_ref,
                },
                element_type,
                inst.span,
                ctx,
            )?;
            return Ok(AnalysisResult::new(air_ref, element_type));
        }

        // A `-> borrow T` accessor call is a place in projection position
        // (ADR-0062): read it through the traced place, so comparing or
        // projecting a drop-glue element borrows rather than copies it.
        if matches!(&inst.data, InstData::MethodCall { .. })
            && self.place_root_with_accessors(inst_ref, ctx).is_some()
            && let Some(result) = self.try_read_traced_place(air, inst_ref, inst.span, ctx)?
        {
            return Ok(result);
        }

        // For other expressions, use the normal analyze_inst
        // (they will trigger move semantics as expected)
        self.analyze_inst(air, inst_ref, ctx)
    }

    /// Look up the resolved type for an instruction from HM inference.
    ///
    /// Returns an `InternalError` if the type was not resolved. This should
    /// never happen in normal operation, but provides a better error message
    /// than a panic if there's a bug in type inference.
    pub(crate) fn get_resolved_type(
        ctx: &AnalysisContext,
        inst_ref: InstRef,
        span: Span,
        context: &str,
    ) -> CompileResult<Type> {
        ctx.resolved_type_of(inst_ref).ok_or_else(|| {
            CompileError::new(
                ErrorKind::InternalError(format!(
                    "type inference did not resolve type for {} (instruction {:?})",
                    context, inst_ref
                )),
                span,
            )
        })
    }
}
