load("//crates:defs.bzl", "rue_crate")

filegroup(
    name = "runtime-abi-inventory-sources",
    srcs = glob(["src/**/*.rs"]),
    visibility = ["PUBLIC"],
)

rue_crate(
    name = "rue-linker",
    deps = [
        "//crates/rue-target:rue-target",
        "//third-party:tracing",
    ],
)
