rust_library(
    name = "rue-linker",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//crates/rue-target:rue-target",
        "//third-party:tracing",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "rue-linker-test",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//crates/rue-target:rue-target",
        "//third-party:tracing",
    ],
)
