load("//crates:defs.bzl", "rue_crate")

rue_crate(
    name = "rue-linker",
    test_platform = "native",
    deps = [
        "//crates/rue-target:rue-target",
        "//third-party:tracing",
    ],
)
